ConceptActionGrammarGenerator: it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker Class Reference
it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker Class Reference
Public Member Functions
void setPolicy (Boolean useLeft)
Boolean getPolicy ()
PseudoBinaryNode getNewRoot ()
void walkLeftFirst ()
void walkRightFirst ()
void walkPseudoBynary (Boolean useLeft)
void walkDepthFirst ()
PseudoBinaryNode getRoot ()
Protected Member Functions
CopyBinaryWalker (PseudoBinaryNode root, Boolean updateCopyId, Map< Long, List< String >> tags, Boolean resetOriginalId)
CopyBinaryWalker (PseudoBinaryNode root, Boolean updateCopyId)
CopyBinaryWalker (PseudoBinaryNode root, Boolean updateCopyId, Map< Long, List< String >> tags, Boolean resetOriginalId, Boolean useLeft)
CopyBinaryWalker (PseudoBinaryNode root, Boolean updateCopyId, Boolean useLeft)
void walkForAll (BaseNode node)
Private Attributes
Boolean useLeft
Detailed Description
Definition at line 341 of file PseudoBinaryNode.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker.CopyBinaryWalker (PseudoBinaryNode root, Boolean updateCopyId, Map< Long, List< String >> tags, Boolean resetOriginalId) protected
Definition at line 345 of file PseudoBinaryNode.java.
it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker.CopyBinaryWalker (PseudoBinaryNode root, Boolean updateCopyId) protected
Definition at line 348 of file PseudoBinaryNode.java.
it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker.CopyBinaryWalker (PseudoBinaryNode root, Boolean updateCopyId, Map< Long, List< String >> tags, Boolean resetOriginalId, Boolean useLeft) protected
Definition at line 351 of file PseudoBinaryNode.java.
it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker.CopyBinaryWalker (PseudoBinaryNode root, Boolean updateCopyId, Boolean useLeft) protected
Definition at line 355 of file PseudoBinaryNode.java.
Member Function Documentation
PseudoBinaryNode it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker.getNewRoot ()
Definition at line 367 of file PseudoBinaryNode.java.
Boolean it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker.getPolicy ()
Definition at line 363 of file PseudoBinaryNode.java.
PseudoBinaryNode it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker.getRoot ()
Definition at line 398 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker.setPolicy (Boolean useLeft)
Definition at line 360 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker.walkDepthFirst ()
Definition at line 390 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker.walkForAll (BaseNode node) protected
Definition at line 403 of file PseudoBinaryNode.java.
References it.emarolab.cagg.core.PseudoBinaryNode.getLeftChild(), it.emarolab.cagg.core.PseudoBinaryNode.getRightChild(), it.emarolab.cagg.core.PseudoBinaryNode.hasLeftChild(), and it.emarolab.cagg.core.PseudoBinaryNode.hasRightChild().
void it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker.walkLeftFirst ()
Definition at line 371 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker.walkPseudoBynary (Boolean useLeft)
Definition at line 383 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker.walkRightFirst ()
Definition at line 377 of file PseudoBinaryNode.java.
Member Data Documentation
Boolean it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker.useLeft private
Definition at line 343 of file PseudoBinaryNode.java.
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/PseudoBinaryNode.java