ConceptActionGrammarGenerator: it.emarolab.cagg.example.MultiGrammarTesting Class Reference
it.emarolab.cagg.example.MultiGrammarTesting Class Reference
Static Public Member Functions
static List
< CaggMultiGrammarTesterConfiguration > getConfigurations ()
static void main (String[] args)
Static Public Attributes
static final List< String > USER_COMMANDS = new ArrayList<>()
static final List< String > GRAMMAR_PATHS = new ArrayList<>()
static final List< String > TEST_NAMES = new ArrayList<>()
static final List< String > EVALUATOR_LOGGING_NAMES = new ArrayList<>()
static final List< String > FORMATTER_LOGGING_NAMES = new ArrayList<>()
static final Float EVALUATION_TIME_OUT = 5.0f
Detailed Description
Definition at line 12 of file MultiGrammarTesting.java.
Member Function Documentation
static List< CaggMultiGrammarTesterConfiguration> it.emarolab.cagg.example.MultiGrammarTesting.getConfigurations () static
Definition at line 49 of file MultiGrammarTesting.java.
References it.emarolab.cagg.example.MultiGrammarTesting.EVALUATOR_LOGGING_NAMES, it.emarolab.cagg.example.MultiGrammarTesting.FORMATTER_LOGGING_NAMES, it.emarolab.cagg.example.MultiGrammarTesting.GRAMMAR_PATHS, and it.emarolab.cagg.example.MultiGrammarTesting.TEST_NAMES.
Referenced by it.emarolab.cagg.example.MultiGrammarTesting.main().
static void it.emarolab.cagg.example.MultiGrammarTesting.main (String[] args) static
Definition at line 67 of file MultiGrammarTesting.java.
References it.emarolab.cagg.example.MultiGrammarTesting.EVALUATION_TIME_OUT, it.emarolab.cagg.example.MultiGrammarTesting.getConfigurations(), and it.emarolab.cagg.example.MultiGrammarTesting.USER_COMMANDS.
Member Data Documentation
final Float it.emarolab.cagg.example.MultiGrammarTesting.EVALUATION_TIME_OUT = 5.0f static
Definition at line 47 of file MultiGrammarTesting.java.
Referenced by it.emarolab.cagg.example.MultiGrammarTesting.main().
final List< String> it.emarolab.cagg.example.MultiGrammarTesting.EVALUATOR_LOGGING_NAMES = new ArrayList<>() static
Definition at line 34 of file MultiGrammarTesting.java.
Referenced by it.emarolab.cagg.example.MultiGrammarTesting.getConfigurations().
final List< String> it.emarolab.cagg.example.MultiGrammarTesting.FORMATTER_LOGGING_NAMES = new ArrayList<>() static
Definition at line 40 of file MultiGrammarTesting.java.
Referenced by it.emarolab.cagg.example.MultiGrammarTesting.getConfigurations().
final List< String> it.emarolab.cagg.example.MultiGrammarTesting.GRAMMAR_PATHS = new ArrayList<>() static
Definition at line 22 of file MultiGrammarTesting.java.
Referenced by it.emarolab.cagg.example.MultiGrammarTesting.getConfigurations().
final List< String> it.emarolab.cagg.example.MultiGrammarTesting.TEST_NAMES = new ArrayList<>() static
Definition at line 28 of file MultiGrammarTesting.java.
Referenced by it.emarolab.cagg.example.MultiGrammarTesting.getConfigurations().
final List< String> it.emarolab.cagg.example.MultiGrammarTesting.USER_COMMANDS = new ArrayList<>() static
Definition at line 14 of file MultiGrammarTesting.java.
Referenced by it.emarolab.cagg.example.MultiGrammarTesting.main().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/example/MultiGrammarTesting.java