ConceptActionGrammarGenerator: it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager Class Reference
it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager Class Reference
Public Member Functions
TestPathManager (String basePath, String attribute, boolean useDate, TestFileNames fileNames)
String getTestPath ()
String getLogPath ()
String getQuestionMapPath ()
String getQuestionMapPath (String prefix)
String getResultPath (String idx)
String getResultPath (int idx)
String getPrimitivePath ()
TestFileNames getFileNames ()
String toString ()
Private Member Functions
boolean validateStr (String str)
boolean validatePath (String str)
Private Attributes
String testPath
TestFileNames fileNames
Detailed Description
Definition at line 84 of file CaggGrammarTesterOnFile.java.
Constructor & Destructor Documentation
it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.TestPathManager (String basePath, String attribute, boolean useDate, TestFileNames fileNames)
Definition at line 89 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.ATTRIBUTE_SEPARATOR, it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.DEFAULT_BASE_PATH, it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.EMPTY_DIRECTORY_NAME, it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.fileNames, it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.NO_TEST_SUBFOLDER_ATTRIBUTE, it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.pathDir(), it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.validatePath(), and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.validateStr().
Member Function Documentation
TestFileNames it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.getFileNames ()
Definition at line 149 of file CaggGrammarTesterOnFile.java.
String it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.getLogPath ()
Definition at line 131 of file CaggGrammarTesterOnFile.java.
String it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.getPrimitivePath ()
Definition at line 146 of file CaggGrammarTesterOnFile.java.
String it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.getQuestionMapPath ()
Definition at line 134 of file CaggGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.createTestMap(), and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.updateTestMap().
String it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.getQuestionMapPath (String prefix)
Definition at line 137 of file CaggGrammarTesterOnFile.java.
String it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.getResultPath (String idx)
Definition at line 140 of file CaggGrammarTesterOnFile.java.
String it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.getResultPath (int idx)
Definition at line 143 of file CaggGrammarTesterOnFile.java.
String it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.getTestPath ()
Definition at line 128 of file CaggGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.createTestMap().
String it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.toString ()
Definition at line 153 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.fileNames.
boolean it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.validatePath (String str) private
Definition at line 119 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.debugging.DebuggingDefaults.SYS_PATH_DELIM, and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.validateStr().
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.TestPathManager().
boolean it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.validateStr (String str) private
Definition at line 112 of file CaggGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.TestPathManager(), and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.validatePath().
Member Data Documentation
TestFileNames it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.fileNames private
Definition at line 87 of file CaggGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.TestPathManager(), and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.toString().
String it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.testPath private
Definition at line 86 of file CaggGrammarTesterOnFile.java.
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/interfaces/CaggGrammarTesterOnFile.java