ConceptActionGrammarGenerator: it.emarolab.cagg.debugging.DebuggingText.Log4j Class Reference
it.emarolab.cagg.debugging.DebuggingText.Log4j Class Reference
Public Member Functions
Log4j (String loggerName, String configFilePath)
constructor
void closeLogger ()
synchronized void info (Object msg)
methods for logging
synchronized void info (int backStep, Object msg)
synchronized void info (int backStep, String threadName, Object msg)
synchronized void info (int backStep, String threadName, String attribute, Object msg)
synchronized void warning (Object msg)
synchronized void warning (int backStep, Object msg)
synchronized void warning (int backStep, String threadName, Object msg)
synchronized void warning (int backStep, String threadName, String attribute, Object msg)
synchronized void error (Object msg)
synchronized void error (int backStep, Object msg)
synchronized void error (int backStep, String threadName, Object msg)
synchronized void error (int backStep, String threadName, String attribute, Object msg)
synchronized void error (Exception e)
synchronized void error (int backStep, Exception e)
synchronized void error (int backStep, String threadName, Exception e)
synchronized void error (int backStep, String threadName, String attribute, Exception e)
synchronized void ok (Object msg)
synchronized void ok (int backStep, Object msg)
synchronized void ok (int backStep, String threadName, Object msg)
synchronized void ok (int backStep, String threadName, String attribute, Object msg)
Public Member Functions inherited from it.emarolab.cagg.debugging.DebuggingText.LoggerBase
abstract void info (Object msg)
abstract void info (int backStep, Object msg)
abstract void info (int loggingStepBack, String threadName, Object msg)
abstract void info (int loggingStepBack, String threadName, String attribute, Object msg)
abstract void warning (Object msg)
abstract void warning (int backStep, Object msg)
abstract void warning (int backStep, String threadName, Object msg)
abstract void warning (int backStep, String threadName, String attribute, Object msg)
abstract void error (Object msg)
abstract void error (int backStep, Object msg)
abstract void error (int backStep, String threadName, Object msg)
abstract void error (int backStep, String threadName, String attribute, Object msg)
abstract void error (Exception e)
abstract void error (int backStep, Exception e)
abstract void error (int backStep, String threadName, Exception e)
abstract void error (int backStep, String threadName, String attribute, Exception e)
abstract void ok (Object msg)
abstract void ok (int backStep, Object msg)
abstract void ok (int backStep, String threadName, Object msg)
abstract void ok (int backStep, String threadName, String attribute, Object masg)
Static Public Attributes
static final String SYST_PROPERTY_CALLER_CLASS = "caggLoggerCallerClass"
set the system property to be used in the log4j configuration file
static final String SYST_PROPERTY_CALLER_METHOD = "caggLoggerCallerMethod"
static final String SYST_PROPERTY_CALLER_LINE = "caggLoggerCallerLine"
static final String SYST_PROPERTY_CALLER = "caggLoggerCaller"
static final String SYST_PROPERTY_ATTRIBUTE = "caggLoggerAttribute"
static final String SYST_PROPERTY_CALLER_CUT_SYMBOL = "-"
static final int SYST_PROPERTY_CALLER_CHAR_CNT = 35
static final int SYST_PROPERTY_NAME_THREAD_CHAR_CNT = 15
static final int SYST_PROPERTY_CALLER_LINE_CHAR_CNT = 4
static final int SYST_PROPERTY_ATTRIBUTE_CHAR_CNT = 5
static final int DEFAULT_CALLER_BACK_STEP_ON_START_TRACE = 4
Private Member Functions
synchronized void applyPropertyCallerMethod (int backStep)
synchronized void applayPropertyThreadLoggerName (String threadName)
synchronized void applayPropertyAttribute (String attribute)
synchronized void resetProperties ()
synchronized String pad (String str, boolean left, int size)
Private Attributes
org.apache.log4j.Logger logger4j
fields
Detailed Description
Definition at line 233 of file DebuggingText.java.
Constructor & Destructor Documentation
it.emarolab.cagg.debugging.DebuggingText.Log4j.Log4j (String loggerName, String configFilePath)
constructor
Definition at line 249 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.Log4j.info(), and it.emarolab.cagg.debugging.DebuggingText.loggerName.
Member Function Documentation
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.applayPropertyAttribute (String attribute) private
Definition at line 419 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.Log4j.pad(), it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_ATTRIBUTE, and it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_ATTRIBUTE_CHAR_CNT.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.error(), it.emarolab.cagg.debugging.DebuggingText.Log4j.info(), it.emarolab.cagg.debugging.DebuggingText.Log4j.ok(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.warning().
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.applayPropertyThreadLoggerName (String threadName) private
Definition at line 406 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.Log4j.pad(), it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_NAME_THREAD_CHAR_CNT, and it.emarolab.cagg.core.evaluation.CaggThread.SYST_PROPERTY_RUNNABLE_NAME.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.error(), it.emarolab.cagg.debugging.DebuggingText.Log4j.info(), it.emarolab.cagg.debugging.DebuggingText.Log4j.ok(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.warning().
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.applyPropertyCallerMethod (int backStep) private
Definition at line 390 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.Log4j.pad(), it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER, it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER_CHAR_CNT, it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER_CLASS, it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER_LINE, it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER_LINE_CHAR_CNT, and it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER_METHOD.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.error(), it.emarolab.cagg.debugging.DebuggingText.Log4j.info(), it.emarolab.cagg.debugging.DebuggingText.Log4j.ok(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.warning().
void it.emarolab.cagg.debugging.DebuggingText.Log4j.closeLogger ()
Definition at line 257 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.Log4j.info().
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.error (Object msg)
Definition at line 315 of file DebuggingText.java.
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.error (int backStep, Object msg)
Definition at line 319 of file DebuggingText.java.
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.error (int backStep, String threadName, Object msg)
Definition at line 323 of file DebuggingText.java.
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.error (int backStep, String threadName, String attribute, Object msg)
Definition at line 327 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.Log4j.applayPropertyAttribute(), it.emarolab.cagg.debugging.DebuggingText.Log4j.applayPropertyThreadLoggerName(), it.emarolab.cagg.debugging.DebuggingText.Log4j.applyPropertyCallerMethod(), it.emarolab.cagg.debugging.DebuggingText.Log4j.DEFAULT_CALLER_BACK_STEP_ON_START_TRACE, it.emarolab.cagg.debugging.DebuggingText.Log4j.logger4j, it.emarolab.cagg.debugging.DebuggingText.reconfigureLogger(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.resetProperties().
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.error (Exception e)
Definition at line 340 of file DebuggingText.java.
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.error (int backStep, Exception e)
Definition at line 344 of file DebuggingText.java.
References it.emarolab.cagg.core.evaluation.CaggThread.DEFAULT_NAME_THREAD.
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.error (int backStep, String threadName, Exception e)
Definition at line 348 of file DebuggingText.java.
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.error (int backStep, String threadName, String attribute, Exception e)
Definition at line 352 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.Log4j.applayPropertyAttribute(), it.emarolab.cagg.debugging.DebuggingText.Log4j.applayPropertyThreadLoggerName(), it.emarolab.cagg.debugging.DebuggingText.Log4j.applyPropertyCallerMethod(), it.emarolab.cagg.debugging.DebuggingText.Log4j.DEFAULT_CALLER_BACK_STEP_ON_START_TRACE, it.emarolab.cagg.debugging.DebuggingText.Log4j.logger4j, it.emarolab.cagg.debugging.DebuggingText.reconfigureLogger(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.resetProperties().
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.info (Object msg)
methods for logging
Definition at line 265 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.closeLogger(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.Log4j().
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.info (int backStep, Object msg)
Definition at line 269 of file DebuggingText.java.
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.info (int backStep, String threadName, Object msg)
Definition at line 273 of file DebuggingText.java.
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.info (int backStep, String threadName, String attribute, Object msg)
Definition at line 277 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.Log4j.applayPropertyAttribute(), it.emarolab.cagg.debugging.DebuggingText.Log4j.applayPropertyThreadLoggerName(), it.emarolab.cagg.debugging.DebuggingText.Log4j.applyPropertyCallerMethod(), it.emarolab.cagg.debugging.DebuggingText.Log4j.DEFAULT_CALLER_BACK_STEP_ON_START_TRACE, it.emarolab.cagg.debugging.DebuggingText.Log4j.logger4j, it.emarolab.cagg.debugging.DebuggingText.reconfigureLogger(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.resetProperties().
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.ok (Object msg)
Definition at line 365 of file DebuggingText.java.
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.ok (int backStep, Object msg)
Definition at line 369 of file DebuggingText.java.
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.ok (int backStep, String threadName, Object msg)
Definition at line 373 of file DebuggingText.java.
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.ok (int backStep, String threadName, String attribute, Object msg)
Definition at line 377 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.Log4j.applayPropertyAttribute(), it.emarolab.cagg.debugging.DebuggingText.Log4j.applayPropertyThreadLoggerName(), it.emarolab.cagg.debugging.DebuggingText.Log4j.applyPropertyCallerMethod(), it.emarolab.cagg.debugging.DebuggingText.Log4j.DEFAULT_CALLER_BACK_STEP_ON_START_TRACE, it.emarolab.cagg.debugging.DebuggingText.Log4j.logger4j, it.emarolab.cagg.debugging.DebuggingText.reconfigureLogger(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.resetProperties().
synchronized String it.emarolab.cagg.debugging.DebuggingText.Log4j.pad (String str, boolean left, int size) private
Definition at line 451 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER_CUT_SYMBOL.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.applayPropertyAttribute(), it.emarolab.cagg.debugging.DebuggingText.Log4j.applayPropertyThreadLoggerName(), it.emarolab.cagg.debugging.DebuggingText.Log4j.applyPropertyCallerMethod(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.resetProperties().
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.resetProperties () private
Definition at line 432 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.Log4j.pad(), it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_ATTRIBUTE, it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_ATTRIBUTE_CHAR_CNT, it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER, it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER_CHAR_CNT, it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER_CLASS, it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER_LINE, it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER_LINE_CHAR_CNT, it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER_METHOD, it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_NAME_THREAD_CHAR_CNT, and it.emarolab.cagg.core.evaluation.CaggThread.SYST_PROPERTY_RUNNABLE_NAME.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.error(), it.emarolab.cagg.debugging.DebuggingText.Log4j.info(), it.emarolab.cagg.debugging.DebuggingText.Log4j.ok(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.warning().
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.warning (Object msg)
Definition at line 290 of file DebuggingText.java.
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.warning (int backStep, Object msg)
Definition at line 294 of file DebuggingText.java.
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.warning (int backStep, String threadName, Object msg)
Definition at line 298 of file DebuggingText.java.
synchronized void it.emarolab.cagg.debugging.DebuggingText.Log4j.warning (int backStep, String threadName, String attribute, Object msg)
Definition at line 302 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.Log4j.applayPropertyAttribute(), it.emarolab.cagg.debugging.DebuggingText.Log4j.applayPropertyThreadLoggerName(), it.emarolab.cagg.debugging.DebuggingText.Log4j.applyPropertyCallerMethod(), it.emarolab.cagg.debugging.DebuggingText.Log4j.DEFAULT_CALLER_BACK_STEP_ON_START_TRACE, it.emarolab.cagg.debugging.DebuggingText.Log4j.logger4j, it.emarolab.cagg.debugging.DebuggingText.reconfigureLogger(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.resetProperties().
Member Data Documentation
final int it.emarolab.cagg.debugging.DebuggingText.Log4j.DEFAULT_CALLER_BACK_STEP_ON_START_TRACE = 4 static
Definition at line 245 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.error(), it.emarolab.cagg.debugging.DebuggingText.Log4j.info(), it.emarolab.cagg.debugging.DebuggingText.Log4j.ok(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.warning().
org.apache.log4j.Logger it.emarolab.cagg.debugging.DebuggingText.Log4j.logger4j private
fields
Definition at line 247 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.error(), it.emarolab.cagg.debugging.DebuggingText.Log4j.info(), it.emarolab.cagg.debugging.DebuggingText.Log4j.ok(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.warning().
final String it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_ATTRIBUTE = "caggLoggerAttribute" static
Definition at line 239 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.applayPropertyAttribute(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.resetProperties().
final int it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_ATTRIBUTE_CHAR_CNT = 5 static
Definition at line 244 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.applayPropertyAttribute(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.resetProperties().
final String it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER = "caggLoggerCaller" static
Definition at line 238 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.applyPropertyCallerMethod(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.resetProperties().
final int it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER_CHAR_CNT = 35 static
Definition at line 241 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.applyPropertyCallerMethod(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.resetProperties().
final String it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER_CLASS = "caggLoggerCallerClass" static
set the system property to be used in the log4j configuration file
Definition at line 235 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.applyPropertyCallerMethod(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.resetProperties().
final String it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER_CUT_SYMBOL = "-" static
Definition at line 240 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.pad().
final String it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER_LINE = "caggLoggerCallerLine" static
Definition at line 237 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.applyPropertyCallerMethod(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.resetProperties().
final int it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER_LINE_CHAR_CNT = 4 static
Definition at line 243 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.applyPropertyCallerMethod(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.resetProperties().
final String it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_CALLER_METHOD = "caggLoggerCallerMethod" static
Definition at line 236 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.applyPropertyCallerMethod(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.resetProperties().
final int it.emarolab.cagg.debugging.DebuggingText.Log4j.SYST_PROPERTY_NAME_THREAD_CHAR_CNT = 15 static
Definition at line 242 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.applayPropertyThreadLoggerName(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.resetProperties().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/debugging/DebuggingText.java