ConceptActionGrammarGenerator: it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile Class Reference
it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile Class Reference
Classes
class TestPathManager
Public Member Functions
CaggGrammarTesterOnFile (String grammarPath)
CaggGrammarTesterOnFile (String grammarPath, Float timeOutSec)
CaggGrammarTesterOnFile (GrammarBase<?extends SemanticExpressionTreeBase > grammar)
CaggGrammarTesterOnFile (GrammarBase<?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
CaggGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, String grammarPath)
CaggGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, String grammarPath, Float timeOutSec)
CaggGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar)
CaggGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
synchronized void willEvaluateCommand (String command, int testIdx)
synchronized void didEvaluateCommand (String command, int testIdx)
EvaluatorTesterOnFile getEvaluator ()
TestPathManager getPathManager ()
void setFile ()
void setFile (String attribute)
void setFile (String basePath, String attribute)
void setFile (String attribute, boolean useDate)
void setFile (boolean useDate, String basePath)
void setFile (String basePath, String attribute, boolean useDate)
void setFile (String basePath, String attribute, boolean useDate, String logsFileName, String testMapFileName, String resultBaseFileName)
void setPathManager (TestPathManager pathManager)
Public Member Functions inherited from it.emarolab.cagg.interfaces.CaggGrammarTester
CaggGrammarTester (GrammarBase<?extends SemanticExpressionTreeBase > grammar)
CaggGrammarTester (GrammarBase<?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
CaggGrammarTester (String grammarPath)
CaggGrammarTester (String grammarPath, Float timeOutSec)
CaggGrammarTester (String evaluatorLoggerName, String formatterLoggerName, String grammarPath)
CaggGrammarTester (String evaluatorLoggerName, String formatterLoggerName, String grammarPath, Float timeOutSec)
CaggGrammarTester (String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar)
CaggGrammarTester (String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
synchronized void willEvaluateCommand (String command, int testIdx)
synchronized void didEvaluateCommand (String command, int testIdx)
Public Member Functions inherited from it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase
GrammarTesterBase (String grammarPath)
GrammarTesterBase (String grammarPath, Float timeOutSec)
GrammarTesterBase (GrammarBase< ?extends SemanticExpressionTreeBase > grammar)
GrammarTesterBase (GrammarBase< ?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
GrammarTesterBase (String evaluatorLoggerName, String formatterLoggerName, String grammarPath)
GrammarTesterBase (String evaluatorLoggerName, String formatterLoggerName, String grammarPath, Float timeOutSec)
GrammarTesterBase (String evaluatorLoggerName, String formatterLoggerName, GrammarBase< ?extends SemanticExpressionTreeBase > grammar)
GrammarTesterBase (String evaluatorLoggerName, String formatterLoggerName, GrammarBase< ?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
GrammarBase< ?extends
SemanticExpressionTreeBase > getGrammar ()
TimeOutedEvaluatorBase getEvaluator ()
ThreadedInputFormatter getFormatter ()
boolean isTestingLastCommand ()
void resetLastCommand ()
Float getTestingTime ()
void setTestingTime ()
synchronized Float getRangeFromTestingStart ()
synchronized String getEvaluatorLoggerName ()
String getFormatterLoggerName ()
synchronized void test (List< String > commands)
synchronized void test (String command)
synchronized void test (String command, int testIdx)
abstract void willEvaluateCommand (String command, int testIdx)
abstract void didEvaluateCommand (String command, int testIdx)
Static Public Member Functions
static String pathDir (String directive)
Static Public Attributes
static final String DEFAULT_BASE_PATH = pathDir(DebuggingDefaults.SYS_PATH_WORKING) + pathDir("file") + pathDir("tests")
static final String DEFAULT_ATTRIBUTE = null
static final Boolean DEFAULT_USE_DATE = true
static final String ATTRIBUTE_SEPARATOR = "_"
static final String EMPTY_DIRECTORY_NAME = "xxx" + ATTRIBUTE_SEPARATOR
static final String NO_TEST_SUBFOLDER_ATTRIBUTE = ".."
Protected Member Functions
ThreadedInputFormatter getNewFormatter (String prefixLog, GrammarBase< ?extends SemanticExpressionTreeBase > grammar)
TimeOutedEvaluatorBase getNewEvaluator (String prefixLog, ThreadedInputFormatter formatter, Float timeOutSec)
void createTestMap (int testIdx)
void createSystemLog (String logPath)
void storeResults (CaggXmlManager xmlManager, int testIdx, String command)
void storeResult (String filePath, CaggXmlManager xmlManager)
synchronized void updateTestMap (String filePath, String command, int testIdx)
void addTestMapFooter (String logPath)
Protected Member Functions inherited from it.emarolab.cagg.interfaces.CaggGrammarTester
ThreadedInputFormatter getNewFormatter (String prefixLog, GrammarBase< ?extends SemanticExpressionTreeBase > grammar)
TimeOutedEvaluatorBase getNewEvaluator (String prefixLog, ThreadedInputFormatter formatter, Float timeOutSec)
Protected Member Functions inherited from it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase
abstract ThreadedInputFormatter getNewFormatter (String loggerName, GrammarBase< ?extends SemanticExpressionTreeBase > grammar)
abstract TimeOutedEvaluatorBase getNewEvaluator (String loggerName, ThreadedInputFormatter formatter, Float timeOutSec)
TimeOutedEvaluatorBase getNewEvaluator (TimeOutedEvaluatorBase eval)
void performTest (String command, int testIdx)
Private Member Functions
Float getTimeRange (Long stampNanoSec)
void setFile (String basePath, String attribute, boolean useDate, TestFileNames fileNames)
Private Attributes
Long initialTime
CaggXMLTestDescriptor xmlDescriptor
TestPathManager pathManager = null
Float lastTime = 0.0f
Detailed Description
Definition at line 65 of file CaggGrammarTesterOnFile.java.
Constructor & Destructor Documentation
it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.CaggGrammarTesterOnFile (String grammarPath)
Definition at line 169 of file CaggGrammarTesterOnFile.java.
it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.CaggGrammarTesterOnFile (String grammarPath, Float timeOutSec)
Definition at line 172 of file CaggGrammarTesterOnFile.java.
it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.CaggGrammarTesterOnFile (GrammarBase<?extends SemanticExpressionTreeBase > grammar)
Definition at line 175 of file CaggGrammarTesterOnFile.java.
it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.CaggGrammarTesterOnFile (GrammarBase<?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
Definition at line 178 of file CaggGrammarTesterOnFile.java.
it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.CaggGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, String grammarPath)
Definition at line 181 of file CaggGrammarTesterOnFile.java.
it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.CaggGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, String grammarPath, Float timeOutSec)
Definition at line 185 of file CaggGrammarTesterOnFile.java.
it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.CaggGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar)
Definition at line 189 of file CaggGrammarTesterOnFile.java.
it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.CaggGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
Definition at line 193 of file CaggGrammarTesterOnFile.java.
Member Function Documentation
void it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.addTestMapFooter (String logPath) protected
Definition at line 295 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getRangeFromTestingStart(), and it.emarolab.cagg.debugging.DebuggingDefaults.SYS_LINE_SEPARATOR.
Referenced by it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.updateTestMap(), and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.updateTestMap().
void it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.createSystemLog (String logPath) protected
Definition at line 242 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.debugging.DebuggingDefaults.SYS_LINE_SEPARATOR.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.createTestMap().
void it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.createTestMap (int testIdx) protected
Definition at line 230 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.createSystemLog(), it.emarolab.cagg.interfaces.TestLog.error(), it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.getQuestionMapPath(), it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.getTestPath(), it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.pathManager, and it.emarolab.cagg.debugging.DebuggingDefaults.SYS_PATH_DELIM.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.willEvaluateCommand().
synchronized void it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.didEvaluateCommand (String command, int testIdx)
Definition at line 247 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.getEvaluator(), it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getFormatter(), it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getGrammar(), it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.getTimeRange(), it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.initialTime, it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.pathManager, it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.storeResults(), and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.xmlDescriptor.
EvaluatorTesterOnFile it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.getEvaluator ()
Definition at line 307 of file CaggGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.didEvaluateCommand(), and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.willEvaluateCommand().
TimeOutedEvaluatorBase it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.getNewEvaluator (String prefixLog, ThreadedInputFormatter formatter, Float timeOutSec) protected
Definition at line 204 of file CaggGrammarTesterOnFile.java.
ThreadedInputFormatter it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.getNewFormatter (String prefixLog, GrammarBase< ?extends SemanticExpressionTreeBase > grammar) protected
Definition at line 200 of file CaggGrammarTesterOnFile.java.
TestPathManager it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.getPathManager ()
Definition at line 311 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.pathManager.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.storeResults(), and it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.updateTestMap().
Float it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.getTimeRange (Long stampNanoSec) private
Definition at line 314 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.debugging.DebuggingDefaults.NANOSEC_2_SEC.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.didEvaluateCommand().
static String it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.pathDir (String directive) static
Definition at line 81 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.debugging.DebuggingDefaults.SYS_PATH_DELIM.
Referenced by it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.setMultiFile(), and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.TestPathManager().
void it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setFile ()
Definition at line 321 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.DEFAULT_ATTRIBUTE, it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.DEFAULT_BASE_PATH, and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.DEFAULT_USE_DATE.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setFile().
void it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setFile (String attribute)
Definition at line 324 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.DEFAULT_BASE_PATH, it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.DEFAULT_USE_DATE, and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setFile().
void it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setFile (String basePath, String attribute)
Definition at line 327 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.DEFAULT_USE_DATE, and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setFile().
void it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setFile (String attribute, boolean useDate)
Definition at line 330 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.DEFAULT_BASE_PATH, and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setFile().
void it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setFile (boolean useDate, String basePath)
Definition at line 333 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.DEFAULT_ATTRIBUTE, and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setFile().
void it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setFile (String basePath, String attribute, boolean useDate)
Definition at line 336 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setFile().
void it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setFile (String basePath, String attribute, boolean useDate, String logsFileName, String testMapFileName, String resultBaseFileName)
Definition at line 339 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setFile().
void it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setFile (String basePath, String attribute, boolean useDate, TestFileNames fileNames) private
Definition at line 344 of file CaggGrammarTesterOnFile.java.
void it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setPathManager (TestPathManager pathManager)
Definition at line 348 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.pathManager.
void it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.storeResult (String filePath, CaggXmlManager xmlManager) protected
Definition at line 283 of file CaggGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.storeResults().
void it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.storeResults (CaggXmlManager xmlManager, int testIdx, String command) protected
Definition at line 277 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.getPathManager(), it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.storeResult(), and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.updateTestMap().
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.didEvaluateCommand().
synchronized void it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.updateTestMap (String filePath, String command, int testIdx) protected
Definition at line 286 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.addTestMapFooter(), it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.getQuestionMapPath(), it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getRangeFromTestingStart(), it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.isTestingLastCommand(), it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.lastTime, and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.pathManager.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.storeResults().
synchronized void it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.willEvaluateCommand (String command, int testIdx)
Definition at line 212 of file CaggGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.createTestMap(), it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.getEvaluator(), it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getGrammar(), it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.initialTime, it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.pathManager, and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.xmlDescriptor.
Member Data Documentation
final String it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.ATTRIBUTE_SEPARATOR = "_" static
Definition at line 78 of file CaggGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.setMultiFile(), and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.TestPathManager().
final String it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.DEFAULT_ATTRIBUTE = null static
Definition at line 72 of file CaggGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setFile().
final String it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.DEFAULT_BASE_PATH = pathDir(DebuggingDefaults.SYS_PATH_WORKING) + pathDir("file") + pathDir("tests") static
Definition at line 71 of file CaggGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setFile(), it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.setMultiFile(), and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.TestPathManager().
final Boolean it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.DEFAULT_USE_DATE = true static
Definition at line 73 of file CaggGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setFile().
final String it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.EMPTY_DIRECTORY_NAME = "xxx" + ATTRIBUTE_SEPARATOR static
Definition at line 79 of file CaggGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.TestPathManager().
Long it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.initialTime private
Definition at line 161 of file CaggGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.didEvaluateCommand(), and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.willEvaluateCommand().
Float it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.lastTime = 0.0f private
Definition at line 276 of file CaggGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.updateTestMap().
final String it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.NO_TEST_SUBFOLDER_ATTRIBUTE = ".." static
Definition at line 80 of file CaggGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.setMultiFile(), and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.TestPathManager.TestPathManager().
TestPathManager it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.pathManager = null private
Definition at line 164 of file CaggGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.createTestMap(), it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.didEvaluateCommand(), it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.getPathManager(), it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.setPathManager(), it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.updateTestMap(), and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.willEvaluateCommand().
CaggXMLTestDescriptor it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.xmlDescriptor private
Definition at line 162 of file CaggGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.didEvaluateCommand(), and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.willEvaluateCommand().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/interfaces/CaggGrammarTesterOnFile.java