ConceptActionGrammarGenerator: it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer Class Reference
it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer Class Reference
Public Member Functions
DataFactoryVisualizer ()
JSeparator addSeparator (JPanel toAddPanel)
JLabel addLabel (String txt, JPanel toAddPanel)
JTree addTree (ExpressionNode<?> root, JPanel toAddPanel)
JTextArea addTextArea (String contents, JPanel toAddPanel)
JTable addMap (Map<?,?> map, JPanel toAddPanel)
void showContents (AbstractNodeData<?> parent, JPanel contentPanel)
void showContents (AbstractNodeDoubleData<?,?> parent, JPanel contentPanel)
void showInfo (AbstractNodeDoubleData<?,?> parent, JPanel contentPanel)
void showInfo (AbstractNodeData<?> parent, JPanel contentPanel)
Private Member Functions
void addWithAuxiliaryPanel (Component comp, JPanel toAddPanel)
Detailed Description
Version
Concept-Action Grammar Generator 1.1
File: src//cagg.core.sourceInterface.grammar.abstractSyntaxTree.AbstractDataFactory.java
Author
Buoncompagni Luca
DIBRIS, emaroLab,
University of Genoa.
15/gen/2016
This class is used to easy visualise node data on GUI.
Particularly, it is used in: it.emarolab.cagg.core.language.syntax.abstractTree.AbstractNodeData, it.emarolab.cagg.core.language.syntax.abstractTree.AbstractNodeDoubleData and their extending classes.
Finally, to get a new instance of this object you should use: AbstractDataFactory#getNewVisualizer()
See Also
AbstractDataFactory
AbstractDataFactory.ASNodeStrData
AbstractDataFactory.ASNodeStrStrData
AbstractDataFactory.ASNodeStrTreeData
it.emarolab.cagg.core.language.syntax.abstractTree.AbstractNodeData
it.emarolab.cagg.core.language.syntax.abstractTree.AbstractNodeDoubleData
Definition at line 549 of file AbstractDataFactory.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.DataFactoryVisualizer ()
Empty constructor, it create this object but it does not do nothing more.
Definition at line 553 of file AbstractDataFactory.java.
Member Function Documentation
JLabel it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.addLabel (String txt, JPanel toAddPanel)
Add a label with a text (given as input parameter) to the panel (given as input parameter as well) and return it.
Parameters
toAddPanel the panel where components should be added.
txt the text to be shown in the label.
Returns
the label with the related text added to the given panel.
Definition at line 574 of file AbstractDataFactory.java.
References it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.addWithAuxiliaryPanel().
JTable it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.addMap (Map<?,?> map, JPanel toAddPanel)
Add a map (given as input parameter) as a table to the panel (given as input parameter as well) and return it.
Parameters
map the map to be shown as a table.
toAddPanel the panel where the table should be added.
Returns
the table added to the given panel.
Definition at line 620 of file AbstractDataFactory.java.
References it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.addWithAuxiliaryPanel().
JSeparator it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.addSeparator (JPanel toAddPanel)
Add a separator to the panel (given as input parameter) and return it.
Parameters
toAddPanel the panel where components should be added.
Returns
the component added to the given panel
Definition at line 561 of file AbstractDataFactory.java.
JTextArea it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.addTextArea (String contents, JPanel toAddPanel)
Add a not editable TextArea, with a text (given as input parameter), to the panel (given as input parameter as well) and return it.
Parameters
contents the string to be shown in the text area.
toAddPanel the panel where components should be added.
Returns
the text area initialised and added to the panel.
Definition at line 602 of file AbstractDataFactory.java.
References it.emarolab.cagg.debugging.DebuggingDefaults.COLOR_TEST_FIELD.
JTree it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.addTree (ExpressionNode<?> root, JPanel toAddPanel)
Add a tree (given as input parameter) to the panel (given as input parameter as well) and return it.
Parameters
root the root node of the tree to be visualised.
toAddPanel the panel where components should be added.
Returns
the tree added to the panel.
Definition at line 588 of file AbstractDataFactory.java.
References it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.addWithAuxiliaryPanel().
void it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.addWithAuxiliaryPanel (Component comp, JPanel toAddPanel) private
Definition at line 695 of file AbstractDataFactory.java.
Referenced by it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.addLabel(), it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.addMap(), and it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.addTree().
void it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.showContents (AbstractNodeData<?> parent, JPanel contentPanel)
This method is called from the GUI in order to visualise the
parent
data object. It calls it.emarolab.cagg.core.language.syntax.abstractTree.AbstractNodeData#addDataToGui(JPanel) in order to add: the data visualisations into the given panel (it.emarolab.cagg.core.language.syntax.abstractTree.AbstractNodeData#getInstance()) and the data information (it.emarolab.cagg.core.language.syntax.abstractTree.AbstractNodeData#getInfo()).
Than, it automatically shows the
genericInfo
of the
parent
by calling: showContents(AbstractNodeData, JPanel)
Parameters
parent the node data objects that from which retrieve the instances and this object.
contentPanel the panel where components should be added.
Definition at line 641 of file AbstractDataFactory.java.
References it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.showInfo().
void it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.showContents (AbstractNodeDoubleData<?,?> parent, JPanel contentPanel)
This method is called from the GUI in order to visualise the
parent
data object. It calls it.emarolab.cagg.core.language.syntax.abstractTree.AbstractNodeDoubleData#addDataToGui(JPanel) in order to add: the data visualisations into the given panel (it.emarolab.cagg.core.language.syntax.abstractTree.AbstractNodeDoubleData#getInstance() and it.emarolab.cagg.core.language.syntax.abstractTree.AbstractNodeDoubleData#getInstance2()) and the data information (it.emarolab.cagg.core.language.syntax.abstractTree.AbstractNodeDoubleData#getInfo1() and it.emarolab.cagg.core.language.syntax.abstractTree.AbstractNodeDoubleData#getInfo2()).
Than, it automatically shows the
genericInfo
of the
parent
by calling: showContents(AbstractNodeDoubleData, JPanel)
Parameters
parent the node data objects that from which retrieve the instances and this object.
contentPanel the panel where components should be added.
Definition at line 660 of file AbstractDataFactory.java.
References it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.showInfo().
void it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.showInfo (AbstractNodeDoubleData<?,?> parent, JPanel contentPanel)
Add javax.swing.JSeparator and call addTextArea(String, JPanel) to display the
genericInfo
by calling: it.emarolab.cagg.core.language.syntax.abstractTree.AbstractNodeDoubleData#getGenericInfo(). The purpose of this method is to have a common way to shown
genericInfo
for all the it.emarolab.cagg.core.language.syntax.abstractTree.AbstractNodeDoubleData.
Parameters
parent the node data objects that contains this
genericInfo
.
contentPanel the panel where components should be added.
Definition at line 674 of file AbstractDataFactory.java.
Referenced by it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.showContents().
void it.emarolab.cagg.core.language.syntax.abstractTree.AbstractDataFactory.DataFactoryVisualizer.showInfo (AbstractNodeData<?> parent, JPanel contentPanel)
Add javax.swing.JSeparator and call addTextArea(String, JPanel) to display the
genericInfo
by calling: it.emarolab.cagg.core.language.syntax.abstractTree.AbstractNodeData#getGenericInfo(). The purpose of this method is to have a common way to shown
genericInfo
for all the it.emarolab.cagg.core.language.syntax.abstractTree.AbstractNodeData.
Parameters
parent the node data objects that contains this
genericInfo
.
contentPanel the panel where components should be added.
Definition at line 689 of file AbstractDataFactory.java.
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/language/syntax/abstractTree/AbstractDataFactory.java