ConceptActionGrammarGenerator: it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger Class Reference
it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger Class Reference
Public Member Functions
Logger (ConsoleLogRidirector consoleRiderector)
Static Public Member Functions
static synchronized void info (String prefix, Object obj)
static synchronized void info (Object obj)
static synchronized void info (String prefix, String msg)
static synchronized void info (String msg)
static synchronized void warning (String prefix, String msg)
static synchronized void warning (String msg)
static synchronized void warning (String prefix, Object obj)
static synchronized void warning (Object obj)
static synchronized void ok (String prefix, String msg)
static synchronized void ok (String msg)
static synchronized void ok (String prefix, Object obj)
static synchronized void ok (Object obj)
static synchronized void error (String prefix, String msg)
static synchronized void error (String msg)
static synchronized void error (String prefix, Object obj)
static synchronized void error (Object obj)
static synchronized void error (String prefix, Exception e)
static synchronized void error (Exception e)
static synchronized void printStackTrace ()
static String flushOut ()
static String flushErr ()
static String flushOutErr ()
static String getFormattedDate ()
static String getFormattedDateMilli ()
static String getFormattedDate (String format)
static void appendOnFileLn (String filePath, String txt)
static void appendOnFile (String filePath, String txt)
static String getFilePath ()
static void setFilePath (String filePath)
Protected Member Functions
void finalize () throws Throwable
Static Private Member Functions
static String getPrefix (String prefix)
static String getTime4Log ()
static void addToGui (String log)
Static Private Attributes
static ConsoleLogRidirector console
Detailed Description
Version
Concept-Action Grammar Generator 1.1
File: src//cagg.debugging.DebuggingText.java
Author
Buoncompagni Luca
DIBRIS, emaroLab,
University of Genoa.
15/gen/2016
This class is used along all the system to have a basing logging object. Particularly, it recieve message from the standard streams:
System.out
and
System.err
basing on the redirector object given on constructor (which is resposible to log those messages also on the Java console or not).
Moreover, it can be used also to directly log data for debugging and showing purposes both in the console or in the GUI.
It is important to note that if some exceptions occur in to the system this class may not print the results as long as its buffer is processed. To obviate to this problem and see the longs in the GUI interact in order to process other logs (e.g. open a new grammar dialog and cancel it). While, from API it is possible to call: Logger#flushOut(), Logger#flushErr() or Logger#flushOutErr()
See Also
it.emarolab.cagg.debugging.baseComponents.customPanel.LogDebuggingGuiPanel
ConsoleLogRidirector
StandaloneDebuggingText
Definition at line 435 of file StandaloneDebuggingText.java.
Constructor & Destructor Documentation
it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.Logger (ConsoleLogRidirector consoleRiderector)
Initialise the static Logger for the system.
Parameters
consoleRiderector is the object used to obtain standard output messages
Definition at line 444 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.console.
Member Function Documentation
static void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.addToGui (String log) static private
Definition at line 687 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.PRINT_ON_GUI.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.flushErr(), and it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.flushOut().
static void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.appendOnFile (String filePath, String txt) static
Definition at line 697 of file StandaloneDebuggingText.java.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.appendOnFileLn().
static void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.appendOnFileLn (String filePath, String txt) static
Definition at line 694 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.appendOnFile(), and it.emarolab.cagg.debugging.DebuggingDefaults.SYS_LINE_SEPARATOR.
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.error (String prefix, String msg) static
Print a message with the ERROR tag (StandaloneDebuggingText#TAG_ERROR) and clear possible redirector message queue by calling flushOutErr() method.
The logs are shown in the
System.err
stream if the flag StandaloneDebuggingText#SHOW_ERROR is
true
.
Parameters
msg the message to be printed
Definition at line 554 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.flushErr(), it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.getPrefix(), it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.getTime4Log(), it.emarolab.cagg.debugging.StandaloneDebuggingText.SHOW_ERROR, and it.emarolab.cagg.debugging.StandaloneDebuggingText.TAG_ERROR.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.error().
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.error (String msg) static
Definition at line 567 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.error().
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.error (String prefix, Object obj) static
calls error(String) by using the method Object#toString() of the input parameter
Parameters
obj the object to print by calling the method
toString()
Definition at line 575 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.info().
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.error (Object obj) static
Definition at line 580 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.error().
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.error (String prefix, Exception e) static
Print an exception (
e.printStackTrace()
) with the ERROR tag (StandaloneDebuggingText#TAG_ERROR) and clear possible redirector message queue by calling flushOutErr() method.
The logs are shown in the
System.err
stream if the flag StandaloneDebuggingText#SHOW_ERROR is
true
.
Parameters
e the reference to the exception object from which get error informations.
Definition at line 589 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.flushErr(), it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.getPrefix(), it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.getTime4Log(), it.emarolab.cagg.debugging.StandaloneDebuggingText.SHOW_ERROR, and it.emarolab.cagg.debugging.StandaloneDebuggingText.TAG_ERROR.
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.error (Exception e) static
Definition at line 598 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.error().
void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.finalize () throws Throwable protected
Definition at line 731 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.flushOutErr().
static String it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.flushErr () static
If StandaloneDebuggingText#ATTACH_ERR_LOGS is
true
, it calls StandaloneDebuggingText.ConsoleLogRidirector#printErrLog() in order to eventually print all the message in the console. Moreover, it adds the messages to the GUI if StandaloneDebuggingText#PRINT_ON_GUI is
true
See Also
it.emarolab.cagg.debugging.baseComponents.customPanel.LogDebuggingGuiPanel
Returns
returns the shown messages as a string or an empty string if StandaloneDebuggingText#ATTACH_ERR_LOGS is
false
Definition at line 640 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.addToGui(), it.emarolab.cagg.debugging.StandaloneDebuggingText.ATTACH_ERR_LOGS, and it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.console.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.error(), it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.flushOutErr(), and it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.ok().
static String it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.flushOut () static
If StandaloneDebuggingText#ATTACH_OUT_LOGS is
true
, it calls StandaloneDebuggingText.ConsoleLogRidirector#printOutLog() in order to eventually print all the message in the console. Moreover, it adds the messages to the GUI if StandaloneDebuggingText#PRINT_ON_GUI is
true
See Also
it.emarolab.cagg.debugging.baseComponents.customPanel.LogDebuggingGuiPanel
Returns
returns the shown messages as a string or an empty string if StandaloneDebuggingText#ATTACH_OUT_LOGS is
false
Definition at line 621 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.addToGui(), it.emarolab.cagg.debugging.StandaloneDebuggingText.ATTACH_OUT_LOGS, and it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.console.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.flushOutErr(), it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.info(), and it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.warning().
static String it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.flushOutErr () static
If StandaloneDebuggingText#ATTACH_ERR_LOGS and StandaloneDebuggingText#ATTACH_OUT_LOGS are
true
, it calls StandaloneDebuggingText.ConsoleLogRidirector#printErrLog() and StandaloneDebuggingText.ConsoleLogRidirector#printOutLog() in order to eventually print all the message in the console. Moreover, it adds the messages to the GUI if StandaloneDebuggingText#PRINT_ON_GUI is
true
See Also
it.emarolab.cagg.debugging.baseComponents.customPanel.LogDebuggingGuiPanel
Returns
returns the shown messages as a string or an empty string if StandaloneDebuggingText#ATTACH_ERR_LOGS or StandaloneDebuggingText#ATTACH_OUT_LOGS are
false
Definition at line 661 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.flushErr(), and it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.flushOut().
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.finalize().
static String it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.getFilePath () static
Returns
the directory path to the logging file. It is
empty()
if the system is not saving the logs. Particularly, this indormation is manaed by the internal instance of ConsoleLogRidirector.
Definition at line 718 of file StandaloneDebuggingText.java.
static String it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.getFormattedDate () static
Returns
a string that express the atucal date and time as
"dd-MM-yyyy_HH:mm:ss"
Definition at line 671 of file StandaloneDebuggingText.java.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.getFormattedDateMilli().
static String it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.getFormattedDate (String format) static
Definition at line 679 of file StandaloneDebuggingText.java.
static String it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.getFormattedDateMilli () static
Definition at line 675 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.getFormattedDate().
static String it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.getPrefix (String prefix) static private
Definition at line 450 of file StandaloneDebuggingText.java.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.error(), it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.info(), it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.ok(), and it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.warning().
static String it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.getTime4Log () static private
Definition at line 455 of file StandaloneDebuggingText.java.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.error(), it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.info(), it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.ok(), and it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.warning().
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.info (String prefix, Object obj) static
calls info(String) by using the method Object#toString() of the input parameter
Parameters
obj the object to print by calling the method
toString()
Definition at line 463 of file StandaloneDebuggingText.java.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.error(), and it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.info().
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.info (Object obj) static
Definition at line 468 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.info().
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.info (String prefix, String msg) static
Print a message with the INFO tag (StandaloneDebuggingText#TAG_INFO) and clear possible redirector message queue by calling flushOutErr() method.
The logs are shown in the
System.out
stream if the flag StandaloneDebuggingText#SHOW_INFO is
true
.
Parameters
msg the message to be printed
Definition at line 477 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.flushOut(), it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.getPrefix(), it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.getTime4Log(), it.emarolab.cagg.debugging.StandaloneDebuggingText.SHOW_INFO, and it.emarolab.cagg.debugging.StandaloneDebuggingText.TAG_INFO.
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.info (String msg) static
Definition at line 485 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.info().
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.ok (String prefix, String msg) static
Print a message with the OK tag (StandaloneDebuggingText#TAG_ERROR) and clear possible redirector message queue by calling flushOutErr() method.
The logs are shown in the
System.err
stream if the flag StandaloneDebuggingText#SHOW_ERROR is
true
.
Parameters
msg the message to be printed
Definition at line 524 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.flushErr(), it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.getPrefix(), it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.getTime4Log(), it.emarolab.cagg.debugging.StandaloneDebuggingText.SHOW_ERROR, and it.emarolab.cagg.debugging.StandaloneDebuggingText.TAG_OK.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.ok().
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.ok (String msg) static
Definition at line 532 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.ok().
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.ok (String prefix, Object obj) static
calls error(String) by using the method Object#toString() of the input parameter
Parameters
obj the object to print by calling the method
toString()
Definition at line 540 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.ok().
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.ok (Object obj) static
Definition at line 545 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.ok().
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.printStackTrace () static
This method print the current thread stack trace. It can be used in order to know the method calling hierarchy in a specific point of the code. Practically, it uses:
Thread.dumpStack();
.
Definition at line 607 of file StandaloneDebuggingText.java.
static void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.setFilePath (String filePath) static
Parameters
filePath the directory path in which save all the logs. Set to
empty()
for do not saving any logs. Particularly, this indormation is manaed by the internal instance of ConsoleLogRidirector.
Definition at line 725 of file StandaloneDebuggingText.java.
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.warning (String prefix, String msg) static
Print a message with the WARNING tag (StandaloneDebuggingText#TAG_WARNING) and clear possible redirector message queue by calling flushOutErr() method.
The logs are shown in the
System.out
stream if the flag StandaloneDebuggingText#SHOW_WARNING is
true
.
Parameters
msg the message to be printed
Definition at line 494 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.flushOut(), it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.getPrefix(), it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.getTime4Log(), it.emarolab.cagg.debugging.StandaloneDebuggingText.SHOW_WARNING, and it.emarolab.cagg.debugging.StandaloneDebuggingText.TAG_WARNING.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.warning().
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.warning (String msg) static
Definition at line 502 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.warning().
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.warning (String prefix, Object obj) static
calls warning(String) by using the method Object#toString() of the input parameter
Parameters
obj the object to print by calling the method
toString()
Definition at line 510 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.warning().
static synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.warning (Object obj) static
Definition at line 515 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.warning().
Member Data Documentation
ConsoleLogRidirector it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.console static private
Definition at line 439 of file StandaloneDebuggingText.java.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.flushErr(), it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.flushOut(), and it.emarolab.cagg.debugging.StandaloneDebuggingText.Logger.Logger().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/debugging/StandaloneDebuggingText.java