ConceptActionGrammarGenerator: it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner Class Reference
it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner Class Reference
Public Member Functions
EvaluatorRunner (String threadName, String loggerName)
void implement ()
Integer getEvaluatedSolutionCount ()
List< EvaluationResults > getAllResults ()
EvaluationResults getResult (Integer idx)
Public Member Functions inherited from it.emarolab.cagg.core.evaluation.CaggThread
CaggThread ()
CaggThread (String name)
CaggThread (String name, String loggerName)
synchronized void setThreadName (String threadName)
synchronized void setRunnableId (Long runnableId)
synchronized void setLoggerName (String name)
synchronized void setLoggingStepBack (int loggingStepBack)
synchronized void shouldRun (boolean flag)
synchronized String getFormattedName ()
synchronized String getThreadName ()
synchronized Long getRunnableId ()
synchronized String getLoggerName ()
synchronized int getLoggingStepBack ()
synchronized Long getStartingTime ()
synchronized Long getEndingTime ()
synchronized boolean isRunning ()
synchronized ThreadLogger getThreadLogger ()
synchronized void log (Object msg)
synchronized void logWarning (Object msg)
synchronized void logOk (Object msg)
synchronized void logError (Object msg)
synchronized void logError (Exception e)
synchronized void terminate ()
synchronized void start ()
void run ()
void preImplement ()
abstract void implement ()
void postImplement ()
Protected Member Functions
void evaluateOnce (Facts< ?> trueFacts)
Protected Member Functions inherited from it.emarolab.cagg.core.evaluation.CaggThread
synchronized Long getTimeStamp ()
synchronized Long getRunningTime ()
Private Attributes
List< EvaluationResults > results = new ArrayList<>()
Integer evaluateSolutionIdx = 0
Additional Inherited Members
Static Public Attributes inherited from it.emarolab.cagg.core.evaluation.CaggThread
static final String DEFAULT_NAME_LOGGER = CaggLoggersManager.DEFAULT_LOGGING_NAME_UI
static final String DEFAULT_NAME_THREAD = "CaggThread"
static final int DEFAULT_LOG_STEP_BACK = 3
static final String SYST_PROPERTY_RUNNABLE_NAME = "caggLoggerThread"
Detailed Description
Definition at line 40 of file ThreadedEvaluator.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.EvaluatorRunner (String threadName, String loggerName)
Definition at line 47 of file ThreadedEvaluator.java.
References it.emarolab.cagg.core.evaluation.ThreadedEvaluator.processedSolutionIdx.
Member Function Documentation
void it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.evaluateOnce (Facts< ?> trueFacts) protected
Definition at line 81 of file ThreadedEvaluator.java.
References it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.evaluateSolutionIdx, it.emarolab.cagg.core.evaluation.CaggThread.log(), it.emarolab.cagg.debugging.DebuggingDefaults.NANOSEC_2_SEC, and it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.results.
Referenced by it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.implement().
List<EvaluationResults> it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.getAllResults ()
Definition at line 121 of file ThreadedEvaluator.java.
References it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.results.
Integer it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.getEvaluatedSolutionCount ()
Definition at line 117 of file ThreadedEvaluator.java.
References it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.evaluateSolutionIdx.
EvaluationResults it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.getResult (Integer idx)
Definition at line 126 of file ThreadedEvaluator.java.
References it.emarolab.cagg.core.evaluation.CaggThread.isRunning(), it.emarolab.cagg.core.evaluation.CaggThread.logError(), and it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.results.
void it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.implement ()
Definition at line 58 of file ThreadedEvaluator.java.
References it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.evaluateOnce(), it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.evaluateSolutionIdx, it.emarolab.cagg.core.evaluation.CaggThread.isRunning(), it.emarolab.cagg.core.evaluation.CaggThread.log(), it.emarolab.cagg.debugging.DebuggingDefaults.NANOSEC_2_SEC, it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.results, and it.emarolab.cagg.core.evaluation.CaggThread.shouldRun().
Member Data Documentation
Integer it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.evaluateSolutionIdx = 0 private
Definition at line 44 of file ThreadedEvaluator.java.
Referenced by it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.evaluateOnce(), it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.getEvaluatedSolutionCount(), and it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.implement().
List< EvaluationResults> it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.results = new ArrayList<>() private
Definition at line 43 of file ThreadedEvaluator.java.
Referenced by it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.evaluateOnce(), it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.getAllResults(), it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.getResult(), and it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.implement().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/evaluation/ThreadedEvaluator.java