ConceptActionGrammarGenerator: it.emarolab.cagg.core.evaluation.TestingTimeOutedEvaluator Class Reference
it.emarolab.cagg.core.evaluation.TestingTimeOutedEvaluator Class Reference
Public Member Functions
TestingTimeOutedEvaluator (ThreadedInputFormatter formatter, Float timeOutSec)
TestingTimeOutedEvaluator (String prefix, ThreadedInputFormatter formatter, Float timeOutSec)
Boolean triggerTimedOut (EvaluatorBase< ComposedGrammar, ThreadedInputFormatter >.EvaluationResults result)
void doWithTrueResult (EvaluatorBase< ComposedGrammar, ThreadedInputFormatter >.EvaluationResults result)
void showTestResult (String msg)
Public Member Functions inherited from it.emarolab.cagg.core.evaluation.interfacing.TimeOutedEvaluatorBase
TimeOutedEvaluatorBase (ThreadedInputFormatter formatter)
TimeOutedEvaluatorBase (ThreadedInputFormatter formatter, Float timeOutSec)
TimeOutedEvaluatorBase (ThreadedInputFormatter formatter, Boolean verbose)
TimeOutedEvaluatorBase (ThreadedInputFormatter formatter, Float timeOutSec, Boolean verbose)
TimeOutedEvaluatorBase (String prefix, ThreadedInputFormatter formatter)
TimeOutedEvaluatorBase (String prefix, ThreadedInputFormatter formatter, Float timeOutSec)
TimeOutedEvaluatorBase (String prefix, ThreadedInputFormatter formatter, Boolean verbose)
TimeOutedEvaluatorBase (String prefix, ThreadedInputFormatter formatter, Float timeOutSec, Boolean verbose)
void activateTrigger (EvaluatorBase< ComposedGrammar, ThreadedInputFormatter >.EvaluationResults result)
abstract Boolean triggerTimedOut (EvaluatorBase< ComposedGrammar, ThreadedInputFormatter >.EvaluationResults result)
abstract void doWithTrueResult (EvaluatorBase< ComposedGrammar, ThreadedInputFormatter >.EvaluationResults result)
void doWithFalseResutl (EvaluatorBase< ComposedGrammar, ThreadedInputFormatter >.EvaluationResults result)
Float getTimeOutSecRange ()
Boolean isVerbose ()
void setVerbose (Boolean verbose)
Integer getTimedOutCount ()
void resetTimedOutCount ()
Public Member Functions inherited from it.emarolab.cagg.core.evaluation.ThreadedEvaluator
ThreadedEvaluator (ThreadedInputFormatter formatter)
ThreadedEvaluator (String logPrefix, ThreadedInputFormatter formatter)
void start ()
void start (String threadName)
void stop ()
void join ()
boolean isRunning ()
EvaluationResults getNextSolution ()
Integer getEvaluationCount ()
Additional Inherited Members
Static Public Attributes inherited from it.emarolab.cagg.core.evaluation.interfacing.TimeOutedEvaluatorBase
static final Float DEFAULT_EVALUATION_TIME_OUT_SEC = null
static final Boolean VERBOSE = true
Protected Member Functions inherited from it.emarolab.cagg.core.evaluation.ThreadedEvaluator
EvaluatorRunner getEvaluatorThread ()
void setEvaluatorThread (EvaluatorRunner evalThread)
Integer getProcessedSolutionIdx ()
Detailed Description
Definition at line 8 of file TestingTimeOutedEvaluator.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.evaluation.TestingTimeOutedEvaluator.TestingTimeOutedEvaluator (ThreadedInputFormatter formatter, Float timeOutSec)
Definition at line 13 of file TestingTimeOutedEvaluator.java.
it.emarolab.cagg.core.evaluation.TestingTimeOutedEvaluator.TestingTimeOutedEvaluator (String prefix, ThreadedInputFormatter formatter, Float timeOutSec)
Definition at line 16 of file TestingTimeOutedEvaluator.java.
Member Function Documentation
void it.emarolab.cagg.core.evaluation.TestingTimeOutedEvaluator.doWithTrueResult (EvaluatorBase< ComposedGrammar, ThreadedInputFormatter >.EvaluationResults result)
Definition at line 33 of file TestingTimeOutedEvaluator.java.
References it.emarolab.cagg.core.evaluation.TestingTimeOutedEvaluator.showTestResult().
void it.emarolab.cagg.core.evaluation.TestingTimeOutedEvaluator.showTestResult (String msg)
Definition at line 38 of file TestingTimeOutedEvaluator.java.
References it.emarolab.cagg.core.evaluation.interfacing.TimeOutedEvaluatorBase.isVerbose().
Referenced by it.emarolab.cagg.core.evaluation.TestingTimeOutedEvaluator.doWithTrueResult(), and it.emarolab.cagg.core.evaluation.TestingTimeOutedEvaluator.triggerTimedOut().
Boolean it.emarolab.cagg.core.evaluation.TestingTimeOutedEvaluator.triggerTimedOut (EvaluatorBase< ComposedGrammar, ThreadedInputFormatter >.EvaluationResults result)
Definition at line 24 of file TestingTimeOutedEvaluator.java.
References it.emarolab.cagg.core.evaluation.interfacing.TimeOutedEvaluatorBase.getTimeOutSecRange(), and it.emarolab.cagg.core.evaluation.TestingTimeOutedEvaluator.showTestResult().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/evaluation/TestingTimeOutedEvaluator.java