ConceptActionGrammarGenerator: it.emarolab.cagg.example.APIusage Class Reference
it.emarolab.cagg.example.APIusage Class Reference
Static Public Member Functions
static void main (String[] args)
Static Public Attributes
static final String USER_SPEECH_INPUT = "Are there 2 cones?"
static boolean TEST = true
static final String SOURCE_BASE_PATH = DebuggingDefaults.PATH_ABSOLUTE_NOTJAR
static final String[] SOURCE_PATS
static final String SERIALISATION_PATH = DebuggingDefaults.PATH_GRAMMA_DESERIALISATION_NOTJAR + "query_scene.ser"
static final int COMPILE = 0
static final int DESERIALISE = 1
static int command = COMPILE
Static Private Member Functions
static CaggCompiler compile ()
static void evaluate (GrammarBase< SemanticTree > grammar)
Detailed Description
Definition at line 17 of file APIusage.java.
Member Function Documentation
static CaggCompiler it.emarolab.cagg.example.APIusage.compile () static private
Definition at line 40 of file APIusage.java.
References it.emarolab.cagg.example.APIusage.SERIALISATION_PATH, and it.emarolab.cagg.example.APIusage.SOURCE_PATS.
Referenced by it.emarolab.cagg.example.APIusage.main().
static void it.emarolab.cagg.example.APIusage.evaluate (GrammarBase< SemanticTree > grammar) static private
Definition at line 50 of file APIusage.java.
References it.emarolab.cagg.example.APIusage.USER_SPEECH_INPUT.
Referenced by it.emarolab.cagg.example.APIusage.main().
static void it.emarolab.cagg.example.APIusage.main (String[] args) static
Definition at line 60 of file APIusage.java.
References it.emarolab.cagg.example.APIusage.command, it.emarolab.cagg.example.APIusage.COMPILE, it.emarolab.cagg.example.APIusage.compile(), it.emarolab.cagg.example.APIusage.DESERIALISE, it.emarolab.cagg.example.APIusage.evaluate(), it.emarolab.cagg.example.APIusage.SERIALISATION_PATH, and it.emarolab.cagg.example.APIusage.TEST.
Member Data Documentation
int it.emarolab.cagg.example.APIusage.command = COMPILE static
Definition at line 36 of file APIusage.java.
Referenced by it.emarolab.cagg.example.APIusage.main().
final int it.emarolab.cagg.example.APIusage.COMPILE = 0 static
Definition at line 34 of file APIusage.java.
Referenced by it.emarolab.cagg.example.APIusage.main().
final int it.emarolab.cagg.example.APIusage.DESERIALISE = 1 static
Definition at line 35 of file APIusage.java.
Referenced by it.emarolab.cagg.example.APIusage.main().
final String it.emarolab.cagg.example.APIusage.SERIALISATION_PATH = DebuggingDefaults.PATH_GRAMMA_DESERIALISATION_NOTJAR + "query_scene.ser" static
Definition at line 31 of file APIusage.java.
Referenced by it.emarolab.cagg.example.APIusage.compile(), and it.emarolab.cagg.example.APIusage.main().
final String it.emarolab.cagg.example.APIusage.SOURCE_BASE_PATH = DebuggingDefaults.PATH_ABSOLUTE_NOTJAR static
Definition at line 26 of file APIusage.java.
final String [] it.emarolab.cagg.example.APIusage.SOURCE_PATS static
Initial value:
= {
        SOURCE_BASE_PATH + "englishBase.cagg",          SOURCE_BASE_PATH + "englishQuestions.cagg",
        SOURCE_BASE_PATH + "ontoEntities.cagg",         SOURCE_BASE_PATH + "ontoProperty.cagg"
    }
Definition at line 27 of file APIusage.java.
Referenced by it.emarolab.cagg.example.APIusage.compile().
boolean it.emarolab.cagg.example.APIusage.TEST = true static
Definition at line 23 of file APIusage.java.
Referenced by it.emarolab.cagg.example.APIusage.main().
final String it.emarolab.cagg.example.APIusage.USER_SPEECH_INPUT = "Are there 2 cones?" static
Definition at line 22 of file APIusage.java.
Referenced by it.emarolab.cagg.example.APIusage.evaluate().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/example/APIusage.java