ConceptActionGrammarGenerator: it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames Class Reference
it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames Class Reference
Public Member Functions
LoggersNames ()
LoggersNames (String evaluatorLoggerName, String formatterLoggerName, String uiLoggerName, String parsingLoggingName, String grammarLoggingName, String testLoggingName)
LoggersNames (String uiLoggerName, String parsingLoggerName, String grammarLoggingName, String testLoggingName)
String getEvaluatorLoggerName ()
String getFormatterLoggerName ()
String getUILoggerName ()
String getParsingLoggerName ()
String getGrammarLoggerName ()
String getTestLoggerName ()
String toString ()
void logEvaluatorInfo (Object o)
void logEvaluatorWarning (Object o)
void logEvaluatorError (Object o)
void logEvaluatorError (Exception e)
void logEvaluatorOk (Object o)
void logFormatterInfo (Object o)
void logFormatterWarning (Object o)
void logFormatterError (Object o)
void logFormatterError (Exception e)
void logFormatterOk (Object o)
void logUIInfo (Object o)
void logUIWarning (Object o)
void logUIError (Object o)
void logUIError (Exception e)
void logUIOk (Object o)
void logParsingInfo (Object o)
void logParsingWarning (Object o)
void logParsingError (Object o)
void logParsingError (Exception e)
void logParsingOk (Object o)
void logGrammarInfo (Object o)
void logGrammarWarning (Object o)
void logGrammarError (Object o)
void logGrammarError (Exception e)
void logGrammarOk (Object o)
void logTestInfo (Object o)
void logTestWarning (Object o)
void logTestError (Object o)
void logTestError (Exception e)
void logTestOk (Object o)
Protected Attributes
Boolean isComplete = null
Private Attributes
String evaluatorLoggerName = null
String formatterLoggerName = null
String uiLoggerName = null
String parsingLoggingName = null
String grammarLoggingName = null
String testLoggingName = null
Detailed Description
Definition at line 117 of file CaggLoggersManager.java.
Constructor & Destructor Documentation
it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.LoggersNames ()
Definition at line 127 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_EVALUATOR, it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_FORMATTER, it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_GRAMMAR, it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_PARSING, it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_TEST, and it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_UI.
it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.LoggersNames (String evaluatorLoggerName, String formatterLoggerName, String uiLoggerName, String parsingLoggingName, String grammarLoggingName, String testLoggingName)
Definition at line 136 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.evaluatorLoggerName, it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.formatterLoggerName, it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.grammarLoggingName, it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.parsingLoggingName, it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.testLoggingName, and it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.uiLoggerName.
it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.LoggersNames (String uiLoggerName, String parsingLoggerName, String grammarLoggingName, String testLoggingName)
Definition at line 145 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.grammarLoggingName, it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.testLoggingName, and it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.uiLoggerName.
Member Function Documentation
String it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getEvaluatorLoggerName ()
Definition at line 153 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.evaluatorLoggerName.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.applyAll(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logEvaluatorError(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logEvaluatorInfo(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logEvaluatorOk(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logEvaluatorWarning(), and it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.toString().
String it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getFormatterLoggerName ()
Definition at line 156 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.formatterLoggerName.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.applyAll(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logFormatterError(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logFormatterInfo(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logFormatterOk(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logFormatterWarning(), and it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.toString().
String it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getGrammarLoggerName ()
Definition at line 165 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.grammarLoggingName.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.applyAll(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logGrammarError(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logGrammarInfo(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logGrammarOk(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logGrammarWarning(), and it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.toString().
String it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getParsingLoggerName ()
Definition at line 162 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.parsingLoggingName.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.applyAll(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logParsingError(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logParsingInfo(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logParsingOk(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logParsingWarning(), and it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.toString().
String it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getTestLoggerName ()
Definition at line 168 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.testLoggingName.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.applyAll(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logTestError(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logTestInfo(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logTestOk(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logTestWarning(), and it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.toString().
String it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getUILoggerName ()
Definition at line 159 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.uiLoggerName.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.applyAll(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logUIError(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logUIInfo(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logUIOk(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logUIWarning(), and it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.toString().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logEvaluatorError (Object o)
Definition at line 184 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getEvaluatorLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logEvaluatorError (Exception e)
Definition at line 187 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getEvaluatorLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logEvaluatorInfo (Object o)
Definition at line 178 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getEvaluatorLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logEvaluatorOk (Object o)
Definition at line 190 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getEvaluatorLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logEvaluatorWarning (Object o)
Definition at line 181 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getEvaluatorLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logFormatterError (Object o)
Definition at line 200 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getFormatterLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logFormatterError (Exception e)
Definition at line 203 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getFormatterLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logFormatterInfo (Object o)
Definition at line 194 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getFormatterLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logFormatterOk (Object o)
Definition at line 206 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getFormatterLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logFormatterWarning (Object o)
Definition at line 197 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getFormatterLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logGrammarError (Object o)
Definition at line 248 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getGrammarLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logGrammarError (Exception e)
Definition at line 251 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getGrammarLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logGrammarInfo (Object o)
Definition at line 242 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getGrammarLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logGrammarOk (Object o)
Definition at line 254 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getGrammarLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logGrammarWarning (Object o)
Definition at line 245 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getGrammarLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logParsingError (Object o)
Definition at line 232 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getParsingLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logParsingError (Exception e)
Definition at line 235 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getParsingLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logParsingInfo (Object o)
Definition at line 226 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getParsingLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logParsingOk (Object o)
Definition at line 238 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getParsingLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logParsingWarning (Object o)
Definition at line 229 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getParsingLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logTestError (Object o)
Definition at line 264 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getTestLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logTestError (Exception e)
Definition at line 267 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getTestLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logTestInfo (Object o)
Definition at line 258 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getTestLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logTestOk (Object o)
Definition at line 270 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getTestLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logTestWarning (Object o)
Definition at line 261 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getTestLoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logUIError (Object o)
Definition at line 216 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getUILoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logUIError (Exception e)
Definition at line 219 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getUILoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logUIInfo (Object o)
Definition at line 210 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getUILoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logUIOk (Object o)
Definition at line 222 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getUILoggerName().
void it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.logUIWarning (Object o)
Definition at line 213 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getUILoggerName().
String it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.toString ()
Definition at line 173 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getEvaluatorLoggerName(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getFormatterLoggerName(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getGrammarLoggerName(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getParsingLoggerName(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getTestLoggerName(), and it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getUILoggerName().
Member Data Documentation
String it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.evaluatorLoggerName = null private
Definition at line 119 of file CaggLoggersManager.java.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getEvaluatorLoggerName(), and it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.LoggersNames().
String it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.formatterLoggerName = null private
Definition at line 120 of file CaggLoggersManager.java.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getFormatterLoggerName(), and it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.LoggersNames().
String it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.grammarLoggingName = null private
Definition at line 123 of file CaggLoggersManager.java.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getGrammarLoggerName(), and it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.LoggersNames().
Boolean it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.isComplete = null protected
Definition at line 125 of file CaggLoggersManager.java.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.applyAll().
String it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.parsingLoggingName = null private
Definition at line 122 of file CaggLoggersManager.java.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getParsingLoggerName(), and it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.LoggersNames().
String it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.testLoggingName = null private
Definition at line 124 of file CaggLoggersManager.java.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getTestLoggerName(), and it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.LoggersNames().
String it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.uiLoggerName = null private
Definition at line 121 of file CaggLoggersManager.java.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getUILoggerName(), and it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.LoggersNames().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/debugging/CaggLoggersManager.java