ConceptActionGrammarGenerator: it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode Class Reference
it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode Class Reference
Classes
class SemanticExpressionEvaluator
class SemanticTreeBuilder
Public Member Functions
SemanticNode (ExpressionNode<?> syntaxNode)
SemanticNode (ExpressionNode<?> syntaxNode, TagBase<?> tags)
SemanticNode copy (Boolean updateCopyId)
SemanticNode copyContents (BaseNode newNode, Boolean generateCopyId)
String toString ()
void setValue (Boolean value)
Boolean hasTags ()
Boolean isTerm ()
Type getType ()
TagBase<?> getTags ()
Boolean getValue ()
BaseData<?> getSyntaxData ()
SemanticResult evaluate ()
SemanticNode buildSemanticTree (ExpressionNode<?> composedTree)
Public Member Functions inherited from it.emarolab.cagg.core.evaluation.semanticGrammar.syntaxCompiler.SemanticExpressionTreeBase.SemanticExpressionNodeBase
SemanticExpressionNodeBase ()
SemanticExpressionNodeBase (Integer maxChildrenCount, String prefixId)
SemanticExpressionNodeBase (Integer maxChildrenCount)
SemanticExpressionNodeBase (String prefixId)
Public Member Functions inherited from it.emarolab.cagg.core.PseudoBinaryNode
PseudoBinaryNode ()
PseudoBinaryNode (String prefixId)
PseudoBinaryNode (Integer maxChildrenCount)
PseudoBinaryNode (Integer maxChildrenCount, String prefixId)
abstract PseudoBinaryNode copy (Boolean createNewCopyID)
PseudoBinaryNode getChild (int i)
PseudoBinaryNode getLeftChild ()
PseudoBinaryNode getRightChild ()
Integer getMaxChildrenCount ()
Boolean isComplite ()
Boolean isLeft ()
boolean hasLeftChild ()
boolean hasRightChild ()
void add (MutableTreeNode newChild)
void addChildren (PseudoBinaryNode leftChild, PseudoBinaryNode rightChild)
void addChild (PseudoBinaryNode newChild)
void addLeftChild (PseudoBinaryNode newChild)
void addRightChild (PseudoBinaryNode newChild)
void add (int position, BaseNode newChild)
void remove (MutableTreeNode aChild)
void remove (int childIndex)
void removeFromParent ()
void removeAllChildren ()
void replaceLeftChild (PseudoBinaryNode newChild)
void replaceRightChild (PseudoBinaryNode newChild)
String getDebuggingId ()
String toTreeString ()
PseudoBinaryNode copyTree ()
PseudoBinaryNode copyTree (Boolean updateCopyId)
PseudoBinaryNode copyTreeWithNewID (Map< Long, List< String >> tagMap)
PseudoBinaryNode copyTreeWithNewID (Map< Long, List< String >> tagMap, Boolean resetOriginalId)
Map< Long, BaseNode > toMap ()
Map< Long, BaseNode > toMap (Boolean useCopyId)
Map< Long, BaseNode > toTermMap ()
Map< Long, BaseNode > toTermMap (Boolean useCopyId)
Public Member Functions inherited from it.emarolab.cagg.core.BaseNode
BaseNode ()
BaseNode (String prefixId)
abstract String toString ()
Long getOriginalId ()
Long getId ()
BaseNode getParent ()
Long getCopyId ()
Boolean isCopy ()
void setPrefixId (String prefixId)
String getPrefixId ()
String getDebuggingId ()
List< BaseNode > getChildrenArray ()
void add (int position, BaseNode newChild)
BaseNode getChild (int index)
void printTree ()
String toTreeString ()
BaseNode copyContents (BaseNode newNode, Boolean generateCopyId)
BaseNode copyTree ()
BaseNode copyTree (final Boolean updateCopyId)
BaseNode copyTreeWithNewID (Map< Long, List< String >> tagMap)
Map< Long, BaseNode > toMap ()
Map< Long, BaseNode > toMap (Boolean useCopyId)
void showTree ()
void showTree (final String frameTitle)
Public Member Functions inherited from it.emarolab.cagg.core.evaluation.semanticGrammar.syntaxCompiler.SemanticExpressionTreeBase.SemanticExpressionPrimitive
Long getId ()
Static Public Attributes
static final String TREE_PREFIX_ID = "ST:"
Static Public Attributes inherited from it.emarolab.cagg.core.BaseNode
static final String DEFAULT_PREFIX_ID = "m"
static Boolean DEFAULT_VERBOSE = false
static Boolean LOG_TOTAL_TIME_ANYTWAY = false
static String DEFAULT_VISITOR_NAME = "visitor"
static String DEFAULT_WALKER_NAME = "walker"
Protected Member Functions
void setTag (TagBase<?> tag)
void evaluate (List< Boolean > childrenValue)
ActionTagBase buildNewEvaluationActionTags ()
Protected Member Functions inherited from it.emarolab.cagg.core.PseudoBinaryNode
void setLeft ()
void setRight ()
void resetPosition ()
void add (MutableTreeNode newChild, Boolean suppressWarning)
Protected Member Functions inherited from it.emarolab.cagg.core.BaseNode
abstract BaseNode copy (Boolean createNewCopyID)
void setOriginalId (Long originalId)
void setId (Long id)
void add (MutableTreeNode newChild, Boolean suppressWarning)
Private Member Functions
SemanticNode ()
void initialise (ExpressionNode<?> syntaxNode)
Private Attributes
TagBase<?> tag
Boolean hasTags = false
Boolean value = null
Type type
ExpressionNode<?>.NodeEvaluator evaluator
BaseData<?> syntaxData
ActionTagBase evaluationActionTag
Detailed Description
Definition at line 107 of file SemanticTree.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.SemanticNode () private
Definition at line 119 of file SemanticTree.java.
it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.SemanticNode (ExpressionNode<?> syntaxNode)
Definition at line 122 of file SemanticTree.java.
it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.SemanticNode (ExpressionNode<?> syntaxNode, TagBase<?> tags)
Definition at line 126 of file SemanticTree.java.
Member Function Documentation
ActionTagBase it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.buildNewEvaluationActionTags () protected
Definition at line 225 of file SemanticTree.java.
SemanticNode it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.buildSemanticTree (ExpressionNode<?> composedTree)
Definition at line 319 of file SemanticTree.java.
SemanticNode it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.copy (Boolean updateCopyId)
Definition at line 143 of file SemanticTree.java.
SemanticNode it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.copyContents (BaseNode newNode, Boolean generateCopyId)
Definition at line 147 of file SemanticTree.java.
References it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.copyContents(), and it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.setTag().
Referenced by it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.copyContents().
void it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.evaluate (List< Boolean > childrenValue) protected
Definition at line 217 of file SemanticTree.java.
SemanticResult it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.evaluate ()
Definition at line 228 of file SemanticTree.java.
BaseData<?> it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.getSyntaxData ()
Implements it.emarolab.cagg.core.evaluation.semanticGrammar.syntaxCompiler.SemanticExpressionTreeBase.SemanticExpressionPrimitive.
Definition at line 213 of file SemanticTree.java.
TagBase<?> it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.getTags ()
Implements it.emarolab.cagg.core.evaluation.semanticGrammar.syntaxCompiler.SemanticExpressionTreeBase.SemanticExpressionPrimitive.
Definition at line 207 of file SemanticTree.java.
Type it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.getType ()
Definition at line 204 of file SemanticTree.java.
Boolean it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.getValue ()
Implements it.emarolab.cagg.core.evaluation.semanticGrammar.syntaxCompiler.SemanticExpressionTreeBase.SemanticExpressionPrimitive.
Definition at line 210 of file SemanticTree.java.
Referenced by it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.SemanticExpressionEvaluator.exitNode(), and it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.SemanticExpressionEvaluator.updateActionTags().
Boolean it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.hasTags ()
Definition at line 198 of file SemanticTree.java.
void it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.initialise (ExpressionNode<?> syntaxNode) private
Definition at line 131 of file SemanticTree.java.
Boolean it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.isTerm ()
Definition at line 201 of file SemanticTree.java.
void it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.setTag (TagBase<?> tag) protected
Definition at line 186 of file SemanticTree.java.
Referenced by it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.copyContents().
void it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.setValue (Boolean value)
Implements it.emarolab.cagg.core.evaluation.semanticGrammar.syntaxCompiler.SemanticExpressionTreeBase.SemanticExpressionPrimitive.
Definition at line 194 of file SemanticTree.java.
String it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.toString ()
Definition at line 159 of file SemanticTree.java.
Member Data Documentation
ActionTagBase it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.evaluationActionTag private
Definition at line 117 of file SemanticTree.java.
Referenced by it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.SemanticExpressionEvaluator.exitNode().
ExpressionNode<?>.NodeEvaluator it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.evaluator private
Definition at line 115 of file SemanticTree.java.
Boolean it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.hasTags = false private
Definition at line 112 of file SemanticTree.java.
Referenced by it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.SemanticExpressionEvaluator.updateActionTags().
BaseData<?> it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.syntaxData private
Definition at line 116 of file SemanticTree.java.
TagBase<?> it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.tag private
Definition at line 111 of file SemanticTree.java.
final String it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.TREE_PREFIX_ID = "ST:" static
Definition at line 109 of file SemanticTree.java.
Type it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.type private
Definition at line 114 of file SemanticTree.java.
Boolean it.emarolab.cagg.core.evaluation.semanticGrammar.SemanticTree.SemanticNode.value = null private
Definition at line 113 of file SemanticTree.java.
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/evaluation/semanticGrammar/SemanticTree.java