ConceptActionGrammarGenerator: it.emarolab.cagg.debugging.DebuggingText.Logger Class Reference
it.emarolab.cagg.debugging.DebuggingText.Logger Class Reference
Static Public Member Functions
static synchronized void info (int backStep, String loggerName, String threadName, Object msg)
static synchronized void info (int backStep, String loggerName, Object msg)
static synchronized void info (int backStep, Object msg)
static synchronized void info (String loggerName, Object msg)
static synchronized void info (Object msg)
static synchronized void warning (int backStep, String loggerName, String threadName, Object msg)
static synchronized void warning (int backStep, String loggerName, Object msg)
static synchronized void warning (int backStep, Object msg)
static synchronized void warning (String loggerName, Object msg)
static synchronized void warning (Object msg)
static synchronized void error (int backStep, String loggerName, String threadName, Object msg)
static synchronized void error (int backStep, String loggerName, Object msg)
static synchronized void error (int backStep, Object msg)
static synchronized void error (String loggerName, Object msg)
static synchronized void error (Object msg)
static synchronized void error (int backStep, String loggerName, String threadName, Exception e)
static synchronized void error (int backStep, String loggerName, Exception e)
static synchronized void error (int backStep, Exception e)
static synchronized void error (String loggerName, Exception e)
static synchronized void error (Exception e)
static synchronized void ok (int backStep, String loggerName, String threadName, Object msg)
static synchronized void ok (int backStep, String loggerName, Object msg)
static synchronized void ok (int backStep, Object msg)
static synchronized void ok (String loggerName, Object msg)
static synchronized void ok (Object msg)
Detailed Description
Definition at line 136 of file DebuggingText.java.
Member Function Documentation
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.error (int backStep, String loggerName, String threadName, Object msg) static
Definition at line 174 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.getLogger().
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.error (int backStep, String loggerName, Object msg) static
Definition at line 177 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.getLogger().
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.error (int backStep, Object msg) static
Definition at line 180 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.loggerMap.
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.error (String loggerName, Object msg) static
Definition at line 184 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.getLogger().
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.error (Object msg) static
Definition at line 187 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.loggerMap.
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.error (int backStep, String loggerName, String threadName, Exception e) static
Definition at line 192 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.getLogger().
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.error (int backStep, String loggerName, Exception e) static
Definition at line 195 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.getLogger().
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.error (int backStep, Exception e) static
Definition at line 198 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.loggerMap.
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.error (String loggerName, Exception e) static
Definition at line 202 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.getLogger().
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.error (Exception e) static
Definition at line 205 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.loggerMap.
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.info (int backStep, String loggerName, String threadName, Object msg) static
Definition at line 138 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.getLogger().
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.info (int backStep, String loggerName, Object msg) static
Definition at line 141 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.getLogger().
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.info (int backStep, Object msg) static
Definition at line 144 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.loggerMap.
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.info (String loggerName, Object msg) static
Definition at line 148 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.getLogger().
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.info (Object msg) static
Definition at line 151 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.loggerMap.
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.ok (int backStep, String loggerName, String threadName, Object msg) static
Definition at line 210 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.getLogger().
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.ok (int backStep, String loggerName, Object msg) static
Definition at line 213 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.getLogger().
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.ok (int backStep, Object msg) static
Definition at line 216 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.loggerMap.
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.ok (String loggerName, Object msg) static
Definition at line 220 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.getLogger().
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.ok (Object msg) static
Definition at line 223 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.loggerMap.
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.warning (int backStep, String loggerName, String threadName, Object msg) static
Definition at line 156 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.getLogger().
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.warning (int backStep, String loggerName, Object msg) static
Definition at line 159 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.getLogger().
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.warning (int backStep, Object msg) static
Definition at line 162 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.loggerMap.
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.warning (String loggerName, Object msg) static
Definition at line 166 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.getLogger().
static synchronized void it.emarolab.cagg.debugging.DebuggingText.Logger.warning (Object msg) static
Definition at line 169 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.loggerMap.
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/debugging/DebuggingText.java