ConceptActionGrammarGenerator: it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener Class Reference
it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener Class Reference
Public Member Functions
LogicalParserListener ()
Boolean isInGrammarRoot ()
void enterNuanceGrammar (NuanceGrammarContext ctx)
void exitNuanceGrammar (NuanceGrammarContext ctx)
Boolean isInGrammarPreamble ()
void enterPreamble (PreambleContext ctx)
void exitPreamble (PreambleContext ctx)
void enterGrammarHearder (GrammarHearderContext ctx)
void exitGrammarHearder (GrammarHearderContext ctx)
Boolean isInGrammarBody ()
void enterBody (BodyContext ctx)
void exitBody (BodyContext ctx)
Boolean isInRuleDeclarationPreamble ()
Boolean isInRuleDeclarationBody ()
void enterRuleDeclaration (RuleDeclarationContext ctx)
void exitRuleDeclaration (RuleDeclarationContext ctx)
Boolean isInRuleBody ()
void enterRuleBody (RuleBodyContext ctx)
void exitRuleBody (RuleBodyContext ctx)
Boolean isOrOperation ()
void enterOrOperator (OrOperatorContext ctx)
Boolean isAndOperation ()
void enterAndOperator (AndOperatorContext ctx)
Boolean isRuleTerm ()
void enterRuleTerm (RuleTermContext ctx)
Public Member Functions inherited from it.emarolab.cagg.core.language.parser.ANTLRInterface.ANTLRGenerated.CAGGSyntaxDefinitionBaseListener
void enterExportDeclaration (@NotNull CAGGSyntaxDefinitionParser.ExportDeclarationContext ctx)
void exitExportDeclaration (@NotNull CAGGSyntaxDefinitionParser.ExportDeclarationContext ctx)
void enterActivableDeclaration (@NotNull CAGGSyntaxDefinitionParser.ActivableDeclarationContext ctx)
void exitActivableDeclaration (@NotNull CAGGSyntaxDefinitionParser.ActivableDeclarationContext ctx)
void enterPreamble (@NotNull CAGGSyntaxDefinitionParser.PreambleContext ctx)
void exitPreamble (@NotNull CAGGSyntaxDefinitionParser.PreambleContext ctx)
void enterRuleBody (@NotNull CAGGSyntaxDefinitionParser.RuleBodyContext ctx)
void exitRuleBody (@NotNull CAGGSyntaxDefinitionParser.RuleBodyContext ctx)
void enterRuleTerm (@NotNull CAGGSyntaxDefinitionParser.RuleTermContext ctx)
void exitRuleTerm (@NotNull CAGGSyntaxDefinitionParser.RuleTermContext ctx)
void enterBody (@NotNull CAGGSyntaxDefinitionParser.BodyContext ctx)
void exitBody (@NotNull CAGGSyntaxDefinitionParser.BodyContext ctx)
void enterPronounceDeclaration (@NotNull CAGGSyntaxDefinitionParser.PronounceDeclarationContext ctx)
void exitPronounceDeclaration (@NotNull CAGGSyntaxDefinitionParser.PronounceDeclarationContext ctx)
void enterRepeatDirective (@NotNull CAGGSyntaxDefinitionParser.RepeatDirectiveContext ctx)
void exitRepeatDirective (@NotNull CAGGSyntaxDefinitionParser.RepeatDirectiveContext ctx)
void enterPronunceLabel (@NotNull CAGGSyntaxDefinitionParser.PronunceLabelContext ctx)
void exitPronunceLabel (@NotNull CAGGSyntaxDefinitionParser.PronunceLabelContext ctx)
void enterActionDirective (@NotNull CAGGSyntaxDefinitionParser.ActionDirectiveContext ctx)
void exitActionDirective (@NotNull CAGGSyntaxDefinitionParser.ActionDirectiveContext ctx)
void enterGrammarHearder (@NotNull CAGGSyntaxDefinitionParser.GrammarHearderContext ctx)
void exitGrammarHearder (@NotNull CAGGSyntaxDefinitionParser.GrammarHearderContext ctx)
void enterImportDeclaration (@NotNull CAGGSyntaxDefinitionParser.ImportDeclarationContext ctx)
void exitImportDeclaration (@NotNull CAGGSyntaxDefinitionParser.ImportDeclarationContext ctx)
void enterNuanceGrammar (@NotNull CAGGSyntaxDefinitionParser.NuanceGrammarContext ctx)
void exitNuanceGrammar (@NotNull CAGGSyntaxDefinitionParser.NuanceGrammarContext ctx)
void enterRuleDirective (@NotNull CAGGSyntaxDefinitionParser.RuleDirectiveContext ctx)
void exitRuleDirective (@NotNull CAGGSyntaxDefinitionParser.RuleDirectiveContext ctx)
void enterGrammarDeclaration (@NotNull CAGGSyntaxDefinitionParser.GrammarDeclarationContext ctx)
void exitGrammarDeclaration (@NotNull CAGGSyntaxDefinitionParser.GrammarDeclarationContext ctx)
void enterRuleExpression (@NotNull CAGGSyntaxDefinitionParser.RuleExpressionContext ctx)
void exitRuleExpression (@NotNull CAGGSyntaxDefinitionParser.RuleExpressionContext ctx)
void enterActionDefinition (@NotNull CAGGSyntaxDefinitionParser.ActionDefinitionContext ctx)
void exitActionDefinition (@NotNull CAGGSyntaxDefinitionParser.ActionDefinitionContext ctx)
void enterStartDeclaration (@NotNull CAGGSyntaxDefinitionParser.StartDeclarationContext ctx)
void exitStartDeclaration (@NotNull CAGGSyntaxDefinitionParser.StartDeclarationContext ctx)
void enterAndOperator (@NotNull CAGGSyntaxDefinitionParser.AndOperatorContext ctx)
void exitAndOperator (@NotNull CAGGSyntaxDefinitionParser.AndOperatorContext ctx)
void enterRuleDeclaration (@NotNull CAGGSyntaxDefinitionParser.RuleDeclarationContext ctx)
void exitRuleDeclaration (@NotNull CAGGSyntaxDefinitionParser.RuleDeclarationContext ctx)
void enterOrOperator (@NotNull CAGGSyntaxDefinitionParser.OrOperatorContext ctx)
void exitOrOperator (@NotNull CAGGSyntaxDefinitionParser.OrOperatorContext ctx)
void enterModifableDeclaration (@NotNull CAGGSyntaxDefinitionParser.ModifableDeclarationContext ctx)
void exitModifableDeclaration (@NotNull CAGGSyntaxDefinitionParser.ModifableDeclarationContext ctx)
void enterLanguageDeclaration (@NotNull CAGGSyntaxDefinitionParser.LanguageDeclarationContext ctx)
void exitLanguageDeclaration (@NotNull CAGGSyntaxDefinitionParser.LanguageDeclarationContext ctx)
void enterOptionalDirective (@NotNull CAGGSyntaxDefinitionParser.OptionalDirectiveContext ctx)
void exitOptionalDirective (@NotNull CAGGSyntaxDefinitionParser.OptionalDirectiveContext ctx)
void enterLabelDirective (@NotNull CAGGSyntaxDefinitionParser.LabelDirectiveContext ctx)
void exitLabelDirective (@NotNull CAGGSyntaxDefinitionParser.LabelDirectiveContext ctx)
void enterIdDirective (@NotNull CAGGSyntaxDefinitionParser.IdDirectiveContext ctx)
void exitIdDirective (@NotNull CAGGSyntaxDefinitionParser.IdDirectiveContext ctx)
void enterPronounceDirective (@NotNull CAGGSyntaxDefinitionParser.PronounceDirectiveContext ctx)
void exitPronounceDirective (@NotNull CAGGSyntaxDefinitionParser.PronounceDirectiveContext ctx)
void enterEveryRule (@NotNull ParserRuleContext ctx)
void exitEveryRule (@NotNull ParserRuleContext ctx)
void visitTerminal (@NotNull TerminalNode node)
void visitErrorNode (@NotNull ErrorNode node)
Protected Member Functions
List< ParseTree > getChildOfTypeOR (ParseTree node)
List< ParseTree > getChildOfTypeAND (ParseTree node)
List< ParseTree > getChildOfTypeTerm (ParseTree node)
List< ParseTree > getChildOfTypeExpression (ParseTree node)
List< ParseTree > getChildOfTypeDirective (ParseTree node)
Boolean hasChildWithXChildren (ParseTree node, int X)
Boolean hasChildWith0Children (ParseTree node)
Boolean hasChildWith1Children (ParseTree node)
Boolean hasChildWith2Children (ParseTree node)
Boolean hasChildWith3Children (ParseTree node)
Boolean hasChildrenWithSymbol (ParseTree orChild, String symbol)
Boolean hasChildrenWithOrSymbol (ParseTree orChild)
Private Attributes
Boolean inGrammarRoot = false
Boolean inGrammarPreamble = false
Boolean inGrammarBody = false
Boolean inRuleDeclarationPreamble = false
Boolean inRuleBody = false
Boolean orOperation = false
Boolean andOperation = false
Boolean ruleTerm = false
Detailed Description
Version
Concept-Action Grammar Generator 1.1
File: src//cagg.core.sourceInterface.parser.ANTLRInterface.LogicalParserListener.java
Author
Buoncompagni Luca
DIBRIS, emaroLab,
University of Genoa.
15/gen/2016
This class extends the CAGGSyntaxDefinitionBaseListener in order to set the value of flags used later to identify the the meaning of a node in the Parsing Tree (PT) based on its positions with respect to neighbourhood nodes. This object is design to assure flag consistency in
enter
-ing node methods.
Moreover, it is important to know that this implementation is based on the ANTLR grammar definition available in the file:
../files/parserGrammar/NuanceGrammar.g4
See Also
CAGGSyntaxDefinitionBaseListener
TreeParserListener
ParserListener
Definition at line 46 of file LogicalParserListener.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.LogicalParserListener ()
This constructor just calls its relative super class constructor it.emarolab.cagg.core.language.parser.ANTLRInterface.ANTLRGenerated.CAGGSyntaxDefinitionBaseListener#NuanceGrammarBaseListener() in order to initialise this object.
Definition at line 69 of file LogicalParserListener.java.
Member Function Documentation
void it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterAndOperator (AndOperatorContext ctx)
This method set isAndOperation() to
true
if this node has at least a child node of type
andOperation
which, in turn, has at least a child. Otherwise, it set it to
false
. Then, it calls its super-method: enterAndOperator(CAGGSyntaxDefinitionParser.AndOperatorContext)
Definition at line 325 of file LogicalParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.andOperation, and it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.getChildOfTypeAND().
void it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterBody (BodyContext ctx)
This method just sets isInGrammarBody() to
true
before to call its super method: CAGGSyntaxDefinitionBaseListener#enterBody(CAGGSyntaxDefinitionParser.BodyContext).
Definition at line 178 of file LogicalParserListener.java.
void it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterGrammarHearder (GrammarHearderContext ctx)
This method just sets isInGrammarPreamble() to
true
before to call its super method: CAGGSyntaxDefinitionBaseListener#enterGrammarHearder(CAGGSyntaxDefinitionParser.GrammarHearderContext).
Definition at line 146 of file LogicalParserListener.java.
void it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterNuanceGrammar (NuanceGrammarContext ctx)
This method just sets isInGrammarRoot() to
true
before to call its super method: CAGGSyntaxDefinitionBaseListener#enterNuanceGrammar(CAGGSyntaxDefinitionParser.NuanceGrammarContext).
Definition at line 94 of file LogicalParserListener.java.
void it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterOrOperator (OrOperatorContext ctx)
This method set isOrOperation() to
true
if this node has at least a child node of type
orOperation
which, in turn, has a child that contains the or symbol (
"|"
). Otherwise, it set it to
false
. Then, it calls its super-method: enterOrOperator(CAGGSyntaxDefinitionParser.OrOperatorContext)
Definition at line 297 of file LogicalParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.getChildOfTypeOR(), it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.hasChildrenWithOrSymbol(), and it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.orOperation.
void it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterPreamble (PreambleContext ctx)
This method just sets isInGrammarPreamble() to
true
before to call its super method: CAGGSyntaxDefinitionBaseListener#enterPreamble(CAGGSyntaxDefinitionParser.PreambleContext).
Definition at line 128 of file LogicalParserListener.java.
void it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterRuleBody (RuleBodyContext ctx)
This method just sets isInRuleBody() to
true
before to call its super method: CAGGSyntaxDefinitionBaseListener#enterRuleBody(CAGGSyntaxDefinitionParser.RuleBodyContext).
Definition at line 263 of file LogicalParserListener.java.
void it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterRuleDeclaration (RuleDeclarationContext ctx)
This method sets the flags: isInRuleDeclarationBody() and isInRuleDeclarationPreamble(). In particular, it sets
inRuleDeclarationPreamble = true
and
inRuleDeclarationBody = false
if isInGrammarPreamble() returns
true
. Otherwise it sets
inRuleDeclarationPreamble = false
and
inRuleDeclarationBody = true
if isInGrammarBody() returns
true
. Otherwise it logs a warning message. Afetr this procedure this method calls its super-method:
#enterRuleDeclaration(RuleDeclarationContext)
.
Definition at line 224 of file LogicalParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isInGrammarBody(), and it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isInGrammarPreamble().
void it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterRuleTerm (RuleTermContext ctx)
This method set isRuleTerm() to
true
if this node has no children of type
ruleExpression
or
ruleDirective
. Otherwise, it set it to
false
. Then, it calls its super-method: enterRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext)
Definition at line 353 of file LogicalParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.getChildOfTypeDirective(), it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.getChildOfTypeExpression(), and it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.ruleTerm.
void it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.exitBody (BodyContext ctx)
This method just resets isInGrammarBody() to
false
before to call its super method: CAGGSyntaxDefinitionBaseListener#exitBody(CAGGSyntaxDefinitionParser.BodyContext).
Definition at line 187 of file LogicalParserListener.java.
void it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.exitGrammarHearder (GrammarHearderContext ctx)
This method just resets isInGrammarPreamble() to
false
before to call its super method: CAGGSyntaxDefinitionBaseListener#exitGrammarHearder(CAGGSyntaxDefinitionParser.GrammarHearderContext).
Definition at line 155 of file LogicalParserListener.java.
void it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.exitNuanceGrammar (NuanceGrammarContext ctx)
This method just resets isInGrammarRoot() to
false
before to call its super method: CAGGSyntaxDefinitionBaseListener#exitNuanceGrammar(CAGGSyntaxDefinitionParser.NuanceGrammarContext).
Definition at line 103 of file LogicalParserListener.java.
void it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.exitPreamble (PreambleContext ctx)
This method just resets isInGrammarPreamble() to
false
before to call its super method: CAGGSyntaxDefinitionBaseListener#exitPreamble(CAGGSyntaxDefinitionParser.PreambleContext).
Definition at line 137 of file LogicalParserListener.java.
void it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.exitRuleBody (RuleBodyContext ctx)
This method just resets isInRuleBody() to
false
before to call its super method: CAGGSyntaxDefinitionBaseListener#exitRuleBody(CAGGSyntaxDefinitionParser.RuleBodyContext).
Definition at line 272 of file LogicalParserListener.java.
void it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.exitRuleDeclaration (RuleDeclarationContext ctx)
This method just resets isInRuleDeclarationPreamble() and isInRuleDeclarationBody() to
false
before to call its super method: CAGGSyntaxDefinitionBaseListener#exitBody(CAGGSyntaxDefinitionParser.BodyContext).
Definition at line 239 of file LogicalParserListener.java.
List< ParseTree> it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.getChildOfTypeAND (ParseTree node) protected
This method returns all the node of type
ondOperator
that are children of the input parameter.
Parameters
node the PT node from which looking for
andOperator
children.
Returns
the list of children of
node
that are of type
andOperator
. Empty list if none.
Definition at line 387 of file LogicalParserListener.java.
Referenced by it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterAndOperator().
List<ParseTree> it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.getChildOfTypeDirective (ParseTree node) protected
This method returns all the node of type
ruleDirective
that are children of the input parameter.
Parameters
node the PT node from which looking for
ruleDirective
children.
Returns
the list of children of
node
that are of type
ruleDirective
. Empty list if none.
Definition at line 423 of file LogicalParserListener.java.
Referenced by it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterRuleTerm().
List<ParseTree> it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.getChildOfTypeExpression (ParseTree node) protected
This method returns all the node of type
ruleExpression
that are children of the input parameter.
Parameters
node the PT node from which looking for
ruleExpression
children.
Returns
the list of children of
node
that are of type
ruleExpression
. Empty list if none.
Definition at line 411 of file LogicalParserListener.java.
Referenced by it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterRuleTerm().
List< ParseTree> it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.getChildOfTypeOR (ParseTree node) protected
This method returns all the node of type
orOperator
that are children of the input parameter.
Parameters
node the PT node from which looking for
orOperator
children.
Returns
the list of children of
node
that are of type
orOperator
. Empty list if none.
Definition at line 375 of file LogicalParserListener.java.
Referenced by it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterOrOperator().
List< ParseTree> it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.getChildOfTypeTerm (ParseTree node) protected
This method returns all the node of type
ruleTerm
that are children of the input parameter.
Parameters
node the PT node from which looking for
ruleTerm
children.
Returns
the list of children of
node
that are of type
ruleTerm
. Empty list if none.
Definition at line 399 of file LogicalParserListener.java.
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.hasChildrenWithOrSymbol (ParseTree orChild) protected
This method just calls and returns the results of: hasChildrenWithOrSymbol(ParseTree) with:
orChild
and
"|"
; as input parameter respectively.
Parameters
orChild the
node
from which check if its children have at least a child which text is equals to
symbol
.
Returns
true
if the input
orNode
has at least a child which have a child with text equals to
"|"
.
Definition at line 504 of file LogicalParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.hasChildrenWithSymbol().
Referenced by it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterOrOperator().
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.hasChildrenWithSymbol (ParseTree orChild, String symbol) protected
This method returns true if the input parameter has a child which have at least a child which text is equals to
symbol
. It returns
false
otherwise.
Parameters
orChild the
node
from which check if its children have at least a child which text is equals to
symbol
.
symbol the string to identify specific sub children by comparing it with its text (retrieved through: ParseTree#getText()).
Returns
true
if the input
orNode
has at least a child which have a child with text equals to
symbol
.
Definition at line 491 of file LogicalParserListener.java.
Referenced by it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.hasChildrenWithOrSymbol().
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.hasChildWith0Children (ParseTree node) protected
This method simple calls: hasChildWithXChildren(ParseTree, int) with
node
and
0
input parameters respectively.
Parameters
node the PT node from which get child of which check if the number of children is equal to
0
.
Returns
true
if the input
node
has at least a child which have
0
children.
false
otherwise.
Definition at line 452 of file LogicalParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.hasChildWithXChildren().
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.hasChildWith1Children (ParseTree node) protected
This method simple calls: hasChildWithXChildren(ParseTree, int) with
node
and
1
input parameters respectively.
Parameters
node the PT node from which get child of which check if the number of children is equal to
1
.
Returns
true
if the input
node
has at least a child which have
1
child.
false
otherwise.
Definition at line 461 of file LogicalParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.hasChildWithXChildren().
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.hasChildWith2Children (ParseTree node) protected
This method simple calls: hasChildWithXChildren(ParseTree, int) with
node
and
2
input parameters respectively.
Parameters
node the PT node from which get child of which check if the number of children is equal to
2
.
Returns
true
if the input
node
has at least a child which have
2
children.
false
otherwise.
Definition at line 470 of file LogicalParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.hasChildWithXChildren().
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.hasChildWith3Children (ParseTree node) protected
This method simple calls: hasChildWithXChildren(ParseTree, int) with
node
and
3
input parameters respectively.
Parameters
node the PT node from which get child of which check if the number of children is equal to
3
.
Returns
true
if the input
node
has at least a child which have
3
children.
false
otherwise.
Definition at line 479 of file LogicalParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.hasChildWithXChildren().
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.hasChildWithXChildren (ParseTree node, int X) protected
This method returns
true
if the input parameter
node
has at least a child with a number of children (sub-child) equal to
X
.
Parameters
node the PT node from which get child of which check if the number of children is equal to
X
.
X the number of children that at least one child of the input
node
must have to return a positive boolean.
Returns
true
if the input
node
has at least a child which have
X
children.
false
otherwise.
Definition at line 440 of file LogicalParserListener.java.
Referenced by it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.hasChildWith0Children(), it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.hasChildWith1Children(), it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.hasChildWith2Children(), and it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.hasChildWith3Children().
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isAndOperation ()
This method returns
true
if the walking through the PT state indicates that the actual parsing node indicates an AND operator in an ET.
false
otherwise.
Returns
true
if the parsing walk state is inside an actual AND operation node in an ET.
false
otherwise.
See Also
enterAndOperator(CAGGSyntaxDefinitionParser.AndOperatorContext)
Definition at line 316 of file LogicalParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.andOperation.
Referenced by it.emarolab.cagg.core.language.parser.ParserListener.enterAndOperator().
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isInGrammarBody ()
This method returns
true
if the walking through the PT state indicates that the actual parsing node are inside the AST body node.
false
otherwise.
Returns
true
if the parsing walk state is inside the AST grammar body node.
false
otherwise.
See Also
enterBody(CAGGSyntaxDefinitionParser.BodyContext)
exitBody(CAGGSyntaxDefinitionParser.BodyContext)
Definition at line 170 of file LogicalParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.inGrammarBody.
Referenced by it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.addNode(), and it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterRuleDeclaration().
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isInGrammarPreamble ()
This method returns
true
if the walking through the PT state indicates that the actual parsing node are inside the AST preamble node. This
false
otherwise.
Returns
true
if the parsing walk state is inside the AST grammar preamble node.
false
otherwise.
See Also
enterPreamble(CAGGSyntaxDefinitionParser.PreambleContext)
exitPreamble(CAGGSyntaxDefinitionParser.PreambleContext)
enterGrammarHearder(CAGGSyntaxDefinitionParser.GrammarHearderContext)
exitGrammarHearder(CAGGSyntaxDefinitionParser.GrammarHearderContext)
Definition at line 120 of file LogicalParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.inGrammarPreamble.
Referenced by it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.addNode(), and it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterRuleDeclaration().
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isInGrammarRoot ()
This method returns
true
if the walking through the PT state indicates that the actual parsing node are inside the AST root node.
false
otherwise.
Returns
true
if the parsing walk state is inside the AST grammar root node.
false
otherwise.
See Also
enterNuanceGrammar(CAGGSyntaxDefinitionParser.NuanceGrammarContext)
exitNuanceGrammar(CAGGSyntaxDefinitionParser.NuanceGrammarContext)
Definition at line 86 of file LogicalParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.inGrammarRoot.
Referenced by it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.addNode().
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isInRuleBody ()
This method returns
true
if the walking through the PT state indicates that the actual parsing node are inside a Rule Body node.
false
otherwise.
Returns
true
if the parsing walk state is inside a PT Rule Body node.
false
otherwise.
See Also
enterRuleBody(CAGGSyntaxDefinitionParser.RuleBodyContext)
exitRuleBody(CAGGSyntaxDefinitionParser.RuleBodyContext)
Definition at line 255 of file LogicalParserListener.java.
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isInRuleDeclarationBody ()
This method returns
true
if the walking through the PT state indicates that the actual parsing node is a Rule Declaration node into the the AST body.
false
otherwise.
Returns
true
if the parsing walk state is a Rule Declaration inside the AST grammar body node.
false
otherwise.
See Also
enterRuleDeclaration(CAGGSyntaxDefinitionParser.RuleDeclarationContext)
exitRuleDeclaration(CAGGSyntaxDefinitionParser.RuleDeclarationContext)
Definition at line 212 of file LogicalParserListener.java.
Referenced by it.emarolab.cagg.core.language.parser.ParserListener.enterRuleDeclaration().
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isInRuleDeclarationPreamble ()
This method returns
true
if the walking through the PT state indicates that the actual parsing node is a Rule Declaration node into the the AST preamble.
false
otherwise.
Returns
true
if the parsing walk state is a Rule Declaration inside the AST grammar preamble node.
false
otherwise.
See Also
enterRuleDeclaration(CAGGSyntaxDefinitionParser.RuleDeclarationContext)
exitRuleDeclaration(CAGGSyntaxDefinitionParser.RuleDeclarationContext)
Definition at line 202 of file LogicalParserListener.java.
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isOrOperation ()
This method returns
true
if the walking through the PT state indicates that the actual parsing node indicates an OR operator in an ET.
false
otherwise.
Returns
true
if the parsing walk state is inside an actual OR operation node in an ET.
false
otherwise.
See Also
enterOrOperator(CAGGSyntaxDefinitionParser.OrOperatorContext)
Definition at line 288 of file LogicalParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.orOperation.
Referenced by it.emarolab.cagg.core.language.parser.ParserListener.enterOrOperator().
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isRuleTerm ()
This method returns
true
if the walking through the PT state indicates that the actual parsing node indicates an expression Term in an ET.
false
otherwise.
Returns
true
if the parsing walk state is inside an actual Term expression node in an ET.
false
otherwise.
See Also
enterRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext)
Definition at line 343 of file LogicalParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.ruleTerm.
Referenced by it.emarolab.cagg.core.language.parser.ParserListener.enterRuleTerm().
Member Data Documentation
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.andOperation = false private
Definition at line 59 of file LogicalParserListener.java.
Referenced by it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterAndOperator(), and it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isAndOperation().
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.inGrammarBody = false private
Definition at line 55 of file LogicalParserListener.java.
Referenced by it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isInGrammarBody().
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.inGrammarPreamble = false private
Definition at line 54 of file LogicalParserListener.java.
Referenced by it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isInGrammarPreamble().
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.inGrammarRoot = false private
Definition at line 53 of file LogicalParserListener.java.
Referenced by it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isInGrammarRoot().
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.inRuleBody = false private
Definition at line 57 of file LogicalParserListener.java.
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.inRuleDeclarationPreamble = false private
Definition at line 56 of file LogicalParserListener.java.
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.orOperation = false private
Definition at line 58 of file LogicalParserListener.java.
Referenced by it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterOrOperator(), and it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isOrOperation().
Boolean it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.ruleTerm = false private
Definition at line 60 of file LogicalParserListener.java.
Referenced by it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.enterRuleTerm(), and it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isRuleTerm().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/language/parser/ANTLRInterface/LogicalParserListener.java