ConceptActionGrammarGenerator: it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive Class Reference
it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive Class Reference
Public Member Functions
EvaluatingInfoPrimitive (SolutionType type, String info)
EvaluatingInfoPrimitive (SolutionType type)
EvaluatingInfoPrimitive (String info)
EvaluatingInfoPrimitive ()
void appendInfo (Object appendix)
void appendInfoLn (String appendix)
void setSolutionType (SolutionType type)
Long getCreationTimeStamp ()
Float getCreationTimeInterval (Long instant)
Float getCreationTimeInterval ()
String getFormattedDate ()
String getUnispaceIndex (String index)
String format ()
String format (Long previousStamp)
void addHearder ()
void addFeasibleHearder ()
void addUnfeasibleHearder (int size)
void addUnerasonableHearder (int size)
String toString ()
String getRawInfo ()
SolutionType getType ()
Static Public Member Functions
static void setEvaluationInitalInstant ()
Static Public Attributes
static final Integer SECOND_RESOLUTION = 15
static final Integer INDEX_RESOLUTION = 5
Private Member Functions
String getUnispaceZeroSeconds ()
String getUnispaceSeconds (String seconds)
String getUnispace (String msg, int numberOfChar)
String parseFeasible (Long previousStamp)
Private Attributes
Long creatingTime
String info
SolutionType type
Static Private Attributes
static Long initialTime
Detailed Description
Definition at line 91 of file GuiEvaluationInterface.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.EvaluatingInfoPrimitive (SolutionType type, String info)
Definition at line 105 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.info, and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.type.
it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.EvaluatingInfoPrimitive (SolutionType type)
Definition at line 110 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.type.
it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.EvaluatingInfoPrimitive (String info)
Definition at line 115 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.info.
it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.EvaluatingInfoPrimitive ()
Definition at line 119 of file GuiEvaluationInterface.java.
Member Function Documentation
void it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.addFeasibleHearder ()
Definition at line 207 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.appendInfoLn(), it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.SolutionType.HEADER, and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.type.
void it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.addHearder ()
Definition at line 194 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.appendInfoLn(), it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.SolutionType.HEADER, and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.type.
void it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.addUnerasonableHearder (int size)
Definition at line 251 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.appendInfoLn(), it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.SolutionType.HEADER, and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.type.
void it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.addUnfeasibleHearder (int size)
Definition at line 231 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.appendInfoLn(), it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.SolutionType.HEADER, and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.type.
void it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.appendInfo (Object appendix)
Definition at line 124 of file GuiEvaluationInterface.java.
void it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.appendInfoLn (String appendix)
Definition at line 127 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.debugging.DebuggingDefaults.SYS_LINE_SEPARATOR.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.addFeasibleHearder(), it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.addHearder(), it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.addUnerasonableHearder(), and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.addUnfeasibleHearder().
String it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.format ()
Definition at line 173 of file GuiEvaluationInterface.java.
String it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.format (Long previousStamp)
Definition at line 176 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getRawInfo(), it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getType(), and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.parseFeasible().
Float it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getCreationTimeInterval (Long instant)
Definition at line 138 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.creatingTime, and it.emarolab.cagg.debugging.DebuggingDefaults.NANOSEC_2_SEC.
Float it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getCreationTimeInterval ()
Definition at line 144 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.initialTime.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.parseFeasible().
Long it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getCreationTimeStamp ()
Definition at line 135 of file GuiEvaluationInterface.java.
String it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getFormattedDate ()
Definition at line 148 of file GuiEvaluationInterface.java.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.toString().
String it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getRawInfo ()
Definition at line 275 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.info.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.format(), it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.parseFeasible(), and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.toString().
SolutionType it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getType ()
Definition at line 278 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.type.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.format().
String it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getUnispace (String msg, int numberOfChar) private
Definition at line 162 of file GuiEvaluationInterface.java.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getUnispaceIndex(), it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getUnispaceSeconds(), and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getUnispaceZeroSeconds().
String it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getUnispaceIndex (String index)
Definition at line 158 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getUnispace(), and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.INDEX_RESOLUTION.
String it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getUnispaceSeconds (String seconds) private
Definition at line 154 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getUnispace(), and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.SECOND_RESOLUTION.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.parseFeasible().
String it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getUnispaceZeroSeconds () private
Definition at line 151 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getUnispace(), and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.SECOND_RESOLUTION.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.parseFeasible().
String it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.parseFeasible (Long previousStamp) private
Definition at line 186 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getCreationTimeInterval(), it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getRawInfo(), it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getUnispaceSeconds(), it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getUnispaceZeroSeconds(), and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.toString().
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.format().
static void it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.setEvaluationInitalInstant () static
Definition at line 97 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.initialTime.
void it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.setSolutionType (SolutionType type)
Definition at line 131 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.type.
String it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.toString ()
Definition at line 272 of file GuiEvaluationInterface.java.
References it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getFormattedDate(), and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getRawInfo().
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.parseFeasible().
Member Data Documentation
Long it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.creatingTime private
Definition at line 101 of file GuiEvaluationInterface.java.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getCreationTimeInterval().
final Integer it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.INDEX_RESOLUTION = 5 static
Definition at line 94 of file GuiEvaluationInterface.java.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getUnispaceIndex().
String it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.info private
Definition at line 102 of file GuiEvaluationInterface.java.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.EvaluatingInfoPrimitive(), and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getRawInfo().
Long it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.initialTime static private
Definition at line 96 of file GuiEvaluationInterface.java.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getCreationTimeInterval(), and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.setEvaluationInitalInstant().
final Integer it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.SECOND_RESOLUTION = 15 static
Definition at line 93 of file GuiEvaluationInterface.java.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getUnispaceSeconds(), and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getUnispaceZeroSeconds().
SolutionType it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.type private
Definition at line 103 of file GuiEvaluationInterface.java.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.addFeasibleHearder(), it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.addHearder(), it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.addUnerasonableHearder(), it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.addUnfeasibleHearder(), it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.EvaluatingInfoPrimitive(), it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.getType(), and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.EvaluatingInfoPrimitive.setSolutionType().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/evaluation/interfacing/GuiEvaluationInterface.java