ConceptActionGrammarGenerator: it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryWalker Class Reference
it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryWalker Class Reference abstract
Public Member Functions
PseudoBinaryWalker (PseudoBinaryNode root)
PseudoBinaryWalker (PseudoBinaryNode root, Boolean verbose)
PseudoBinaryWalker (PseudoBinaryNode root, Boolean verbose, String walkerName)
void walkLeftFirst ()
void walkRightFirst ()
void walkPseudoBynary (Boolean useLeft)
void walkDepthFirst ()
PseudoBinaryNode getRoot ()
abstract Boolean enterNode (BaseNode node)
abstract void exitNode (BaseNode node)
Protected Member Functions
void walkForAll (BaseNode node)
Private Attributes
Boolean useLeft
Detailed Description
Definition at line 634 of file PseudoBinaryNode.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryWalker.PseudoBinaryWalker (PseudoBinaryNode root)
Definition at line 638 of file PseudoBinaryNode.java.
it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryWalker.PseudoBinaryWalker (PseudoBinaryNode root, Boolean verbose)
Definition at line 641 of file PseudoBinaryNode.java.
it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryWalker.PseudoBinaryWalker (PseudoBinaryNode root, Boolean verbose, String walkerName)
Definition at line 644 of file PseudoBinaryNode.java.
Member Function Documentation
abstract Boolean it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryWalker.enterNode (BaseNode node) abstract
abstract void it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryWalker.exitNode (BaseNode node) abstract
PseudoBinaryNode it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryWalker.getRoot ()
Definition at line 675 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryWalker.walkDepthFirst ()
Definition at line 667 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryWalker.walkForAll (BaseNode node) protected
Definition at line 680 of file PseudoBinaryNode.java.
References it.emarolab.cagg.core.PseudoBinaryNode.getLeftChild(), it.emarolab.cagg.core.PseudoBinaryNode.getRightChild(), it.emarolab.cagg.core.PseudoBinaryNode.hasLeftChild(), and it.emarolab.cagg.core.PseudoBinaryNode.hasRightChild().
void it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryWalker.walkLeftFirst ()
Definition at line 648 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryWalker.walkPseudoBynary (Boolean useLeft)
Definition at line 660 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryWalker.walkRightFirst ()
Definition at line 654 of file PseudoBinaryNode.java.
Member Data Documentation
Boolean it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryWalker.useLeft private
Definition at line 636 of file PseudoBinaryNode.java.
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/PseudoBinaryNode.java