ConceptActionGrammarGenerator: it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase Class Reference
it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase Class Reference abstract
Public Member Functions
GrammarTesterBase (String grammarPath)
GrammarTesterBase (String grammarPath, Float timeOutSec)
GrammarTesterBase (GrammarBase< ?extends SemanticExpressionTreeBase > grammar)
GrammarTesterBase (GrammarBase< ?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
GrammarTesterBase (String evaluatorLoggerName, String formatterLoggerName, String grammarPath)
GrammarTesterBase (String evaluatorLoggerName, String formatterLoggerName, String grammarPath, Float timeOutSec)
GrammarTesterBase (String evaluatorLoggerName, String formatterLoggerName, GrammarBase< ?extends SemanticExpressionTreeBase > grammar)
GrammarTesterBase (String evaluatorLoggerName, String formatterLoggerName, GrammarBase< ?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
GrammarBase< ?extends
SemanticExpressionTreeBase > getGrammar ()
TimeOutedEvaluatorBase getEvaluator ()
ThreadedInputFormatter getFormatter ()
boolean isTestingLastCommand ()
void resetLastCommand ()
Float getTestingTime ()
void setTestingTime ()
synchronized Float getRangeFromTestingStart ()
synchronized String getEvaluatorLoggerName ()
String getFormatterLoggerName ()
synchronized void test (List< String > commands)
synchronized void test (String command)
synchronized void test (String command, int testIdx)
abstract void willEvaluateCommand (String command, int testIdx)
abstract void didEvaluateCommand (String command, int testIdx)
Protected Member Functions
abstract ThreadedInputFormatter getNewFormatter (String loggerName, GrammarBase< ?extends SemanticExpressionTreeBase > grammar)
abstract TimeOutedEvaluatorBase getNewEvaluator (String loggerName, ThreadedInputFormatter formatter, Float timeOutSec)
TimeOutedEvaluatorBase getNewEvaluator (TimeOutedEvaluatorBase eval)
void performTest (String command, int testIdx)
Private Member Functions
GrammarBase< ?extends
SemanticExpressionTreeBase > loadGrammar (String grammarFilePath)
initialisation methods used from constructors
void initialise (String evaluatorLoggerName, String formatterLoggerName, GrammarBase< ?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
Private Attributes
GrammarBase< ?extends
SemanticExpressionTreeBase > grammar
TimeOutedEvaluatorBase evaluator
ThreadedInputFormatter formatter
boolean isTestingLastCommand = false
Long testStartingTimeStamp
Float testingTime
String evaluationLoggerName
Detailed Description
Definition at line 13 of file GrammarTesterBase.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.GrammarTesterBase (String grammarPath)
Definition at line 29 of file GrammarTesterBase.java.
References it.emarolab.cagg.core.evaluation.interfacing.TimeOutedEvaluatorBase.DEFAULT_EVALUATION_TIME_OUT_SEC, it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_EVALUATOR, it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_FORMATTER, it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.initialise(), and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.loadGrammar().
it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.GrammarTesterBase (String grammarPath, Float timeOutSec)
Definition at line 33 of file GrammarTesterBase.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_EVALUATOR, it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_FORMATTER, it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.initialise(), and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.loadGrammar().
it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.GrammarTesterBase (GrammarBase< ?extends SemanticExpressionTreeBase > grammar)
Definition at line 37 of file GrammarTesterBase.java.
References it.emarolab.cagg.core.evaluation.interfacing.TimeOutedEvaluatorBase.DEFAULT_EVALUATION_TIME_OUT_SEC, it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_EVALUATOR, it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_FORMATTER, and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.initialise().
it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.GrammarTesterBase (GrammarBase< ?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
Definition at line 41 of file GrammarTesterBase.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_EVALUATOR, it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_FORMATTER, and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.initialise().
it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.GrammarTesterBase (String evaluatorLoggerName, String formatterLoggerName, String grammarPath)
Definition at line 45 of file GrammarTesterBase.java.
References it.emarolab.cagg.core.evaluation.interfacing.TimeOutedEvaluatorBase.DEFAULT_EVALUATION_TIME_OUT_SEC, it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.initialise(), and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.loadGrammar().
it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.GrammarTesterBase (String evaluatorLoggerName, String formatterLoggerName, String grammarPath, Float timeOutSec)
Definition at line 49 of file GrammarTesterBase.java.
References it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.initialise(), and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.loadGrammar().
it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.GrammarTesterBase (String evaluatorLoggerName, String formatterLoggerName, GrammarBase< ?extends SemanticExpressionTreeBase > grammar)
Definition at line 52 of file GrammarTesterBase.java.
References it.emarolab.cagg.core.evaluation.interfacing.TimeOutedEvaluatorBase.DEFAULT_EVALUATION_TIME_OUT_SEC, and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.initialise().
it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.GrammarTesterBase (String evaluatorLoggerName, String formatterLoggerName, GrammarBase< ?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
Definition at line 55 of file GrammarTesterBase.java.
References it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.initialise().
Member Function Documentation
abstract void it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.didEvaluateCommand (String command, int testIdx) abstract
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.performTest().
TimeOutedEvaluatorBase it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getEvaluator ()
Definition at line 89 of file GrammarTesterBase.java.
References it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.evaluator.
synchronized String it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getEvaluatorLoggerName ()
Definition at line 110 of file GrammarTesterBase.java.
References it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.evaluationLoggerName.
ThreadedInputFormatter it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getFormatter ()
Definition at line 92 of file GrammarTesterBase.java.
References it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.formatter.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.didEvaluateCommand().
String it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getFormatterLoggerName ()
Definition at line 113 of file GrammarTesterBase.java.
GrammarBase< ? extends SemanticExpressionTreeBase> it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getGrammar ()
Definition at line 86 of file GrammarTesterBase.java.
References it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.grammar.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.didEvaluateCommand(), and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.willEvaluateCommand().
abstract TimeOutedEvaluatorBase it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getNewEvaluator (String loggerName, ThreadedInputFormatter formatter, Float timeOutSec) abstract protected
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getNewEvaluator(), it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.initialise(), and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.performTest().
TimeOutedEvaluatorBase it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getNewEvaluator (TimeOutedEvaluatorBase eval) protected
Definition at line 79 of file GrammarTesterBase.java.
References it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getNewEvaluator(), and it.emarolab.cagg.core.evaluation.interfacing.TimeOutedEvaluatorBase.getTimeOutSecRange().
abstract ThreadedInputFormatter it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getNewFormatter (String loggerName, GrammarBase< ?extends SemanticExpressionTreeBase > grammar) abstract protected
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.initialise().
synchronized Float it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getRangeFromTestingStart ()
Definition at line 107 of file GrammarTesterBase.java.
References it.emarolab.cagg.debugging.DebuggingDefaults.NANOSEC_2_SEC, and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.testStartingTimeStamp.
Referenced by it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.addTestMapFooter(), it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.updateTestMap(), and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.updateTestMap().
Float it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getTestingTime ()
Definition at line 101 of file GrammarTesterBase.java.
References it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.testingTime.
void it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.initialise (String evaluatorLoggerName, String formatterLoggerName, GrammarBase< ?extends SemanticExpressionTreeBase > grammar, Float timeOutSec) private
get the grammar first
store the formatter
store the evaluator
store the prefix log
Definition at line 65 of file GrammarTesterBase.java.
References it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.formatter, it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getNewEvaluator(), it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getNewFormatter(), and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.grammar.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.GrammarTesterBase().
boolean it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.isTestingLastCommand ()
Definition at line 95 of file GrammarTesterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.test(), it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.updateTestMap(), and it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.updateTestMap().
GrammarBase< ? extends SemanticExpressionTreeBase> it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.loadGrammar (String grammarFilePath) private
initialisation methods used from constructors
Definition at line 59 of file GrammarTesterBase.java.
References it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.grammar.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.GrammarTesterBase().
void it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.performTest (String command, int testIdx) protected
Definition at line 137 of file GrammarTesterBase.java.
References it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.didEvaluateCommand(), it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.evaluator, it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getNewEvaluator(), it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.resetLastCommand(), it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.setTestingTime(), and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.willEvaluateCommand().
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.test().
void it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.resetLastCommand ()
Definition at line 98 of file GrammarTesterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.performTest().
void it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.setTestingTime ()
Definition at line 104 of file GrammarTesterBase.java.
References it.emarolab.cagg.debugging.DebuggingDefaults.NANOSEC_2_SEC, it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.testingTime, and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.testStartingTimeStamp.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.performTest().
synchronized void it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.test (List< String > commands)
Definition at line 119 of file GrammarTesterBase.java.
References it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.isTestingLastCommand(), it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.performTest(), and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.testStartingTimeStamp.
Referenced by it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.run().
synchronized void it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.test (String command)
Definition at line 127 of file GrammarTesterBase.java.
References it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.performTest(), and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.testStartingTimeStamp.
synchronized void it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.test (String command, int testIdx)
Definition at line 132 of file GrammarTesterBase.java.
References it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.performTest(), and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.testStartingTimeStamp.
abstract void it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.willEvaluateCommand (String command, int testIdx) abstract
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.performTest().
Member Data Documentation
String it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.evaluationLoggerName private
Definition at line 24 of file GrammarTesterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getEvaluatorLoggerName().
TimeOutedEvaluatorBase it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.evaluator private
Definition at line 19 of file GrammarTesterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getEvaluator(), and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.performTest().
ThreadedInputFormatter it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.formatter private
Definition at line 20 of file GrammarTesterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getFormatter(), and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.initialise().
GrammarBase< ? extends SemanticExpressionTreeBase> it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.grammar private
Definition at line 18 of file GrammarTesterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getGrammar(), it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.initialise(), and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.loadGrammar().
boolean it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.isTestingLastCommand = false private
Definition at line 21 of file GrammarTesterBase.java.
Float it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.testingTime private
Definition at line 23 of file GrammarTesterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getTestingTime(), and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.setTestingTime().
Long it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.testStartingTimeStamp private
Definition at line 22 of file GrammarTesterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getRangeFromTestingStart(), it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.setTestingTime(), and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.test().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/evaluation/interfacing/GrammarTesterBase.java