ConceptActionGrammarGenerator: it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration Class Reference
it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration Class Reference
Public Member Functions
CaggMultiGrammarTesterConfiguration (String evaluatorLoggerName, String formatterLoggerName, String grammarPath)
CaggMultiGrammarTesterConfiguration (String testName, String evaluatorLoggerName, String formatterLoggerName, String grammarPath)
CaggMultiGrammarTesterConfiguration (String testName, String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar)
String getTestName ()
String getEvaluatorLoggerName ()
String getFormatterLoggerName ()
GrammarBase<?extends
SemanticExpressionTreeBase > getGrammar ()
Private Member Functions
GrammarBase< ?extends
SemanticExpressionTreeBase > loadGrammar (String grammarFilePath)
void initialise (String testName, String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar)
Private Attributes
String testName
String evaluatorLoggerName
GrammarBase<?extends
SemanticExpressionTreeBase > grammar
Detailed Description
Definition at line 10 of file CaggMultiGrammarTesterConfiguration.java.
Constructor & Destructor Documentation
it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.CaggMultiGrammarTesterConfiguration (String evaluatorLoggerName, String formatterLoggerName, String grammarPath)
Definition at line 21 of file CaggMultiGrammarTesterConfiguration.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.DEFAULT_TEST_NAME, it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.initialise(), and it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.loadGrammar().
it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.CaggMultiGrammarTesterConfiguration (String testName, String evaluatorLoggerName, String formatterLoggerName, String grammarPath)
Definition at line 24 of file CaggMultiGrammarTesterConfiguration.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.initialise(), and it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.loadGrammar().
it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.CaggMultiGrammarTesterConfiguration (String testName, String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar)
Definition at line 27 of file CaggMultiGrammarTesterConfiguration.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.initialise().
Member Function Documentation
String it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.getEvaluatorLoggerName ()
Definition at line 52 of file CaggMultiGrammarTesterConfiguration.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.evaluatorLoggerName.
String it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.getFormatterLoggerName ()
Definition at line 55 of file CaggMultiGrammarTesterConfiguration.java.
GrammarBase<? extends SemanticExpressionTreeBase> it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.getGrammar ()
Definition at line 58 of file CaggMultiGrammarTesterConfiguration.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.grammar.
String it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.getTestName ()
Definition at line 49 of file CaggMultiGrammarTesterConfiguration.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.testName.
void it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.initialise (String testName, String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar) private
Definition at line 38 of file CaggMultiGrammarTesterConfiguration.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.evaluatorLoggerName, it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.grammar, and it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.testName.
Referenced by it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.CaggMultiGrammarTesterConfiguration().
GrammarBase< ? extends SemanticExpressionTreeBase> it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.loadGrammar (String grammarFilePath) private
Definition at line 31 of file CaggMultiGrammarTesterConfiguration.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.grammar.
Referenced by it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.CaggMultiGrammarTesterConfiguration().
Member Data Documentation
String it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.evaluatorLoggerName private
Definition at line 15 of file CaggMultiGrammarTesterConfiguration.java.
Referenced by it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.getEvaluatorLoggerName(), and it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.initialise().
GrammarBase<? extends SemanticExpressionTreeBase> it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.grammar private
Definition at line 16 of file CaggMultiGrammarTesterConfiguration.java.
Referenced by it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.getGrammar(), it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.initialise(), and it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.loadGrammar().
String it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.testName private
Definition at line 14 of file CaggMultiGrammarTesterConfiguration.java.
Referenced by it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.getTestName(), and it.emarolab.cagg.interfaces.CaggMultiGrammarTesterConfiguration.initialise().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/interfaces/CaggMultiGrammarTesterConfiguration.java