ConceptActionGrammarGenerator: it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator Class Reference
it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator Class Reference
Classes
class ExpressionQueues
Public Member Functions
ExpressionTreeGenerator ()
ExpressionNode<?> getExpressionTree ()
ExpressionQueues getExpressionQueses ()
void addOperation (ExpressionNode<?> e)
void addTerm (ExpressionNode<?> e)
Static Public Attributes
static final Integer PENDING_ERROR = -1
static final Integer PENDING_NO = 0
static final Integer PENDING_OPERATION = 1
static final Integer PENDING_TERM = 2
Private Member Functions
void updateExpressionTree (ExpressionQueues queues)
ExpressionNode<?> getExpressionTreeRoot (ExpressionQueues queues)
void addExpressionOperationNode (ExpressionNode<?> treeState, ExpressionNode<?> toAdd)
void addExpressionTermNode (ExpressionNode<?> treeState, ExpressionNode<?> toAdd)
Private Attributes
ExpressionNode<?> expressionRoot
ExpressionNode<?> expressionNodeState
ExpressionQueues queues
Detailed Description
Version
Concept-Action Grammar Generator 1.1
File: src//cagg.core.sourceInterface.grammar.expressionTree.ExpressionTreeGenerator.java
Author
Buoncompagni Luca
DIBRIS, emaroLab,
University of Genoa.
15/gen/2016
This class is used from it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener in order to create Expression Tree (ET) from a Parsing Tree (PT). Moreover, the created ET is suppose to be the node
data
of a Abstract Syntax Tree (AST).
The purpose of this class is to create an ET during parsing. In particular, it is possible to add operation when they are intercepted by the parser (enter rule) and than update the ET in order to generate it. More in details, by adding operation this class manage a set of
Queues
(implemented in ExpressionQueues). On the other hand, by updating the tree it pull informations for the queues in order to add them in the tree correctly.
See Also
ExpressionQueues
it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener
it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionNodeOld
it.emarolab.cagg.core.language.syntax.abstractTree.AbstractSyntaxNode
Definition at line 35 of file ExpressionTreeGenerator.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionTreeGenerator ()
Initialise this class by creating a new ET root, internal state variables and queues (ExpressionQueues).
Definition at line 72 of file ExpressionTreeGenerator.java.
References it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.expressionNodeState, it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.expressionRoot, and it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.queues.
Member Function Documentation
void it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.addExpressionOperationNode (ExpressionNode<?> treeState, ExpressionNode<?> toAdd) private
Definition at line 153 of file ExpressionTreeGenerator.java.
References it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.expressionNodeState.
Referenced by it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.updateExpressionTree().
void it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.addExpressionTermNode (ExpressionNode<?> treeState, ExpressionNode<?> toAdd) private
Definition at line 170 of file ExpressionTreeGenerator.java.
References it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.expressionNodeState.
Referenced by it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.updateExpressionTree().
void it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.addOperation (ExpressionNode<?> e)
This method introduce a new parsed operation node to the ExpressionQueues. Finally, it updates the ET with this new node by pulling data from the queues.
Parameters
e the operation node to be added to the ET.
Definition at line 101 of file ExpressionTreeGenerator.java.
References it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.queues, and it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.updateExpressionTree().
void it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.addTerm (ExpressionNode<?> e)
This method introduce a new parsed term node to the ExpressionQueues. Finally, it updates the ET with this new node by pulling data from the queues.
Parameters
e the term node to be added to the ET.
Definition at line 110 of file ExpressionTreeGenerator.java.
References it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.queues, and it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.updateExpressionTree().
ExpressionQueues it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.getExpressionQueses ()
Returns
the queues of the node to be added to the ET.
Definition at line 90 of file ExpressionTreeGenerator.java.
References it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.queues.
ExpressionNode<?> it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.getExpressionTree ()
Returns
the root of the generated ET.
Definition at line 84 of file ExpressionTreeGenerator.java.
References it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.expressionRoot.
ExpressionNode<?> it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.getExpressionTreeRoot (ExpressionQueues queues) private
Definition at line 142 of file ExpressionTreeGenerator.java.
References it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.hasOperatorPending(), it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.hasTermPending(), it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.operationPull(), and it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.termPull().
Referenced by it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.updateExpressionTree().
void it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.updateExpressionTree (ExpressionQueues queues) private
Definition at line 117 of file ExpressionTreeGenerator.java.
References it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.addExpressionOperationNode(), it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.addExpressionTermNode(), it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.expressionNodeState, it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.expressionRoot, it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.getExpressionTreeRoot(), it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.hasPending(), it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.operationPull(), it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.PENDING_NO, it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.PENDING_OPERATION, it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.PENDING_TERM, it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.queues, and it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.termPull().
Referenced by it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.addOperation(), and it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.addTerm().
Member Data Documentation
ExpressionNode<?> it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.expressionNodeState private
Definition at line 64 of file ExpressionTreeGenerator.java.
Referenced by it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.addExpressionOperationNode(), it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.addExpressionTermNode(), it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionTreeGenerator(), and it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.updateExpressionTree().
ExpressionNode<?> it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.expressionRoot private
Definition at line 63 of file ExpressionTreeGenerator.java.
Referenced by it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionTreeGenerator(), it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.getExpressionTree(), and it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.updateExpressionTree().
final Integer it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.PENDING_ERROR = -1 static
The constant tag value given from ExpressionQueues#hasPending() in case of error. Default value:
-1
.
Definition at line 44 of file ExpressionTreeGenerator.java.
Referenced by it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.hasPending().
final Integer it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.PENDING_NO = 0 static
The constant tag value given from ExpressionQueues#hasPending() in case of no action to be performed on tree creation. Default value:
0
.
Definition at line 49 of file ExpressionTreeGenerator.java.
Referenced by it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.hasPending(), and it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.updateExpressionTree().
final Integer it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.PENDING_OPERATION = 1 static
The constant tag value given from ExpressionQueues#hasPending() in case in which a operation node should be considered on tree creation. Default value:
1
.
Definition at line 54 of file ExpressionTreeGenerator.java.
Referenced by it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.hasPending(), and it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.updateExpressionTree().
final Integer it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.PENDING_TERM = 2 static
The constant tag value given from ExpressionQueues#hasPending() in case in which a term node should be considered on tree creation. Default value:
2
.
Definition at line 59 of file ExpressionTreeGenerator.java.
Referenced by it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.hasPending(), and it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.updateExpressionTree().
ExpressionQueues it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.queues private
Definition at line 65 of file ExpressionTreeGenerator.java.
Referenced by it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.addOperation(), it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.addTerm(), it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionTreeGenerator(), it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.getExpressionQueses(), and it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.updateExpressionTree().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/language/syntax/expressionTree/ExpressionTreeGenerator.java