ConceptActionGrammarGenerator: it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger Class Reference
it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger Class Reference
Public Member Functions
synchronized void info (Object msg)
synchronized void warning (Object msg)
synchronized void ok (Object msg)
synchronized void error (Object msg)
synchronized void error (Exception e)
Detailed Description
Definition at line 136 of file CaggThread.java.
Member Function Documentation
synchronized void it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger.error (Object msg)
Definition at line 152 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.getFormattedName(), it.emarolab.cagg.core.evaluation.CaggThread.getLoggingStepBack(), and it.emarolab.cagg.core.evaluation.CaggThread.loggerName.
synchronized void it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger.error (Exception e)
Definition at line 156 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.getFormattedName(), it.emarolab.cagg.core.evaluation.CaggThread.getLoggingStepBack(), and it.emarolab.cagg.core.evaluation.CaggThread.loggerName.
synchronized void it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger.info (Object msg)
Definition at line 140 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.getFormattedName(), it.emarolab.cagg.core.evaluation.CaggThread.getLoggingStepBack(), and it.emarolab.cagg.core.evaluation.CaggThread.loggerName.
synchronized void it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger.ok (Object msg)
Definition at line 148 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.getFormattedName(), it.emarolab.cagg.core.evaluation.CaggThread.getLoggingStepBack(), and it.emarolab.cagg.core.evaluation.CaggThread.loggerName.
synchronized void it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger.warning (Object msg)
Definition at line 144 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.getFormattedName(), it.emarolab.cagg.core.evaluation.CaggThread.getLoggingStepBack(), and it.emarolab.cagg.core.evaluation.CaggThread.loggerName.
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/evaluation/CaggThread.java