ConceptActionGrammarGenerator: it.emarolab.cagg.debugging.DebuggingText Class Reference
it.emarolab.cagg.debugging.DebuggingText Class Reference
Classes
class Log4j
class Logger
class LoggerBase
Public Member Functions
DebuggingText (String loggerName, String configurationPath)
String getConfigurationPath ()
String getLoggerName ()
LoggerBase getLogger ()
String toString ()
Static Public Member Functions
static void reconfigureLogger ()
static synchronized void printStackTrace ()
static String getFormattedDate ()
static String getFormattedDateMilli ()
static String getFormattedDate (String format)
static void appendOnFileLn (String filePath, String txt)
static void appendOnFile (String filePath, String txt)
static LoggerBase getLogger (String loggerName)
static void removeLogger (String loggerName)
Protected Member Functions
LoggerBase createLogger ()
void addLogger ()
void setConfigurationPath (String configurationPath)
void setLoggerName (String loggerName)
void setLogger (LoggerBase logger)
Static Protected Member Functions
static void addLogger (String loggerName, LoggerBase logger)
Private Member Functions
void initialise (String loggerName, String configurationPath)
Private Attributes
String loggerName
String configurationPath
LoggerBase logger
Static Private Attributes
static Map< String, LoggerBase > loggerMap = new HashMap<>()
Detailed Description
Definition at line 18 of file DebuggingText.java.
Constructor & Destructor Documentation
it.emarolab.cagg.debugging.DebuggingText.DebuggingText (String loggerName, String configurationPath)
Definition at line 30 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.initialise().
Member Function Documentation
void it.emarolab.cagg.debugging.DebuggingText.addLogger () protected
Definition at line 42 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.getLogger(), and it.emarolab.cagg.debugging.DebuggingText.getLoggerName().
Referenced by it.emarolab.cagg.debugging.DebuggingText.initialise().
static void it.emarolab.cagg.debugging.DebuggingText.addLogger (String loggerName, LoggerBase logger) static protected
Definition at line 116 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.logger, it.emarolab.cagg.debugging.DebuggingText.loggerMap, and it.emarolab.cagg.debugging.DebuggingText.loggerName.
static void it.emarolab.cagg.debugging.DebuggingText.appendOnFile (String filePath, String txt) static
Definition at line 95 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.appendOnFileLn().
static void it.emarolab.cagg.debugging.DebuggingText.appendOnFileLn (String filePath, String txt) static
Definition at line 92 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.appendOnFile(), and it.emarolab.cagg.debugging.DebuggingDefaults.SYS_LINE_SEPARATOR.
LoggerBase it.emarolab.cagg.debugging.DebuggingText.createLogger () protected
Definition at line 39 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.getConfigurationPath(), and it.emarolab.cagg.debugging.DebuggingText.getLoggerName().
Referenced by it.emarolab.cagg.debugging.DebuggingText.initialise().
String it.emarolab.cagg.debugging.DebuggingText.getConfigurationPath ()
Definition at line 52 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.configurationPath.
Referenced by it.emarolab.cagg.debugging.DebuggingText.createLogger().
static String it.emarolab.cagg.debugging.DebuggingText.getFormattedDate () static
Definition at line 79 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.getFormattedDateMilli(), and it.emarolab.cagg.debugging.CaggLoggersManager.setFilePath().
static String it.emarolab.cagg.debugging.DebuggingText.getFormattedDate (String format) static
Definition at line 85 of file DebuggingText.java.
static String it.emarolab.cagg.debugging.DebuggingText.getFormattedDateMilli () static
Definition at line 82 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.getFormattedDate().
LoggerBase it.emarolab.cagg.debugging.DebuggingText.getLogger ()
Definition at line 58 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.logger.
Referenced by it.emarolab.cagg.debugging.DebuggingText.addLogger().
static LoggerBase it.emarolab.cagg.debugging.DebuggingText.getLogger (String loggerName) static
Definition at line 121 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.loggerMap, and it.emarolab.cagg.debugging.DebuggingText.loggerName.
String it.emarolab.cagg.debugging.DebuggingText.getLoggerName ()
Definition at line 55 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.loggerName.
Referenced by it.emarolab.cagg.debugging.DebuggingText.addLogger(), and it.emarolab.cagg.debugging.DebuggingText.createLogger().
void it.emarolab.cagg.debugging.DebuggingText.initialise (String loggerName, String configurationPath) private
Definition at line 33 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.addLogger(), it.emarolab.cagg.debugging.DebuggingText.createLogger(), it.emarolab.cagg.debugging.DebuggingText.setConfigurationPath(), it.emarolab.cagg.debugging.DebuggingText.setLogger(), and it.emarolab.cagg.debugging.DebuggingText.setLoggerName().
Referenced by it.emarolab.cagg.debugging.DebuggingText.DebuggingText().
static synchronized void it.emarolab.cagg.debugging.DebuggingText.printStackTrace () static
Definition at line 75 of file DebuggingText.java.
static void it.emarolab.cagg.debugging.DebuggingText.reconfigureLogger () static
Definition at line 45 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.error(), it.emarolab.cagg.debugging.DebuggingText.Log4j.info(), it.emarolab.cagg.debugging.DebuggingText.Log4j.ok(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.warning().
static void it.emarolab.cagg.debugging.DebuggingText.removeLogger (String loggerName) static
Definition at line 126 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.loggerName.
void it.emarolab.cagg.debugging.DebuggingText.setConfigurationPath (String configurationPath) protected
Definition at line 61 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.configurationPath.
Referenced by it.emarolab.cagg.debugging.DebuggingText.initialise().
void it.emarolab.cagg.debugging.DebuggingText.setLogger (LoggerBase logger) protected
Definition at line 67 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.logger.
Referenced by it.emarolab.cagg.debugging.DebuggingText.initialise().
void it.emarolab.cagg.debugging.DebuggingText.setLoggerName (String loggerName) protected
Definition at line 64 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.loggerName.
Referenced by it.emarolab.cagg.debugging.DebuggingText.initialise().
String it.emarolab.cagg.debugging.DebuggingText.toString ()
Definition at line 495 of file DebuggingText.java.
References it.emarolab.cagg.debugging.DebuggingText.loggerMap.
Member Data Documentation
String it.emarolab.cagg.debugging.DebuggingText.configurationPath private
Definition at line 24 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.getConfigurationPath(), and it.emarolab.cagg.debugging.DebuggingText.setConfigurationPath().
LoggerBase it.emarolab.cagg.debugging.DebuggingText.logger private
Definition at line 25 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.addLogger(), it.emarolab.cagg.debugging.DebuggingText.getLogger(), and it.emarolab.cagg.debugging.DebuggingText.setLogger().
Map< String, LoggerBase> it.emarolab.cagg.debugging.DebuggingText.loggerMap = new HashMap<>() static private
Definition at line 114 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.addLogger(), it.emarolab.cagg.debugging.DebuggingText.getLogger(), and it.emarolab.cagg.debugging.DebuggingText.toString().
String it.emarolab.cagg.debugging.DebuggingText.loggerName private
Definition at line 23 of file DebuggingText.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.addLogger(), it.emarolab.cagg.debugging.DebuggingText.getLogger(), it.emarolab.cagg.debugging.DebuggingText.getLoggerName(), it.emarolab.cagg.debugging.DebuggingText.Log4j.Log4j(), it.emarolab.cagg.debugging.DebuggingText.removeLogger(), and it.emarolab.cagg.debugging.DebuggingText.setLoggerName().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/debugging/DebuggingText.java