ConceptActionGrammarGenerator: it.emarolab.cagg.core.evaluation.CaggThread Class Reference
it.emarolab.cagg.core.evaluation.CaggThread Class Reference abstract
Classes
class ThreadLogger
Public Member Functions
CaggThread ()
CaggThread (String name)
CaggThread (String name, String loggerName)
synchronized void setThreadName (String threadName)
synchronized void setRunnableId (Long runnableId)
synchronized void setLoggerName (String name)
synchronized void setLoggingStepBack (int loggingStepBack)
synchronized void shouldRun (boolean flag)
synchronized String getFormattedName ()
synchronized String getThreadName ()
synchronized Long getRunnableId ()
synchronized String getLoggerName ()
synchronized int getLoggingStepBack ()
synchronized Long getStartingTime ()
synchronized Long getEndingTime ()
synchronized boolean isRunning ()
synchronized ThreadLogger getThreadLogger ()
synchronized void log (Object msg)
synchronized void logWarning (Object msg)
synchronized void logOk (Object msg)
synchronized void logError (Object msg)
synchronized void logError (Exception e)
synchronized void terminate ()
synchronized void start ()
void run ()
void preImplement ()
abstract void implement ()
void postImplement ()
Static Public Attributes
static final String DEFAULT_NAME_LOGGER = CaggLoggersManager.DEFAULT_LOGGING_NAME_UI
static final String DEFAULT_NAME_THREAD = "CaggThread"
static final int DEFAULT_LOG_STEP_BACK = 3
static final String SYST_PROPERTY_RUNNABLE_NAME = "caggLoggerThread"
Protected Member Functions
synchronized Long getTimeStamp ()
synchronized Long getRunningTime ()
Private Member Functions
void initialise (String name, String loggerName)
Static Private Member Functions
static Long assignId ()
Private Attributes
String threadName
Long runnableId
String loggerName
int loggingStepBack = DEFAULT_LOG_STEP_BACK
Long startingTime = null
Boolean running = false
Detailed Description
Definition at line 7 of file CaggThread.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.evaluation.CaggThread.CaggThread ()
Definition at line 43 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.DEFAULT_NAME_LOGGER, it.emarolab.cagg.core.evaluation.CaggThread.DEFAULT_NAME_THREAD, and it.emarolab.cagg.core.evaluation.CaggThread.initialise().
it.emarolab.cagg.core.evaluation.CaggThread.CaggThread (String name)
Definition at line 46 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.DEFAULT_NAME_LOGGER, and it.emarolab.cagg.core.evaluation.CaggThread.initialise().
it.emarolab.cagg.core.evaluation.CaggThread.CaggThread (String name, String loggerName)
Definition at line 49 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.initialise().
Member Function Documentation
static Long it.emarolab.cagg.core.evaluation.CaggThread.assignId () static private
Definition at line 30 of file CaggThread.java.
Referenced by it.emarolab.cagg.core.evaluation.CaggThread.initialise().
synchronized Long it.emarolab.cagg.core.evaluation.CaggThread.getEndingTime ()
Definition at line 107 of file CaggThread.java.
Referenced by it.emarolab.cagg.core.evaluation.CaggThread.run().
synchronized String it.emarolab.cagg.core.evaluation.CaggThread.getFormattedName ()
Definition at line 89 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.runnableId, and it.emarolab.cagg.core.evaluation.CaggThread.threadName.
Referenced by it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger.error(), it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger.info(), it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger.ok(), and it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger.warning().
synchronized String it.emarolab.cagg.core.evaluation.CaggThread.getLoggerName ()
Definition at line 98 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.loggerName.
synchronized int it.emarolab.cagg.core.evaluation.CaggThread.getLoggingStepBack ()
Definition at line 101 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.loggingStepBack.
Referenced by it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger.error(), it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger.info(), it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger.ok(), and it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger.warning().
synchronized Long it.emarolab.cagg.core.evaluation.CaggThread.getRunnableId ()
Definition at line 95 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.runnableId.
synchronized Long it.emarolab.cagg.core.evaluation.CaggThread.getRunningTime () protected
Definition at line 207 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.getTimeStamp(), and it.emarolab.cagg.core.evaluation.CaggThread.running.
synchronized Long it.emarolab.cagg.core.evaluation.CaggThread.getStartingTime ()
Definition at line 104 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.startingTime.
synchronized ThreadLogger it.emarolab.cagg.core.evaluation.CaggThread.getThreadLogger ()
Definition at line 117 of file CaggThread.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.FactsSearcher(), it.emarolab.cagg.core.evaluation.CaggThread.log(), it.emarolab.cagg.core.evaluation.CaggThread.logError(), it.emarolab.cagg.core.evaluation.CaggThread.logOk(), and it.emarolab.cagg.core.evaluation.CaggThread.logWarning().
synchronized String it.emarolab.cagg.core.evaluation.CaggThread.getThreadName ()
Definition at line 92 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.threadName.
synchronized Long it.emarolab.cagg.core.evaluation.CaggThread.getTimeStamp () protected
Definition at line 204 of file CaggThread.java.
Referenced by it.emarolab.cagg.core.evaluation.CaggThread.getRunningTime(), and it.emarolab.cagg.core.evaluation.CaggThread.run().
abstract void it.emarolab.cagg.core.evaluation.CaggThread.implement () abstract
Referenced by it.emarolab.cagg.core.evaluation.CaggThread.run().
void it.emarolab.cagg.core.evaluation.CaggThread.initialise (String name, String loggerName) private
Definition at line 52 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.assignId(), it.emarolab.cagg.core.evaluation.CaggThread.DEFAULT_NAME_LOGGER, it.emarolab.cagg.core.evaluation.CaggThread.DEFAULT_NAME_THREAD, and it.emarolab.cagg.core.evaluation.CaggThread.loggerName.
Referenced by it.emarolab.cagg.core.evaluation.CaggThread.CaggThread().
synchronized boolean it.emarolab.cagg.core.evaluation.CaggThread.isRunning ()
Definition at line 110 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.running.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineRecorsive(), it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.getResult(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getSkippedWords(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getTrueFact(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getUnfeasibleFact(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getUsedWords(), it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.implement(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.join(), it.emarolab.cagg.core.evaluation.ThreadedEvaluator.join(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.start(), it.emarolab.cagg.core.evaluation.ThreadedEvaluator.start(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.stop(), and it.emarolab.cagg.core.evaluation.ThreadedEvaluator.stop().
synchronized void it.emarolab.cagg.core.evaluation.CaggThread.log (Object msg)
Definition at line 120 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.getThreadLogger().
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineInputs(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineRecorsive(), it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.evaluateOnce(), it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.implement(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.implement().
synchronized void it.emarolab.cagg.core.evaluation.CaggThread.logError (Object msg)
Definition at line 129 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.getThreadLogger().
Referenced by it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.getResult(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getSkippedWords(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getTrueFact(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getUnfeasibleFact(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getUsedWords(), and it.emarolab.cagg.core.evaluation.CaggThread.start().
synchronized void it.emarolab.cagg.core.evaluation.CaggThread.logError (Exception e)
Definition at line 132 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.getThreadLogger().
synchronized void it.emarolab.cagg.core.evaluation.CaggThread.logOk (Object msg)
Definition at line 126 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.getThreadLogger().
synchronized void it.emarolab.cagg.core.evaluation.CaggThread.logWarning (Object msg)
Definition at line 123 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.getThreadLogger().
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineInputs(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineRecorsive().
void it.emarolab.cagg.core.evaluation.CaggThread.postImplement ()
Definition at line 198 of file CaggThread.java.
Referenced by it.emarolab.cagg.core.evaluation.CaggThread.run().
void it.emarolab.cagg.core.evaluation.CaggThread.preImplement ()
Definition at line 196 of file CaggThread.java.
Referenced by it.emarolab.cagg.core.evaluation.CaggThread.run().
void it.emarolab.cagg.core.evaluation.CaggThread.run ()
Definition at line 183 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.getEndingTime(), it.emarolab.cagg.core.evaluation.CaggThread.getTimeStamp(), it.emarolab.cagg.core.evaluation.CaggThread.implement(), it.emarolab.cagg.core.evaluation.CaggThread.postImplement(), it.emarolab.cagg.core.evaluation.CaggThread.preImplement(), and it.emarolab.cagg.core.evaluation.CaggThread.running.
synchronized void it.emarolab.cagg.core.evaluation.CaggThread.setLoggerName (String name)
Definition at line 76 of file CaggThread.java.
synchronized void it.emarolab.cagg.core.evaluation.CaggThread.setLoggingStepBack (int loggingStepBack)
Definition at line 79 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.loggingStepBack.
synchronized void it.emarolab.cagg.core.evaluation.CaggThread.setRunnableId (Long runnableId)
Definition at line 73 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.runnableId.
synchronized void it.emarolab.cagg.core.evaluation.CaggThread.setThreadName (String threadName)
Definition at line 70 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.threadName.
synchronized void it.emarolab.cagg.core.evaluation.CaggThread.shouldRun (boolean flag)
Definition at line 82 of file CaggThread.java.
Referenced by it.emarolab.cagg.core.evaluation.ThreadedEvaluator.EvaluatorRunner.implement(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.implement().
synchronized void it.emarolab.cagg.core.evaluation.CaggThread.start ()
Definition at line 171 of file CaggThread.java.
References it.emarolab.cagg.core.evaluation.CaggThread.logError(), and it.emarolab.cagg.core.evaluation.CaggThread.running.
synchronized void it.emarolab.cagg.core.evaluation.CaggThread.terminate ()
Definition at line 166 of file CaggThread.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.stop().
Member Data Documentation
final int it.emarolab.cagg.core.evaluation.CaggThread.DEFAULT_LOG_STEP_BACK = 3 static
Definition at line 14 of file CaggThread.java.
final String it.emarolab.cagg.core.evaluation.CaggThread.DEFAULT_NAME_LOGGER = CaggLoggersManager.DEFAULT_LOGGING_NAME_UI static
Definition at line 12 of file CaggThread.java.
Referenced by it.emarolab.cagg.core.evaluation.CaggThread.CaggThread(), and it.emarolab.cagg.core.evaluation.CaggThread.initialise().
final String it.emarolab.cagg.core.evaluation.CaggThread.DEFAULT_NAME_THREAD = "CaggThread" static
Definition at line 13 of file CaggThread.java.
Referenced by it.emarolab.cagg.core.evaluation.CaggThread.CaggThread(), it.emarolab.cagg.debugging.DebuggingText.Log4j.error(), and it.emarolab.cagg.core.evaluation.CaggThread.initialise().
String it.emarolab.cagg.core.evaluation.CaggThread.loggerName private
Definition at line 23 of file CaggThread.java.
Referenced by it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger.error(), it.emarolab.cagg.core.evaluation.CaggThread.getLoggerName(), it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger.info(), it.emarolab.cagg.core.evaluation.CaggThread.initialise(), it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger.ok(), and it.emarolab.cagg.core.evaluation.CaggThread.ThreadLogger.warning().
int it.emarolab.cagg.core.evaluation.CaggThread.loggingStepBack = DEFAULT_LOG_STEP_BACK private
Definition at line 25 of file CaggThread.java.
Referenced by it.emarolab.cagg.core.evaluation.CaggThread.getLoggingStepBack(), and it.emarolab.cagg.core.evaluation.CaggThread.setLoggingStepBack().
Long it.emarolab.cagg.core.evaluation.CaggThread.runnableId private
Definition at line 22 of file CaggThread.java.
Referenced by it.emarolab.cagg.core.evaluation.CaggThread.getFormattedName(), it.emarolab.cagg.core.evaluation.CaggThread.getRunnableId(), and it.emarolab.cagg.core.evaluation.CaggThread.setRunnableId().
Boolean it.emarolab.cagg.core.evaluation.CaggThread.running = false private
Definition at line 27 of file CaggThread.java.
Referenced by it.emarolab.cagg.core.evaluation.CaggThread.getRunningTime(), it.emarolab.cagg.core.evaluation.CaggThread.isRunning(), it.emarolab.cagg.core.evaluation.CaggThread.run(), and it.emarolab.cagg.core.evaluation.CaggThread.start().
Long it.emarolab.cagg.core.evaluation.CaggThread.startingTime = null private
Definition at line 26 of file CaggThread.java.
Referenced by it.emarolab.cagg.core.evaluation.CaggThread.getStartingTime().
final String it.emarolab.cagg.core.evaluation.CaggThread.SYST_PROPERTY_RUNNABLE_NAME = "caggLoggerThread" static
Definition at line 15 of file CaggThread.java.
Referenced by it.emarolab.cagg.debugging.DebuggingText.Log4j.applayPropertyThreadLoggerName(), and it.emarolab.cagg.debugging.DebuggingText.Log4j.resetProperties().
String it.emarolab.cagg.core.evaluation.CaggThread.threadName private
Definition at line 21 of file CaggThread.java.
Referenced by it.emarolab.cagg.core.evaluation.CaggThread.getFormattedName(), it.emarolab.cagg.core.evaluation.CaggThread.getThreadName(), and it.emarolab.cagg.core.evaluation.CaggThread.setThreadName().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/evaluation/CaggThread.java