ConceptActionGrammarGenerator: it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord Class Reference
it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord Class Reference
Public Member Functions
SkippedWord (List< String > userInput, Integer idx)
void addSolutionId (Integer solutionIdx)
List< Integer > getSolutionIds ()
Integer getSolutionId (int idx)
Integer getSolutionMinIndex ()
Integer getSolutionMaxIndex ()
Integer getSolutionId ()
Boolean isComingFromSolution (SkippedWord other)
Boolean isComingFromSolution (Integer otherSolutionId)
String getWord ()
Integer getWordIndexOnUserInput ()
String toString ()
int hashCode ()
boolean equals (Object obj)
Private Member Functions
ThreadedInputFormatter getOuterType ()
Private Attributes
String word
Integer idx
List< Integer > solutionId = new ArrayList<>()
Detailed Description
Definition at line 429 of file ThreadedInputFormatter.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.SkippedWord (List< String > userInput, Integer idx)
Definition at line 435 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.idx.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.equals().
Member Function Documentation
void it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.addSolutionId (Integer solutionIdx)
Definition at line 440 of file ThreadedInputFormatter.java.
boolean it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.equals (Object obj)
Definition at line 497 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getWord(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.SkippedWord().
ThreadedInputFormatter it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getOuterType () private
Definition at line 525 of file ThreadedInputFormatter.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.hashCode().
Integer it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getSolutionId (int idx)
Definition at line 446 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.idx.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.isComingFromSolution().
Integer it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getSolutionId ()
Definition at line 455 of file ThreadedInputFormatter.java.
List< Integer> it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getSolutionIds ()
Definition at line 443 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.solutionId.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getSolutionMaxIndex(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.toString().
Integer it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getSolutionMaxIndex ()
Definition at line 452 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getSolutionIds().
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.toString().
Integer it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getSolutionMinIndex ()
Definition at line 449 of file ThreadedInputFormatter.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.toString().
String it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getWord ()
Definition at line 467 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.word.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.equals(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.toString().
Integer it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getWordIndexOnUserInput ()
Definition at line 470 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.idx.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.toString().
int it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.hashCode ()
Definition at line 488 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getOuterType(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.word.
Boolean it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.isComingFromSolution (SkippedWord other)
Definition at line 458 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getSolutionId().
Boolean it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.isComingFromSolution (Integer otherSolutionId)
Definition at line 461 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.solutionId.
String it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.toString ()
Definition at line 475 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getSolutionIds(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getSolutionMaxIndex(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getSolutionMinIndex(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getWord(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getWordIndexOnUserInput().
Member Data Documentation
Integer it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.idx private
Definition at line 432 of file ThreadedInputFormatter.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getSolutionId(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getWordIndexOnUserInput(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.SkippedWord().
List< Integer> it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.solutionId = new ArrayList<>() private
Definition at line 433 of file ThreadedInputFormatter.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getSolutionIds(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.isComingFromSolution().
String it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.word private
Definition at line 431 of file ThreadedInputFormatter.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.getWord(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.SkippedWord.hashCode().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/evaluation/inputFormatting/ThreadedInputFormatter.java