ConceptActionGrammarGenerator: it.emarolab.cagg.core.PseudoBinaryNode Class Reference
it.emarolab.cagg.core.PseudoBinaryNode Class Reference abstract
Classes
class CopyBinaryWalker
class MapBinaryCreator
class PseudoBinaryTreeGenerator< N extends PseudoBinaryNode >
class PseudoBinaryWalker
class StringBinaryWalker
Public Member Functions
PseudoBinaryNode ()
PseudoBinaryNode (String prefixId)
PseudoBinaryNode (Integer maxChildrenCount)
PseudoBinaryNode (Integer maxChildrenCount, String prefixId)
abstract PseudoBinaryNode copy (Boolean createNewCopyID)
PseudoBinaryNode getChild (int i)
PseudoBinaryNode getLeftChild ()
PseudoBinaryNode getRightChild ()
Integer getMaxChildrenCount ()
Boolean isComplite ()
Boolean isLeft ()
boolean hasLeftChild ()
boolean hasRightChild ()
void add (MutableTreeNode newChild)
void addChildren (PseudoBinaryNode leftChild, PseudoBinaryNode rightChild)
void addChild (PseudoBinaryNode newChild)
void addLeftChild (PseudoBinaryNode newChild)
void addRightChild (PseudoBinaryNode newChild)
void add (int position, BaseNode newChild)
void remove (MutableTreeNode aChild)
void remove (int childIndex)
void removeFromParent ()
void removeAllChildren ()
void replaceLeftChild (PseudoBinaryNode newChild)
void replaceRightChild (PseudoBinaryNode newChild)
String getDebuggingId ()
String toTreeString ()
PseudoBinaryNode copyTree ()
PseudoBinaryNode copyTree (Boolean updateCopyId)
PseudoBinaryNode copyTreeWithNewID (Map< Long, List< String >> tagMap)
PseudoBinaryNode copyTreeWithNewID (Map< Long, List< String >> tagMap, Boolean resetOriginalId)
Map< Long, BaseNode > toMap ()
Map< Long, BaseNode > toMap (Boolean useCopyId)
Map< Long, BaseNode > toTermMap ()
Map< Long, BaseNode > toTermMap (Boolean useCopyId)
Public Member Functions inherited from it.emarolab.cagg.core.BaseNode
BaseNode ()
BaseNode (String prefixId)
abstract String toString ()
Long getOriginalId ()
Long getId ()
BaseNode getParent ()
Long getCopyId ()
Boolean isCopy ()
void setPrefixId (String prefixId)
String getPrefixId ()
String getDebuggingId ()
List< BaseNode > getChildrenArray ()
void add (int position, BaseNode newChild)
BaseNode getChild (int index)
void printTree ()
String toTreeString ()
BaseNode copyContents (BaseNode newNode, Boolean generateCopyId)
BaseNode copyTree ()
BaseNode copyTree (final Boolean updateCopyId)
BaseNode copyTreeWithNewID (Map< Long, List< String >> tagMap)
Map< Long, BaseNode > toMap ()
Map< Long, BaseNode > toMap (Boolean useCopyId)
void showTree ()
void showTree (final String frameTitle)
Protected Member Functions
void setLeft ()
void setRight ()
void resetPosition ()
void add (MutableTreeNode newChild, Boolean suppressWarning)
Protected Member Functions inherited from it.emarolab.cagg.core.BaseNode
abstract BaseNode copy (Boolean createNewCopyID)
void setOriginalId (Long originalId)
void setId (Long id)
void add (MutableTreeNode newChild, Boolean suppressWarning)
Private Member Functions
void initialise (Integer maxChildrenCount)
void setMaxChildrenCount (Integer maxChildrenCount)
void setPosition (PseudoBinaryNode newChild)
Private Attributes
Boolean fromChildrenMethod = false
Integer order
Boolean isLeft = null
Additional Inherited Members
Static Public Attributes inherited from it.emarolab.cagg.core.BaseNode
static final String DEFAULT_PREFIX_ID = "m"
static Boolean DEFAULT_VERBOSE = false
static Boolean LOG_TOTAL_TIME_ANYTWAY = false
static String DEFAULT_VISITOR_NAME = "visitor"
static String DEFAULT_WALKER_NAME = "walker"
Detailed Description
Definition at line 16 of file PseudoBinaryNode.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryNode ()
Definition at line 28 of file PseudoBinaryNode.java.
it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryNode (String prefixId)
Definition at line 32 of file PseudoBinaryNode.java.
it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryNode (Integer maxChildrenCount)
Definition at line 37 of file PseudoBinaryNode.java.
it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryNode (Integer maxChildrenCount, String prefixId)
Definition at line 42 of file PseudoBinaryNode.java.
Member Function Documentation
void it.emarolab.cagg.core.PseudoBinaryNode.add (MutableTreeNode newChild)
add a new child to this node. Do not call directly this function in order to use max child managing mechanism. Use addChild(ExpressionNode) or addChildren(ExpressionNode, ExpressionNode) instead.
Parameters
newChild the new node to be added as a child to this parent.
Definition at line 155 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.add (MutableTreeNode newChild, Boolean suppressWarning) protected
Definition at line 168 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.add (int position, BaseNode newChild)
Definition at line 213 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.addChild (PseudoBinaryNode newChild)
add a new children to this node by managing the fact that this tree should satisfy getMaxChildrenCount(). Be aware that it does not do nothing if the
newChild1
is equal to another child of this node, since it calls add(MutableTreeNode).
Parameters
newChild a new node to be added as a child of this node.
Definition at line 192 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.addChildren (PseudoBinaryNode leftChild, PseudoBinaryNode rightChild)
add two new children to this node by managing the fact that this tree should satisfy getMaxChildrenCount(). Be aware that it does not do nothing if the
newChild1 = newChild2
, since it calls add(MutableTreeNode).
Parameters
newChild1 a new node to be added as a child of this node.
newChild2 another new node to be added as a child of this node.
Definition at line 180 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.addLeftChild (PseudoBinaryNode newChild)
Definition at line 200 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.addRightChild (PseudoBinaryNode newChild)
Definition at line 205 of file PseudoBinaryNode.java.
abstract PseudoBinaryNode it.emarolab.cagg.core.PseudoBinaryNode.copy (Boolean createNewCopyID) abstract
PseudoBinaryNode it.emarolab.cagg.core.PseudoBinaryNode.copyTree ()
Definition at line 323 of file PseudoBinaryNode.java.
PseudoBinaryNode it.emarolab.cagg.core.PseudoBinaryNode.copyTree (Boolean updateCopyId)
Definition at line 327 of file PseudoBinaryNode.java.
PseudoBinaryNode it.emarolab.cagg.core.PseudoBinaryNode.copyTreeWithNewID (Map< Long, List< String >> tagMap)
Definition at line 333 of file PseudoBinaryNode.java.
PseudoBinaryNode it.emarolab.cagg.core.PseudoBinaryNode.copyTreeWithNewID (Map< Long, List< String >> tagMap, Boolean resetOriginalId)
Definition at line 336 of file PseudoBinaryNode.java.
PseudoBinaryNode it.emarolab.cagg.core.PseudoBinaryNode.getChild (int i)
Definition at line 63 of file PseudoBinaryNode.java.
String it.emarolab.cagg.core.PseudoBinaryNode.getDebuggingId ()
Definition at line 279 of file PseudoBinaryNode.java.
PseudoBinaryNode it.emarolab.cagg.core.PseudoBinaryNode.getLeftChild ()
Definition at line 66 of file PseudoBinaryNode.java.
Referenced by it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker.walkForAll(), and it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryWalker.walkForAll().
Integer it.emarolab.cagg.core.PseudoBinaryNode.getMaxChildrenCount ()
Returns
the maximum number of children that this node can accepts. This is set on constructor or by copyContents(SyntaxNode) by calling getMaxChildrenCount().
Definition at line 81 of file PseudoBinaryNode.java.
PseudoBinaryNode it.emarolab.cagg.core.PseudoBinaryNode.getRightChild ()
Definition at line 71 of file PseudoBinaryNode.java.
Referenced by it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker.walkForAll(), and it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryWalker.walkForAll().
boolean it.emarolab.cagg.core.PseudoBinaryNode.hasLeftChild ()
Definition at line 128 of file PseudoBinaryNode.java.
Referenced by it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker.walkForAll(), and it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryWalker.walkForAll().
boolean it.emarolab.cagg.core.PseudoBinaryNode.hasRightChild ()
Definition at line 136 of file PseudoBinaryNode.java.
Referenced by it.emarolab.cagg.core.PseudoBinaryNode.CopyBinaryWalker.walkForAll(), and it.emarolab.cagg.core.PseudoBinaryNode.PseudoBinaryWalker.walkForAll().
void it.emarolab.cagg.core.PseudoBinaryNode.initialise (Integer maxChildrenCount) private
Definition at line 47 of file PseudoBinaryNode.java.
Boolean it.emarolab.cagg.core.PseudoBinaryNode.isComplite ()
Returns
true
if the node has as much children as it maximum number defines (getMaxChildrenCount()}).
false
otherwise
Definition at line 120 of file PseudoBinaryNode.java.
Boolean it.emarolab.cagg.core.PseudoBinaryNode.isLeft ()
Definition at line 125 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.remove (MutableTreeNode aChild)
Definition at line 238 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.remove (int childIndex)
Definition at line 244 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.removeAllChildren ()
Definition at line 254 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.removeFromParent ()
Definition at line 249 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.replaceLeftChild (PseudoBinaryNode newChild)
Definition at line 260 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.replaceRightChild (PseudoBinaryNode newChild)
Definition at line 265 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.resetPosition () protected
Definition at line 99 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.setLeft () protected
Definition at line 93 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.setMaxChildrenCount (Integer maxChildrenCount) private
Definition at line 88 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.setPosition (PseudoBinaryNode newChild) private
Definition at line 102 of file PseudoBinaryNode.java.
void it.emarolab.cagg.core.PseudoBinaryNode.setRight () protected
Definition at line 96 of file PseudoBinaryNode.java.
Map<Long, BaseNode> it.emarolab.cagg.core.PseudoBinaryNode.toMap ()
Definition at line 427 of file PseudoBinaryNode.java.
Map<Long, BaseNode> it.emarolab.cagg.core.PseudoBinaryNode.toMap (Boolean useCopyId)
Definition at line 431 of file PseudoBinaryNode.java.
Map<Long, BaseNode> it.emarolab.cagg.core.PseudoBinaryNode.toTermMap ()
Definition at line 436 of file PseudoBinaryNode.java.
Map<Long, BaseNode> it.emarolab.cagg.core.PseudoBinaryNode.toTermMap (Boolean useCopyId)
Definition at line 439 of file PseudoBinaryNode.java.
String it.emarolab.cagg.core.PseudoBinaryNode.toTreeString ()
Definition at line 289 of file PseudoBinaryNode.java.
Member Data Documentation
Boolean it.emarolab.cagg.core.PseudoBinaryNode.fromChildrenMethod = false private
Definition at line 21 of file PseudoBinaryNode.java.
Boolean it.emarolab.cagg.core.PseudoBinaryNode.isLeft = null private
Definition at line 23 of file PseudoBinaryNode.java.
Integer it.emarolab.cagg.core.PseudoBinaryNode.order private
Definition at line 22 of file PseudoBinaryNode.java.
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/PseudoBinaryNode.java