ConceptActionGrammarGenerator: it.emarolab.cagg.debugging.DebuggingGui.DebuggingStaticActioner Class Reference
it.emarolab.cagg.debugging.DebuggingGui.DebuggingStaticActioner Class Reference
Static Public Member Functions
static String getBasePath (String stateFilePath)
static Boolean serialiseClick (JFrame mainFrame, GrammarBase<?> merger)
static GuiEvaluationInterface testClick (GrammarBase<?> merger, final TestDebugginGuiPanel testPanel, final SemanticTreeGuiPanel completeGuiPanel, final JGradientBooleanButton booleanButton)
Static Private Attributes
static final JFileChooser fc = new JFileChooser()
static String serialisationPath = null
Detailed Description
Version
Concept-Action Grammar Generator 1.1
File: src//cagg.debugging.DebuggingGui.java
Author
Buoncompagni Luca
DIBRIS, emaroLab,
University of Genoa.
15/gen/2016
This class contains the methods to be used when the user interact with the GUI. Particularly, it describes the actions that can be done in the
Testing
tab.
See Also
DebuggingGui
Definition at line 463 of file DebuggingGui.java.
Member Function Documentation
static String it.emarolab.cagg.debugging.DebuggingGui.DebuggingStaticActioner.getBasePath (String stateFilePath) static
Initialie and maintain the directory path when opening file.
Parameters
stateFilePath the previous opened directory or
null
.
Returns
returns the stateFilePath if it is not
null
. Or the default path when the application is launched from JAR (
JarChecker.getJarPath() + DebuggingDefaults.PATH_GRAMMA_DESERIALISATION_JAR
) or not (it.emarolab.cagg.debugging.DebuggingDefaults#PATH_GRAMMA_DESERIALISATION_NOTJAR)
Definition at line 479 of file DebuggingGui.java.
References it.emarolab.cagg.debugging.DebuggingGui.JarChecker.isFromJar, it.emarolab.cagg.debugging.DebuggingDefaults.PATH_GRAMMA_DESERIALISATION_JAR, and it.emarolab.cagg.debugging.DebuggingDefaults.PATH_GRAMMA_DESERIALISATION_NOTJAR.
Referenced by it.emarolab.cagg.debugging.baseComponents.DeserialisationGui.createAndstartGui().
static Boolean it.emarolab.cagg.debugging.DebuggingGui.DebuggingStaticActioner.serialiseClick (JFrame mainFrame, GrammarBase<?> merger) static
Method called when the button
"Serialise"
is clicked.
Parameters
mainFrame the GUI frame in which the javax.swing.JFileChooser is linked on.
merger the grammar structure to be serialised.
Returns
true
if success.
false
otherwise.
Definition at line 500 of file DebuggingGui.java.
static GuiEvaluationInterface it.emarolab.cagg.debugging.DebuggingGui.DebuggingStaticActioner.testClick (GrammarBase<?> merger, final TestDebugginGuiPanel testPanel, final SemanticTreeGuiPanel completeGuiPanel, final JGradientBooleanButton booleanButton) static
Method called when the button
"Test"
is clicked.
Parameters
merger the grammar structure to be tested.
testPanel the panel from where get input and set results.
completeGuiPanel the complete grammar tree panel to set node evaluation colors.
Definition at line 518 of file DebuggingGui.java.
References it.emarolab.cagg.debugging.baseComponents.JGradientBooleanButton.changeState(), and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.hasBeenKilled().
Member Data Documentation
final JFileChooser it.emarolab.cagg.debugging.DebuggingGui.DebuggingStaticActioner.fc = new JFileChooser() static private
Definition at line 465 of file DebuggingGui.java.
String it.emarolab.cagg.debugging.DebuggingGui.DebuggingStaticActioner.serialisationPath = null static private
Definition at line 466 of file DebuggingGui.java.
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/debugging/DebuggingGui.java