ConceptActionGrammarGenerator: it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues Class Reference
it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues Class Reference
Public Member Functions
ExpressionQueues ()
Queue< ExpressionNode<?> > getOperationQueue ()
Queue< ExpressionNode<?> > getTermQueue ()
void operationAdd (ExpressionNode<?> e)
void termAdd (ExpressionNode<?> e)
ExpressionNode<?> operationPull ()
ExpressionNode<?> termPull ()
ExpressionNode<?> operationPeek ()
ExpressionNode<?> termPeek ()
Boolean hasOperatorPending ()
Boolean hasTermPending ()
Integer hasPending ()
String toString ()
Private Attributes
Queue< ExpressionNode<?> > operationQueue
Detailed Description
Version
Concept-Action Grammar Generator 1.1
File: src//cagg.core.sourceInterface.grammar.expressionTree.ExpressionTreeGenerator.java
Author
Buoncompagni Luca
DIBRIS, emaroLab,
University of Genoa.
15/gen/2016
This class implements and manage two different java.util.Queue of it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionNodeOld. Particularly, one queue contains only the Operation nodes, while the other only the Term node.
Moreover this class monitor the state of the queues by considering the number of elements and, based on that, it returns the type of pending action to be performed in order to build the ET through the methods: hasPending(), hasOperatorPending() and hasTermPending().
See Also
java.util.Queue
it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionNodeOld
Definition at line 211 of file ExpressionTreeGenerator.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.ExpressionQueues ()
Initialise this class by creating new Term and Operation queues.
Definition at line 219 of file ExpressionTreeGenerator.java.
References it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.operationQueue.
Member Function Documentation
Queue<ExpressionNode<?> > it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.getOperationQueue ()
Returns
the queue containing all the Operation nodes not yet added to the ET.
Definition at line 228 of file ExpressionTreeGenerator.java.
References it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.operationQueue.
Queue<ExpressionNode<?> > it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.getTermQueue ()
Returns
the queue containing all the Term nodes not yet added to the ET.
Definition at line 234 of file ExpressionTreeGenerator.java.
Boolean it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.hasOperatorPending ()
It check the size of the Operation queue in order to check if there are at least one operation node to be processed during ET generation.
Returns
true
if there are at least one operation in the queues.
false
otherwise.
Definition at line 292 of file ExpressionTreeGenerator.java.
Referenced by it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.getExpressionTreeRoot(), and it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.hasPending().
Integer it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.hasPending ()
This method check the state of the Operation and Term queues. Particolarly, it returns: ExpressionTreeGenerator#PENDING_NO if both queues are empty. Or: ExpressionTreeGenerator#PENDING_OPERATION if the Operation queue is not empty. Or: ExpressionTreeGenerator#PENDING_TERM if the Operation queue is empty but the Term queue not. Or: ExpressionTreeGenerator#PENDING_ERROR otherwise.
Returns
the actual pending node in queues tag.
Definition at line 312 of file ExpressionTreeGenerator.java.
References it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.hasOperatorPending(), it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.hasTermPending(), it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.PENDING_ERROR, it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.PENDING_NO, it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.PENDING_OPERATION, and it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.PENDING_TERM.
Referenced by it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.updateExpressionTree().
Boolean it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.hasTermPending ()
It check the size of the Term queue in order to check if there are at least one term node to be processed during ET generation.
Returns
true
if there are at least one term in the queues.
false
otherwise.
Definition at line 300 of file ExpressionTreeGenerator.java.
Referenced by it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.getExpressionTreeRoot(), and it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.hasPending().
void it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.operationAdd (ExpressionNode<?> e)
This method add a node to the operation queue by calling: java.util.Queue#offer(Object).
Parameters
e the node to be added to the Operation queue.
Definition at line 244 of file ExpressionTreeGenerator.java.
ExpressionNode<?> it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.operationPeek ()
This method returns (but not remove) an operation node from the operation queue.
Returns
the result of java.util.Queue#peek() applied to the Operation queue.
Definition at line 275 of file ExpressionTreeGenerator.java.
ExpressionNode<?> it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.operationPull ()
This method returns and remove an operation node from the operation queue.
Returns
the result of java.util.Queue#poll() applied to the Operation queue.
Definition at line 260 of file ExpressionTreeGenerator.java.
Referenced by it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.getExpressionTreeRoot(), and it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.updateExpressionTree().
void it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.termAdd (ExpressionNode<?> e)
This method add a node to the term queue by calling: java.util.Queue#offer(Object).
Parameters
e the node to be added to the Term queue.
Definition at line 252 of file ExpressionTreeGenerator.java.
ExpressionNode<?> it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.termPeek ()
This method returns (but not remove) a term node from the term queue.
Returns
the result of java.util.Queue#peek() applied to the Term queue.
Definition at line 282 of file ExpressionTreeGenerator.java.
ExpressionNode<?> it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.termPull ()
This method returns and remove a term node from the term queue.
Returns
the result of java.util.Queue#poll() applied to the Term queue.
Definition at line 267 of file ExpressionTreeGenerator.java.
Referenced by it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.getExpressionTreeRoot(), and it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.updateExpressionTree().
String it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.toString ()
This method describe this class with a string formatted as:
"{[OPERATORS:" + operationQueue + " ];[ TEMRS:" + termQueue + "]}";
. Where,
operationQueue
is given from getOperationQueue(). While,
termQueue
is given from getTermQueue().
See Also
java.lang.Object::toString()
Definition at line 332 of file ExpressionTreeGenerator.java.
References it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.operationQueue.
Member Data Documentation
Queue< ExpressionNode<?> > it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.operationQueue private
Definition at line 213 of file ExpressionTreeGenerator.java.
Referenced by it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.ExpressionQueues(), it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.getOperationQueue(), and it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionTreeGenerator.ExpressionQueues.toString().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/language/syntax/expressionTree/ExpressionTreeGenerator.java