ConceptActionGrammarGenerator: it.emarolab.cagg.core.evaluation.GuiEvaluator Class Reference
it.emarolab.cagg.core.evaluation.GuiEvaluator Class Reference
Public Member Functions
GuiEvaluator (ThreadedInputFormatter formatter)
void activateTrigger (EvaluationResults result)
void startAndMonitorResult (TestDebugginGuiPanel testPanel, SemanticTreeGuiPanel treePanel)
void stopEvaluation ()
Boolean hasBeenKilled ()
Boolean inProgress ()
Integer getEvaluatingProgress ()
EvaluatingInfo getNewEvaluatingInfo ()
EvaluatedTree getAllEvaluatedExpressions ()
Public Member Functions inherited from it.emarolab.cagg.core.evaluation.ThreadedEvaluator
ThreadedEvaluator (ThreadedInputFormatter formatter)
ThreadedEvaluator (String logPrefix, ThreadedInputFormatter formatter)
void start ()
void start (String threadName)
void stop ()
void join ()
boolean isRunning ()
EvaluationResults getNextSolution ()
Integer getEvaluationCount ()
Protected Member Functions
void resetExpression ()
Protected Member Functions inherited from it.emarolab.cagg.core.evaluation.ThreadedEvaluator
EvaluatorRunner getEvaluatorThread ()
void setEvaluatorThread (EvaluatorRunner evalThread)
Integer getProcessedSolutionIdx ()
Private Attributes
EvaluatingInfo guiInfo = new EvaluatingInfo()
EvaluatedTree evalTree = new EvaluatedTree()
Boolean hasBeenKilled = null
Integer previousTreeSize = 0
Detailed Description
Definition at line 13 of file GuiEvaluator.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.evaluation.GuiEvaluator.GuiEvaluator (ThreadedInputFormatter formatter)
Definition at line 27 of file GuiEvaluator.java.
Member Function Documentation
void it.emarolab.cagg.core.evaluation.GuiEvaluator.activateTrigger (EvaluationResults result)
Definition at line 49 of file GuiEvaluator.java.
EvaluatedTree it.emarolab.cagg.core.evaluation.GuiEvaluator.getAllEvaluatedExpressions ()
Implements it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.
Definition at line 183 of file GuiEvaluator.java.
References it.emarolab.cagg.core.evaluation.GuiEvaluator.evalTree.
Integer it.emarolab.cagg.core.evaluation.GuiEvaluator.getEvaluatingProgress ()
Implements it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.
Definition at line 172 of file GuiEvaluator.java.
EvaluatingInfo it.emarolab.cagg.core.evaluation.GuiEvaluator.getNewEvaluatingInfo ()
Implements it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.
Definition at line 177 of file GuiEvaluator.java.
References it.emarolab.cagg.core.evaluation.GuiEvaluator.guiInfo.
Boolean it.emarolab.cagg.core.evaluation.GuiEvaluator.hasBeenKilled ()
Implements it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.
Definition at line 164 of file GuiEvaluator.java.
Referenced by it.emarolab.cagg.core.evaluation.GuiEvaluator.startAndMonitorResult(), and it.emarolab.cagg.core.evaluation.GuiEvaluator.stopEvaluation().
Boolean it.emarolab.cagg.core.evaluation.GuiEvaluator.inProgress ()
Implements it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.
Definition at line 168 of file GuiEvaluator.java.
void it.emarolab.cagg.core.evaluation.GuiEvaluator.resetExpression () protected
Definition at line 35 of file GuiEvaluator.java.
References it.emarolab.cagg.core.evaluation.GuiEvaluator.evalTree.
void it.emarolab.cagg.core.evaluation.GuiEvaluator.startAndMonitorResult (TestDebugginGuiPanel testPanel, SemanticTreeGuiPanel treePanel)
Implements it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.
Definition at line 58 of file GuiEvaluator.java.
References it.emarolab.cagg.debugging.baseComponents.customPanel.SemanticTreeGuiPanel.addTree(), it.emarolab.cagg.core.evaluation.GuiEvaluator.evalTree, it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.SolutionType.FEASIBLE, it.emarolab.cagg.core.evaluation.ThreadedEvaluator.getNextSolution(), it.emarolab.cagg.core.evaluation.GuiEvaluator.hasBeenKilled(), it.emarolab.cagg.core.evaluation.GuiEvaluator.previousTreeSize, it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.SolutionType.TRUE_SOL_IDX, it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.SolutionType.UNFEASIBLE, and it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.SolutionType.UNREASONABLE.
void it.emarolab.cagg.core.evaluation.GuiEvaluator.stopEvaluation ()
Implements it.emarolab.cagg.core.evaluation.interfacing.GuiEvaluationInterface.
Definition at line 158 of file GuiEvaluator.java.
References it.emarolab.cagg.core.evaluation.GuiEvaluator.hasBeenKilled().
Member Data Documentation
EvaluatedTree it.emarolab.cagg.core.evaluation.GuiEvaluator.evalTree = new EvaluatedTree() private
Definition at line 20 of file GuiEvaluator.java.
Referenced by it.emarolab.cagg.core.evaluation.GuiEvaluator.getAllEvaluatedExpressions(), it.emarolab.cagg.core.evaluation.GuiEvaluator.resetExpression(), and it.emarolab.cagg.core.evaluation.GuiEvaluator.startAndMonitorResult().
EvaluatingInfo it.emarolab.cagg.core.evaluation.GuiEvaluator.guiInfo = new EvaluatingInfo() private
Definition at line 19 of file GuiEvaluator.java.
Referenced by it.emarolab.cagg.core.evaluation.GuiEvaluator.getNewEvaluatingInfo().
Boolean it.emarolab.cagg.core.evaluation.GuiEvaluator.hasBeenKilled = null private
Definition at line 21 of file GuiEvaluator.java.
Integer it.emarolab.cagg.core.evaluation.GuiEvaluator.previousTreeSize = 0 private
Definition at line 22 of file GuiEvaluator.java.
Referenced by it.emarolab.cagg.core.evaluation.GuiEvaluator.startAndMonitorResult().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/evaluation/GuiEvaluator.java