ConceptActionGrammarGenerator: it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase Class Reference
it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase Class Reference abstract
Public Member Functions
InputFormatterBase (GrammarBase<?> grammar)
InputFormatterBase (String loggerName, GrammarBase<?> grammar)
InputFormatterBase (GrammarBase<?> grammar, String notAllowableCharPatern)
InputFormatterBase (String loggerName, GrammarBase<?> grammar, String notAllowableCharPatern)
void searchFacts (String input)
GrammarBase<?> getGrammar ()
List< String > getTokenisedInputs ()
String getNotAllowableCharPatern ()
Long getFormattingStatingTimeStamp ()
String getLoggerName ()
ThreadLogger getThreadLogger ()
void setGrammar (GrammarBase<?> grammar)
void setNotAllowableCharPatern (String notAllowableCharPatern)
void setLoggerName (String loggerName)
void setThreadLogger (ThreadLogger logger)
abstract Facts<?> getNextFacts ()
abstract Integer getFactsCount ()
abstract void stop ()
abstract void join ()
abstract boolean isRunning ()
Static Public Attributes
static final String DEFAULT_NOT_ALLOWABLE_CHAR_PATTERN = "[^a-zA-Z0-9À-ÿ\\s]"
static final Boolean SHOULD_COLLECT_UNFEASIBLE_FACTS = false
static final String DEFAULT_LOGGER_NAME = CaggLoggersManager.DEFAULT_LOGGING_NAME_FORMATTER
static final int DEFAULT_LOGGING_BACK_STEP = 2
Protected Member Functions
List< String > tokenize (String input, String notAllowableCharPatern)
abstract void start ()
void log (Object msg)
void log (int backStep, Object msg)
void logWarning (Object msg)
void logWarning (int backStep, Object msg)
void logOk (Object msg)
void logOk (int backStep, Object msg)
void logError (Object msg)
void logError (int backStep, Object msg)
void logError (Exception e)
void logError (int backStep, Exception e)
Private Member Functions
void initialise (GrammarBase<?> grammar, String notAllowableCharPatern, String logName)
Private Attributes
GrammarBase<?> grammar
List< String > tokenisedInputs
String notAllowableCharPatern
Long formattingStartTimeStamp = null
String loggerName
ThreadLogger threadLogger
Detailed Description
Definition at line 14 of file InputFormatterBase.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.InputFormatterBase (GrammarBase<?> grammar)
Definition at line 40 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.DEFAULT_LOGGER_NAME, it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.DEFAULT_NOT_ALLOWABLE_CHAR_PATTERN, and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.initialise().
it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.InputFormatterBase (String loggerName, GrammarBase<?> grammar)
Definition at line 43 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.DEFAULT_NOT_ALLOWABLE_CHAR_PATTERN, and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.initialise().
it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.InputFormatterBase (GrammarBase<?> grammar, String notAllowableCharPatern)
Definition at line 46 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.DEFAULT_LOGGER_NAME, and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.initialise().
it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.InputFormatterBase (String loggerName, GrammarBase<?> grammar, String notAllowableCharPatern)
Definition at line 49 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.initialise().
Member Function Documentation
abstract Integer it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.getFactsCount () abstract
Long it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.getFormattingStatingTimeStamp ()
Definition at line 116 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.formattingStartTimeStamp.
GrammarBase<?> it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.getGrammar ()
Definition at line 107 of file InputFormatterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getTermOccurence(), and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.tokenize().
String it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.getLoggerName ()
Definition at line 119 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.loggerName.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.start().
abstract Facts<?> it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.getNextFacts () abstract
String it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.getNotAllowableCharPatern ()
Definition at line 113 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.notAllowableCharPatern.
ThreadLogger it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.getThreadLogger ()
Definition at line 122 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.threadLogger.
List< String> it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.getTokenisedInputs ()
Definition at line 110 of file InputFormatterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.start().
void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.initialise (GrammarBase<?> grammar, String notAllowableCharPatern, String logName) private
Definition at line 52 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.DEFAULT_LOGGER_NAME, it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.grammar, and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.notAllowableCharPatern.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.InputFormatterBase().
abstract boolean it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.isRunning () abstract
abstract void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.join () abstract
void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.log (Object msg) protected
Definition at line 156 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.DEFAULT_LOGGING_BACK_STEP, and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.loggerName.
void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.log (int backStep, Object msg) protected
Definition at line 159 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.DEFAULT_LOGGING_BACK_STEP, and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.loggerName.
void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.logError (Object msg) protected
Definition at line 177 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.DEFAULT_LOGGING_BACK_STEP, and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.loggerName.
void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.logError (int backStep, Object msg) protected
Definition at line 180 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.DEFAULT_LOGGING_BACK_STEP, and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.loggerName.
void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.logError (Exception e) protected
Definition at line 184 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.DEFAULT_LOGGING_BACK_STEP, and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.loggerName.
void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.logError (int backStep, Exception e) protected
Definition at line 187 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.DEFAULT_LOGGING_BACK_STEP, and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.loggerName.
void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.logOk (Object msg) protected
Definition at line 170 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.DEFAULT_LOGGING_BACK_STEP, and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.loggerName.
void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.logOk (int backStep, Object msg) protected
Definition at line 173 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.DEFAULT_LOGGING_BACK_STEP, and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.loggerName.
void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.logWarning (Object msg) protected
Definition at line 163 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.DEFAULT_LOGGING_BACK_STEP, and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.loggerName.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.tokenize().
void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.logWarning (int backStep, Object msg) protected
Definition at line 166 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.DEFAULT_LOGGING_BACK_STEP, and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.loggerName.
void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.searchFacts (String input)
Definition at line 65 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.formattingStartTimeStamp, it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.notAllowableCharPatern, it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.start(), and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.tokenize().
void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.setGrammar (GrammarBase<?> grammar)
Definition at line 129 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.grammar.
void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.setLoggerName (String loggerName)
Definition at line 135 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.loggerName.
void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.setNotAllowableCharPatern (String notAllowableCharPatern)
Definition at line 132 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.notAllowableCharPatern.
void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.setThreadLogger (ThreadLogger logger)
Definition at line 138 of file InputFormatterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.FactsSearcher().
abstract void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.start () abstract protected
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.searchFacts().
abstract void it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.stop () abstract
List< String> it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.tokenize (String input, String notAllowableCharPatern) protected
This method is used to pre-filtering the input given from the user. In particular it uses
allowableCharPatern
to discard not allowable chars in the input. Then, it tokenise the string and returns each tokens in a list.
Parameters
input the peach-to-text string given by the user.
allowableCharPatern the set of char that are allowable in the
input
. The others will be discarded.
Returns
the input given by the user where the not allowable chars are removed. Moreover, the returning value is a list which contains input words (e.g. tokenised by space).
Definition at line 83 of file InputFormatterBase.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.getGrammar(), it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.logWarning(), and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.notAllowableCharPatern.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.searchFacts().
Member Data Documentation
final String it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.DEFAULT_LOGGER_NAME = CaggLoggersManager.DEFAULT_LOGGING_NAME_FORMATTER static
Definition at line 21 of file InputFormatterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.initialise(), and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.InputFormatterBase().
final int it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.DEFAULT_LOGGING_BACK_STEP = 2 static
Definition at line 22 of file InputFormatterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.log(), it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.logError(), it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.logOk(), and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.logWarning().
final String it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.DEFAULT_NOT_ALLOWABLE_CHAR_PATTERN = "[^a-zA-Z0-9À-ÿ\\s]" static
Definition at line 19 of file InputFormatterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.InputFormatterBase().
Long it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.formattingStartTimeStamp = null private
Definition at line 31 of file InputFormatterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.getFormattingStatingTimeStamp(), and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.searchFacts().
GrammarBase<?> it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.grammar private
Definition at line 28 of file InputFormatterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.initialise(), and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.setGrammar().
String it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.loggerName private
Definition at line 32 of file InputFormatterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.getLoggerName(), it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.log(), it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.logError(), it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.logOk(), it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.logWarning(), and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.setLoggerName().
String it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.notAllowableCharPatern private
Definition at line 30 of file InputFormatterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.getNotAllowableCharPatern(), it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.initialise(), it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.searchFacts(), it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.setNotAllowableCharPatern(), and it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.tokenize().
final Boolean it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.SHOULD_COLLECT_UNFEASIBLE_FACTS = false static
Definition at line 20 of file InputFormatterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.storeUnfeasibleSolution().
ThreadLogger it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.threadLogger private
Definition at line 33 of file InputFormatterBase.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.getThreadLogger().
List< String> it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.tokenisedInputs private
Definition at line 29 of file InputFormatterBase.java.
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/evaluation/inputFormatting/InputFormatterBase.java