ConceptActionGrammarGenerator: it.emarolab.cagg.debugging.CaggLoggersManager Class Reference
it.emarolab.cagg.debugging.CaggLoggersManager Class Reference
Classes
class LoggersNames
Public Member Functions
CaggLoggersManager ()
CaggLoggersManager (String log4jConfigPath)
CaggLoggersManager (String evaluatorLoggerName, String formatterLoggerName, String uiLoggerName, String parsingLoggerName, String grammarLoggingName, String testLoggerName)
CaggLoggersManager (String evaluatorLoggerName, String formatterLoggerName, String uiLoggerName, String parsingLoggerName, String grammarLoggingName, String testLoggerName, String log4jConfigPath)
CaggLoggersManager (String uiLoggerName, String parsingLoggerName, String grammarLoggingName, String testLoggerName)
CaggLoggersManager (String uiLoggerName, String parsingLoggerName, String grammarLoggingName, String testLoggerName, String log4jConfigPath)
LoggersNames getNames ()
String getLog4jConfigPath ()
void applyAll ()
Static Public Member Functions
static void setFilePath (String path)
static String getFilePath ()
Static Public Attributes
static final String DEFAULT_LOGGING_NAME_EVALUATOR = "log-evaluator"
static final String DEFAULT_LOGGING_NAME_FORMATTER = "log-formatter"
static final String DEFAULT_LOGGING_NAME_UI = "log-UI"
static final String DEFAULT_LOGGING_NAME_PARSING = "log-parsing"
static final String DEFAULT_LOGGING_NAME_GRAMMAR = "log-grammar"
static final String DEFAULT_LOGGING_NAME_TEST = "log-test"
static final String DEFAULT_CONFIGURATION_PATH = DebuggingDefaults.PATH_LOG_CONF_BASE + "log4j_guiConf.xml"
static final String SYST_PROPERTY_PATH = "caggLoggerPath"
Protected Member Functions
void apply (String name)
Private Member Functions
void initialise (LoggersNames names, String log4jConfigPath)
Private Attributes
LoggersNames names
String log4jConfigPath
Detailed Description
Definition at line 8 of file CaggLoggersManager.java.
Constructor & Destructor Documentation
it.emarolab.cagg.debugging.CaggLoggersManager.CaggLoggersManager ()
Definition at line 31 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_CONFIGURATION_PATH, and it.emarolab.cagg.debugging.CaggLoggersManager.initialise().
it.emarolab.cagg.debugging.CaggLoggersManager.CaggLoggersManager (String log4jConfigPath)
Definition at line 34 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.initialise().
it.emarolab.cagg.debugging.CaggLoggersManager.CaggLoggersManager (String evaluatorLoggerName, String formatterLoggerName, String uiLoggerName, String parsingLoggerName, String grammarLoggingName, String testLoggerName)
Definition at line 37 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_CONFIGURATION_PATH, it.emarolab.cagg.debugging.CaggLoggersManager.initialise(), and it.emarolab.cagg.debugging.CaggLoggersManager.names.
it.emarolab.cagg.debugging.CaggLoggersManager.CaggLoggersManager (String evaluatorLoggerName, String formatterLoggerName, String uiLoggerName, String parsingLoggerName, String grammarLoggingName, String testLoggerName, String log4jConfigPath)
Definition at line 41 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.initialise(), and it.emarolab.cagg.debugging.CaggLoggersManager.names.
it.emarolab.cagg.debugging.CaggLoggersManager.CaggLoggersManager (String uiLoggerName, String parsingLoggerName, String grammarLoggingName, String testLoggerName)
Definition at line 45 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_CONFIGURATION_PATH, it.emarolab.cagg.debugging.CaggLoggersManager.initialise(), and it.emarolab.cagg.debugging.CaggLoggersManager.names.
it.emarolab.cagg.debugging.CaggLoggersManager.CaggLoggersManager (String uiLoggerName, String parsingLoggerName, String grammarLoggingName, String testLoggerName, String log4jConfigPath)
Definition at line 49 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.initialise(), and it.emarolab.cagg.debugging.CaggLoggersManager.names.
Member Function Documentation
void it.emarolab.cagg.debugging.CaggLoggersManager.apply (String name) protected
Definition at line 90 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.getLog4jConfigPath().
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.applyAll().
void it.emarolab.cagg.debugging.CaggLoggersManager.applyAll ()
Definition at line 73 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.apply(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getEvaluatorLoggerName(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getFormatterLoggerName(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getGrammarLoggerName(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getParsingLoggerName(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getTestLoggerName(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.getUILoggerName(), it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.isComplete, and it.emarolab.cagg.debugging.CaggLoggersManager.names.
static String it.emarolab.cagg.debugging.CaggLoggersManager.getFilePath () static
Definition at line 110 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.SYST_PROPERTY_PATH.
String it.emarolab.cagg.debugging.CaggLoggersManager.getLog4jConfigPath ()
Definition at line 66 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.log4jConfigPath.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.apply().
LoggersNames it.emarolab.cagg.debugging.CaggLoggersManager.getNames ()
Definition at line 63 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.names.
void it.emarolab.cagg.debugging.CaggLoggersManager.initialise (LoggersNames names, String log4jConfigPath) private
Definition at line 53 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.CaggLoggersManager.log4jConfigPath, and it.emarolab.cagg.debugging.CaggLoggersManager.setFilePath().
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.CaggLoggersManager().
static void it.emarolab.cagg.debugging.CaggLoggersManager.setFilePath (String path) static
Definition at line 94 of file CaggLoggersManager.java.
References it.emarolab.cagg.debugging.DebuggingText.getFormattedDate(), it.emarolab.cagg.debugging.UILog.getLogger(), it.emarolab.cagg.debugging.UILog.info(), it.emarolab.cagg.debugging.DebuggingDefaults.LOGS_FILE_FORMAT, it.emarolab.cagg.debugging.DebuggingDefaults.PATH_LOG_BASE, and it.emarolab.cagg.debugging.CaggLoggersManager.SYST_PROPERTY_PATH.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.initialise().
Member Data Documentation
final String it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_CONFIGURATION_PATH = DebuggingDefaults.PATH_LOG_CONF_BASE + "log4j_guiConf.xml" static
Definition at line 18 of file CaggLoggersManager.java.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.CaggLoggersManager().
final String it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_EVALUATOR = "log-evaluator" static
Definition at line 12 of file CaggLoggersManager.java.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.GrammarTesterBase(), and it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.LoggersNames().
final String it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_FORMATTER = "log-formatter" static
Definition at line 13 of file CaggLoggersManager.java.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.GrammarTesterBase(), and it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.LoggersNames().
final String it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_GRAMMAR = "log-grammar" static
Definition at line 16 of file CaggLoggersManager.java.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.LoggersNames().
final String it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_PARSING = "log-parsing" static
Definition at line 15 of file CaggLoggersManager.java.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.LoggersNames().
final String it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_TEST = "log-test" static
Definition at line 17 of file CaggLoggersManager.java.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.LoggersNames().
final String it.emarolab.cagg.debugging.CaggLoggersManager.DEFAULT_LOGGING_NAME_UI = "log-UI" static
Definition at line 14 of file CaggLoggersManager.java.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.LoggersNames.LoggersNames().
String it.emarolab.cagg.debugging.CaggLoggersManager.log4jConfigPath private
Definition at line 26 of file CaggLoggersManager.java.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.getLog4jConfigPath(), and it.emarolab.cagg.debugging.CaggLoggersManager.initialise().
LoggersNames it.emarolab.cagg.debugging.CaggLoggersManager.names private
Definition at line 25 of file CaggLoggersManager.java.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.applyAll(), it.emarolab.cagg.debugging.CaggLoggersManager.CaggLoggersManager(), and it.emarolab.cagg.debugging.CaggLoggersManager.getNames().
final String it.emarolab.cagg.debugging.CaggLoggersManager.SYST_PROPERTY_PATH = "caggLoggerPath" static
Definition at line 20 of file CaggLoggersManager.java.
Referenced by it.emarolab.cagg.debugging.CaggLoggersManager.getFilePath(), and it.emarolab.cagg.debugging.CaggLoggersManager.setFilePath().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/debugging/CaggLoggersManager.java