ConceptActionGrammarGenerator: it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter Class Reference
it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter Class Reference
Classes
class FactsSearcher
class SkippedWord
Public Member Functions
ThreadedInputFormatter (GrammarBase<?> grammar, String notAllowableCharPatern)
ThreadedInputFormatter (GrammarBase<?> grammar)
ThreadedInputFormatter (String loggetName, GrammarBase<?> grammar, String notAllowableCharPatern)
ThreadedInputFormatter (String logName, GrammarBase<?> grammar)
void start ()
void start (String threadName)
void stop ()
void join ()
boolean isRunning ()
Integer getFactsCount ()
Integer getUnfeasibleFactsCount ()
Facts<?> getNextFacts ()
List< Facts< Long > > getUnfeasibleFacts ()
Set< SkippedWord > getSkippedWords (int idx)
List< String > getUsedWords (int idx)
FactsSearcher getSearcher ()
Integer getActualFactsIdx ()
Public Member Functions inherited from it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase
InputFormatterBase (GrammarBase<?> grammar)
InputFormatterBase (String loggerName, GrammarBase<?> grammar)
InputFormatterBase (GrammarBase<?> grammar, String notAllowableCharPatern)
InputFormatterBase (String loggerName, GrammarBase<?> grammar, String notAllowableCharPatern)
void searchFacts (String input)
GrammarBase<?> getGrammar ()
List< String > getTokenisedInputs ()
String getNotAllowableCharPatern ()
Long getFormattingStatingTimeStamp ()
String getLoggerName ()
ThreadLogger getThreadLogger ()
void setGrammar (GrammarBase<?> grammar)
void setNotAllowableCharPatern (String notAllowableCharPatern)
void setLoggerName (String loggerName)
void setThreadLogger (ThreadLogger logger)
abstract Facts<?> getNextFacts ()
abstract Integer getFactsCount ()
abstract void stop ()
abstract void join ()
abstract boolean isRunning ()
Static Public Attributes
static final String DEFAULT_THREAD_NAME = "th-form"
Static Public Attributes inherited from it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase
static final String DEFAULT_NOT_ALLOWABLE_CHAR_PATTERN = "[^a-zA-Z0-9À-ÿ\\s]"
static final Boolean SHOULD_COLLECT_UNFEASIBLE_FACTS = false
static final String DEFAULT_LOGGER_NAME = CaggLoggersManager.DEFAULT_LOGGING_NAME_FORMATTER
static final int DEFAULT_LOGGING_BACK_STEP = 2
Private Attributes
FactsSearcher searcher = null
Integer factsIdx
Additional Inherited Members
Protected Member Functions inherited from it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase
List< String > tokenize (String input, String notAllowableCharPatern)
abstract void start ()
void log (Object msg)
void log (int backStep, Object msg)
void logWarning (Object msg)
void logWarning (int backStep, Object msg)
void logOk (Object msg)
void logOk (int backStep, Object msg)
void logError (Object msg)
void logError (int backStep, Object msg)
void logError (Exception e)
void logError (int backStep, Exception e)
Detailed Description
Definition at line 14 of file ThreadedInputFormatter.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.ThreadedInputFormatter (GrammarBase<?> grammar, String notAllowableCharPatern)
Definition at line 31 of file ThreadedInputFormatter.java.
it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.ThreadedInputFormatter (GrammarBase<?> grammar)
Definition at line 34 of file ThreadedInputFormatter.java.
it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.ThreadedInputFormatter (String loggetName, GrammarBase<?> grammar, String notAllowableCharPatern)
Definition at line 37 of file ThreadedInputFormatter.java.
it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.ThreadedInputFormatter (String logName, GrammarBase<?> grammar)
Definition at line 40 of file ThreadedInputFormatter.java.
Member Function Documentation
Integer it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.getActualFactsIdx ()
Definition at line 138 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.factsIdx.
Integer it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.getFactsCount ()
Definition at line 86 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.searcher.
Facts<?> it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.getNextFacts ()
Definition at line 97 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.factsIdx, and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.searcher.
FactsSearcher it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.getSearcher ()
Definition at line 135 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.searcher.
Set< SkippedWord> it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.getSkippedWords (int idx)
Definition at line 109 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getSkippedWords(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.searcher.
Referenced by it.emarolab.cagg.core.evaluation.interfacing.EvaluatorBase< G extends GrammarBase< ?extends SemanticExpressionTreeBase >, F extends InputFormatterBase >.EvaluationResults.EvaluationResults().
List< Facts<Long> > it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.getUnfeasibleFacts ()
Definition at line 103 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.searcher.
Integer it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.getUnfeasibleFactsCount ()
Definition at line 91 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.searcher.
List< String> it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.getUsedWords (int idx)
Definition at line 123 of file ThreadedInputFormatter.java.
boolean it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.isRunning ()
Definition at line 80 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.searcher.
void it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.join ()
Definition at line 67 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.CaggThread.isRunning(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.searcher.
void it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.start ()
Definition at line 48 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.DEFAULT_THREAD_NAME.
void it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.start (String threadName)
Definition at line 51 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.getLoggerName(), it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.getTokenisedInputs(), it.emarolab.cagg.core.evaluation.CaggThread.isRunning(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.searcher.
void it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.stop ()
Definition at line 59 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.CaggThread.isRunning(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.searcher, and it.emarolab.cagg.core.evaluation.CaggThread.terminate().
Member Data Documentation
final String it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.DEFAULT_THREAD_NAME = "th-form" static
Definition at line 19 of file ThreadedInputFormatter.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.start().
Integer it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.factsIdx private
Definition at line 25 of file ThreadedInputFormatter.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.FactsSearcher(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.getActualFactsIdx(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.getNextFacts().
FactsSearcher it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.searcher = null private
Definition at line 24 of file ThreadedInputFormatter.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.getFactsCount(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.getNextFacts(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.getSearcher(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.getSkippedWords(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.getUnfeasibleFacts(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.getUnfeasibleFactsCount(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.isRunning(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.join(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.start(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.stop().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/evaluation/inputFormatting/ThreadedInputFormatter.java