ConceptActionGrammarGenerator: it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher Class Reference
it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher Class Reference
Public Member Functions
void implement ()
List< Set< SkippedWord > > getSkippedWords ()
Set< SkippedWord > getSkippedWords (int idx)
List< List< String > > getUsedWords ()
List< String > getUsedWords (int idx)
Integer getSolutionDiscoveredCount ()
Integer getUnfeasibleSolutionDiscoveredCount ()
List< Facts< Long > > getAllTrueFacts ()
Facts< Long > getTrueFact (int idx)
List< Facts< Long > > getAllUnfeasibleFacts ()
Facts< Long > getUnfeasibleFact (int idx)
Public Member Functions inherited from it.emarolab.cagg.core.evaluation.CaggThread
CaggThread ()
CaggThread (String name)
CaggThread (String name, String loggerName)
synchronized void setThreadName (String threadName)
synchronized void setRunnableId (Long runnableId)
synchronized void setLoggerName (String name)
synchronized void setLoggingStepBack (int loggingStepBack)
synchronized void shouldRun (boolean flag)
synchronized String getFormattedName ()
synchronized String getThreadName ()
synchronized Long getRunnableId ()
synchronized String getLoggerName ()
synchronized int getLoggingStepBack ()
synchronized Long getStartingTime ()
synchronized Long getEndingTime ()
synchronized boolean isRunning ()
synchronized ThreadLogger getThreadLogger ()
synchronized void log (Object msg)
synchronized void logWarning (Object msg)
synchronized void logOk (Object msg)
synchronized void logError (Object msg)
synchronized void logError (Exception e)
synchronized void terminate ()
synchronized void start ()
void run ()
void preImplement ()
abstract void implement ()
void postImplement ()
Protected Member Functions
void reduceInput (List< String > input)
Protected Member Functions inherited from it.emarolab.cagg.core.evaluation.CaggThread
synchronized Long getTimeStamp ()
synchronized Long getRunningTime ()
Private Member Functions
FactsSearcher (String threadName, String loggerName, List< String > userInput)
void combineInputs ()
List< Long > combineRecorsive (Integer idx, List< Long > inputIds)
Boolean isInSkipped (int idx)
GrammarBase< ?extends
SemanticExpressionTreeBase >
.TermOccurenceCollector getTermOccurence (Long startingId, Integer idx)
GrammarBase< ?extends
SemanticExpressionTreeBase >
.TermOccurenceCollector getTermOccurence (Long startingId, String definition)
List< Long > copyListIterative (List< Long > list)
void storeFeasibleSolution (List< Long > inputIds)
void storeUnfeasibleSolution (List< Long > inputIds, List< Long > unfeasibleCombination)
Private Attributes
Integer solutionDiscovered = 0
List< Facts< Long > > trueFacts = new ArrayList<>()
List< Facts< Long > > unfeasibleFacts = new ArrayList<>()
List< String > userInput
List< List< String > > actualEvaluatedInput = new ArrayList<>()
List< Set< SkippedWord > > skippedWords = new ArrayList<>()
Set< SkippedWord > skipped = null
Boolean alreadyLoggedFlag
Additional Inherited Members
Static Public Attributes inherited from it.emarolab.cagg.core.evaluation.CaggThread
static final String DEFAULT_NAME_LOGGER = CaggLoggersManager.DEFAULT_LOGGING_NAME_UI
static final String DEFAULT_NAME_THREAD = "CaggThread"
static final int DEFAULT_LOG_STEP_BACK = 3
static final String SYST_PROPERTY_RUNNABLE_NAME = "caggLoggerThread"
Detailed Description
Definition at line 146 of file ThreadedInputFormatter.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.FactsSearcher (String threadName, String loggerName, List< String > userInput) private
Definition at line 158 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.factsIdx, it.emarolab.cagg.core.evaluation.CaggThread.getThreadLogger(), it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.setThreadLogger(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.userInput.
Member Function Documentation
void it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineInputs () private
Definition at line 193 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineRecorsive(), it.emarolab.cagg.core.evaluation.CaggThread.log(), it.emarolab.cagg.core.evaluation.CaggThread.logWarning(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.trueFacts, it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.unfeasibleFacts, and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.userInput.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.implement().
List< Long> it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineRecorsive (Integer idx, List< Long > inputIds) private
Definition at line 201 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.alreadyLoggedFlag, it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.copyListIterative(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getTermOccurence(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.isInSkipped(), it.emarolab.cagg.core.evaluation.CaggThread.isRunning(), it.emarolab.cagg.core.evaluation.CaggThread.log(), it.emarolab.cagg.core.evaluation.CaggThread.logWarning(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.skipped, it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.storeFeasibleSolution(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.storeUnfeasibleSolution(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.userInput.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineInputs().
List< Long> it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.copyListIterative (List< Long > list) private
Definition at line 267 of file ThreadedInputFormatter.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineRecorsive().
List< Facts< Long> > it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getAllTrueFacts ()
Definition at line 379 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.trueFacts.
List< Facts< Long> > it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getAllUnfeasibleFacts ()
Definition at line 400 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.unfeasibleFacts.
List< Set< SkippedWord> > it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getSkippedWords ()
Definition at line 328 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.skippedWords, and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.trueFacts.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.getSkippedWords(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getSkippedWords().
Set< SkippedWord> it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getSkippedWords (int idx)
Definition at line 333 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getSkippedWords(), it.emarolab.cagg.core.evaluation.CaggThread.isRunning(), it.emarolab.cagg.core.evaluation.CaggThread.logError(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.skippedWords, and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.trueFacts.
Integer it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getSolutionDiscoveredCount ()
Definition at line 372 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.solutionDiscovered.
GrammarBase< ? extends SemanticExpressionTreeBase>.TermOccurenceCollector it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getTermOccurence (Long startingId, Integer idx) private
Definition at line 259 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.userInput.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineRecorsive().
GrammarBase< ? extends SemanticExpressionTreeBase>.TermOccurenceCollector it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getTermOccurence (Long startingId, String definition) private
Definition at line 263 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.getGrammar().
Facts< Long> it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getTrueFact (int idx)
Definition at line 384 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.CaggThread.isRunning(), it.emarolab.cagg.core.evaluation.CaggThread.logError(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.trueFacts.
Facts< Long> it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getUnfeasibleFact (int idx)
Definition at line 405 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.CaggThread.isRunning(), it.emarolab.cagg.core.evaluation.CaggThread.logError(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.unfeasibleFacts.
Integer it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getUnfeasibleSolutionDiscoveredCount ()
Definition at line 375 of file ThreadedInputFormatter.java.
List< List< String> > it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getUsedWords ()
Definition at line 350 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.actualEvaluatedInput, and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.trueFacts.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getUsedWords().
List< String> it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getUsedWords (int idx)
Definition at line 355 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.actualEvaluatedInput, it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getUsedWords(), it.emarolab.cagg.core.evaluation.CaggThread.isRunning(), it.emarolab.cagg.core.evaluation.CaggThread.logError(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.trueFacts.
void it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.implement ()
Definition at line 173 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineInputs(), it.emarolab.cagg.core.evaluation.CaggThread.log(), it.emarolab.cagg.debugging.DebuggingDefaults.NANOSEC_2_SEC, it.emarolab.cagg.core.evaluation.CaggThread.shouldRun(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.skipped, it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.trueFacts, it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.unfeasibleFacts, and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.userInput.
Boolean it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.isInSkipped (int idx) private
Definition at line 243 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.skipped, and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.skippedWords.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineRecorsive().
void it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.reduceInput (List< String > input) protected
Definition at line 169 of file ThreadedInputFormatter.java.
void it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.storeFeasibleSolution (List< Long > inputIds) private
Definition at line 274 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.skipped, it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.solutionDiscovered, it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.trueFacts, and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.userInput.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineRecorsive().
void it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.storeUnfeasibleSolution (List< Long > inputIds, List< Long > unfeasibleCombination) private
Definition at line 308 of file ThreadedInputFormatter.java.
References it.emarolab.cagg.core.evaluation.inputFormatting.InputFormatterBase.SHOULD_COLLECT_UNFEASIBLE_FACTS, and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.unfeasibleFacts.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineRecorsive().
Member Data Documentation
List< List< String> > it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.actualEvaluatedInput = new ArrayList<>() private
Definition at line 152 of file ThreadedInputFormatter.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getUsedWords().
Boolean it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.alreadyLoggedFlag private
Definition at line 155 of file ThreadedInputFormatter.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineRecorsive().
Set<SkippedWord> it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.skipped = null private
Definition at line 154 of file ThreadedInputFormatter.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineRecorsive(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.implement(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.isInSkipped(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.storeFeasibleSolution().
List< Set< SkippedWord> > it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.skippedWords = new ArrayList<>() private
Definition at line 153 of file ThreadedInputFormatter.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getSkippedWords(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.isInSkipped().
Integer it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.solutionDiscovered = 0 private
Definition at line 148 of file ThreadedInputFormatter.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getSolutionDiscoveredCount(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.storeFeasibleSolution().
List< Facts< Long> > it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.trueFacts = new ArrayList<>() private
Definition at line 149 of file ThreadedInputFormatter.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineInputs(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getAllTrueFacts(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getSkippedWords(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getTrueFact(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getUsedWords(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.implement(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.storeFeasibleSolution().
List< Facts< Long> > it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.unfeasibleFacts = new ArrayList<>() private
Definition at line 150 of file ThreadedInputFormatter.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineInputs(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getAllUnfeasibleFacts(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getUnfeasibleFact(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.implement(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.storeUnfeasibleSolution().
List< String> it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.userInput private
Definition at line 151 of file ThreadedInputFormatter.java.
Referenced by it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineInputs(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.combineRecorsive(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.FactsSearcher(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.getTermOccurence(), it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.implement(), and it.emarolab.cagg.core.evaluation.inputFormatting.ThreadedInputFormatter.FactsSearcher.storeFeasibleSolution().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/evaluation/inputFormatting/ThreadedInputFormatter.java