ConceptActionGrammarGenerator: it.emarolab.cagg.interfaces.CaggCompiler Class Reference
it.emarolab.cagg.interfaces.CaggCompiler Class Reference
Public Member Functions
CaggCompiler (String[] sourcesPath, String serialisationPath)
CaggCompiler (String paths, String serialisationPath)
CaggCompiler (String[] sourcesPath)
CaggCompiler (String paths)
List< String > getSourcesPath ()
String getSerialisationPath ()
List< TextualParser > getParsers ()
GrammarBase< SemanticTree > getGrammar ()
void setSerialisationPath (String path)
void serialise ()
GrammarBase< SemanticTree > deserialise ()
Static Public Member Functions
static GrammarBase< SemanticTree > deserialise (String path)
static GrammarBase< SemanticTree > deserialise (String path, String alias)
Private Member Functions
void initialise (List< String > sourcesPath, String serialisationPath)
Private Attributes
List< String > sourcesPath
String serialisationPath
List< TextualParser > parsers = new ArrayList<>()
GrammarBase< SemanticTree > grammar
Static Private Attributes
static Integer textualParseIdentifier = 0
Detailed Description
Definition at line 15 of file CaggCompiler.java.
Constructor & Destructor Documentation
it.emarolab.cagg.interfaces.CaggCompiler.CaggCompiler (String[] sourcesPath, String serialisationPath)
Definition at line 27 of file CaggCompiler.java.
References it.emarolab.cagg.interfaces.CaggCompiler.initialise(), and it.emarolab.cagg.interfaces.CaggCompiler.serialisationPath.
it.emarolab.cagg.interfaces.CaggCompiler.CaggCompiler (String paths, String serialisationPath)
Definition at line 30 of file CaggCompiler.java.
References it.emarolab.cagg.interfaces.CaggCompiler.initialise(), and it.emarolab.cagg.interfaces.CaggCompiler.sourcesPath.
it.emarolab.cagg.interfaces.CaggCompiler.CaggCompiler (String[] sourcesPath)
Definition at line 35 of file CaggCompiler.java.
References it.emarolab.cagg.interfaces.CaggCompiler.initialise().
it.emarolab.cagg.interfaces.CaggCompiler.CaggCompiler (String paths)
Definition at line 38 of file CaggCompiler.java.
References it.emarolab.cagg.interfaces.CaggCompiler.initialise(), and it.emarolab.cagg.interfaces.CaggCompiler.sourcesPath.
Member Function Documentation
GrammarBase< SemanticTree> it.emarolab.cagg.interfaces.CaggCompiler.deserialise ()
Definition at line 87 of file CaggCompiler.java.
References it.emarolab.cagg.interfaces.CaggCompiler.serialisationPath.
static GrammarBase< SemanticTree> it.emarolab.cagg.interfaces.CaggCompiler.deserialise (String path) static
Definition at line 94 of file CaggCompiler.java.
static GrammarBase< SemanticTree> it.emarolab.cagg.interfaces.CaggCompiler.deserialise (String path, String alias) static
Definition at line 98 of file CaggCompiler.java.
GrammarBase< SemanticTree> it.emarolab.cagg.interfaces.CaggCompiler.getGrammar ()
Definition at line 73 of file CaggCompiler.java.
References it.emarolab.cagg.interfaces.CaggCompiler.grammar.
List<TextualParser> it.emarolab.cagg.interfaces.CaggCompiler.getParsers ()
Definition at line 70 of file CaggCompiler.java.
References it.emarolab.cagg.interfaces.CaggCompiler.parsers.
String it.emarolab.cagg.interfaces.CaggCompiler.getSerialisationPath ()
Definition at line 67 of file CaggCompiler.java.
References it.emarolab.cagg.interfaces.CaggCompiler.serialisationPath.
List<String> it.emarolab.cagg.interfaces.CaggCompiler.getSourcesPath ()
Definition at line 64 of file CaggCompiler.java.
References it.emarolab.cagg.interfaces.CaggCompiler.sourcesPath.
void it.emarolab.cagg.interfaces.CaggCompiler.initialise (List< String > sourcesPath, String serialisationPath) private
Definition at line 43 of file CaggCompiler.java.
References it.emarolab.cagg.interfaces.CaggCompiler.grammar, it.emarolab.cagg.interfaces.CaggCompiler.parsers, it.emarolab.cagg.interfaces.CaggCompiler.serialisationPath, it.emarolab.cagg.interfaces.CaggCompiler.sourcesPath, and it.emarolab.cagg.interfaces.CaggCompiler.textualParseIdentifier.
Referenced by it.emarolab.cagg.interfaces.CaggCompiler.CaggCompiler().
void it.emarolab.cagg.interfaces.CaggCompiler.serialise ()
Definition at line 84 of file CaggCompiler.java.
References it.emarolab.cagg.interfaces.CaggCompiler.serialisationPath.
void it.emarolab.cagg.interfaces.CaggCompiler.setSerialisationPath (String path)
Definition at line 78 of file CaggCompiler.java.
Member Data Documentation
GrammarBase< SemanticTree> it.emarolab.cagg.interfaces.CaggCompiler.grammar private
Definition at line 23 of file CaggCompiler.java.
Referenced by it.emarolab.cagg.interfaces.CaggCompiler.getGrammar(), and it.emarolab.cagg.interfaces.CaggCompiler.initialise().
List< TextualParser> it.emarolab.cagg.interfaces.CaggCompiler.parsers = new ArrayList<>() private
Definition at line 22 of file CaggCompiler.java.
Referenced by it.emarolab.cagg.interfaces.CaggCompiler.getParsers(), and it.emarolab.cagg.interfaces.CaggCompiler.initialise().
String it.emarolab.cagg.interfaces.CaggCompiler.serialisationPath private
Definition at line 21 of file CaggCompiler.java.
Referenced by it.emarolab.cagg.interfaces.CaggCompiler.CaggCompiler(), it.emarolab.cagg.interfaces.CaggCompiler.deserialise(), it.emarolab.cagg.interfaces.CaggCompiler.getSerialisationPath(), it.emarolab.cagg.interfaces.CaggCompiler.initialise(), and it.emarolab.cagg.interfaces.CaggCompiler.serialise().
List< String> it.emarolab.cagg.interfaces.CaggCompiler.sourcesPath private
Definition at line 20 of file CaggCompiler.java.
Referenced by it.emarolab.cagg.interfaces.CaggCompiler.CaggCompiler(), it.emarolab.cagg.interfaces.CaggCompiler.getSourcesPath(), and it.emarolab.cagg.interfaces.CaggCompiler.initialise().
Integer it.emarolab.cagg.interfaces.CaggCompiler.textualParseIdentifier = 0 static private
Definition at line 19 of file CaggCompiler.java.
Referenced by it.emarolab.cagg.interfaces.CaggCompiler.initialise().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/interfaces/CaggCompiler.java