ConceptActionGrammarGenerator: it.emarolab.cagg.core.language.parser.TextualParser Class Reference
it.emarolab.cagg.core.language.parser.TextualParser Class Reference
Public Member Functions
TextualParser (String toParse, Boolean fromFile, Integer id)
TextualParser (String toParse, Integer id)
String toString ()
Integer getId ()
AbstractSyntaxNode<?> getASTree ()
AbstractSyntaxNode<?> getASPreambleTree ()
AbstractSyntaxNode<?> getASBodyTree ()
boolean hasError ()
Static Public Member Functions
static Boolean isStringLiteral (String baseLit)
static String removePrefix (String baseStr, String prefix)
static String getWordBetweenSymbols (String baseStr, String startSymb, String endSymb)
static String getWordBetweenSymbols (String baseStr, String startSymb, String endSymb, Boolean lastOf)
static String removeWordBetweenTwoSymbols (String baseStr, String startSymb, String endSymb)
static String removeDeclaration (String baseStr)
static String retrieveString (String baseStr)
static String retrieveDeclaration (String baseStr)
static String retrieveDirectiveContent (ParserRuleContext ctx, String declaration)
static List< String > retrieveDirectiveContents (ParserRuleContext ctx, String declaration)
Static Public Attributes
static final String DEFAULT_SEPARATOR = ","
static final String DEFAULT_BEGINNING = "!"
static final String DEFAULT_OPEN = "("
static final String DEFAULT_CLOSE = ")"
static final String DEFAULT_STRING_IDENTIFIER = "\""
static final String DEFAULT_REMOVING_REPLACE = ""
static final String DEFAULT_DECLARATION_OPEN = "<"
static final String DEFAULT_DECLARATION_CLOSE = ">"
Protected Member Functions
CAGGSyntaxDefinitionLexer instanciateLexer (ANTLRInputStream stream)
CAGGSyntaxDefinitionParser instanciateParse (CAGGSyntaxDefinitionLexer lexer)
NuanceGrammarContext startParser (CAGGSyntaxDefinitionParser parser)
Private Member Functions
void initialise (Integer id)
Private Attributes
Integer id = null
Boolean hasError
Detailed Description
Version
Concept-Action Grammar Generator 1.1
File: src//cagg.core.sourceInterface.parser.TextualParser.java
Author
Buoncompagni Luca
DIBRIS, emaroLab,
University of Genoa.
15/gen/2016
This class extends ParserBase object with parameter set to: CAGGSyntaxDefinitionLexer, CAGGSyntaxDefinitionParser, NuanceGrammarContext and ParserListener; respectively.
It purposes is to activate the parsing procedure and get a populated Abstract Syntax Tree (AST). For doing so, it requires a source text to be parsed in order to create the Parsing Tree (PT) and then walk over it to create the AST by using a listener (this is done in class constructor).
Last but not the least, this class also implements static methods used to manipulate strings and detach information during parsing.
See Also
ParserBase
ParserListener
Definition at line 41 of file TextualParser.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.language.parser.TextualParser.TextualParser (String toParse, Boolean fromFile, Integer id)
This constructor simple rely on ParserBase#ParserBase(String, Boolean) by using:
toParse
and
fromFile
as input parameters respectively. Further it initialises this class
id
with respect to the input specification. This is used mainly for visualisation and debugging. Finally, this constructor also creates a new ParserListener and set it as listener through the method: setListener(ParseTreeListener).
Parameters
toParse the text to be parsed (if
fromFile
is
false
). Or the path to the file to be parsed (if
from file
is
true
).
fromFile identifies if the parameter
toParse
is the text to be parsed (
false
) or the path to the file to be parsed (
false
).
id the identifier to be assigned to this object.
Definition at line 99 of file TextualParser.java.
References it.emarolab.cagg.core.language.parser.TextualParser.initialise().
it.emarolab.cagg.core.language.parser.TextualParser.TextualParser (String toParse, Integer id)
This constructor simple rely on ParserBase#ParserBase(String) by using:
toParse
as input parameter. Further it initialises this class
id
with respect to the input specification. This is used mainly for visualisation and debugging. Finally, this constructor also creates a new ParserListener and set it as listener through the method: setListener(ParseTreeListener).
Parameters
toParse the source text to be parsed.
id the identifier to be assigned to this object.
Definition at line 113 of file TextualParser.java.
References it.emarolab.cagg.core.language.parser.TextualParser.initialise().
Member Function Documentation
AbstractSyntaxNode<?> it.emarolab.cagg.core.language.parser.TextualParser.getASBodyTree ()
This method, returns the preamble node of a copy of the Abstract Syntax Tree generated during parsing. In particular, it is generated by walking through the Parsing Tree and by applying the listener created on constructor (TextualParser(String, Integer) or TextualParser(String, Boolean, Integer)). More in details, the tree is given by querying: ParserListener#getAstPreamble() and then the copy is given by calling: AbstractSyntaxNode#copyTree().
Returns
a copy of the Abstract Syntax Tree preamble node. This method, returns the body node of the Abstract Syntax Tree generated during parsing. In particular, it is generated by walking through the Parsing Tree and by applying the listener created on constructor (TextualParser(String, Integer) or TextualParser(String, Boolean, Integer)). More in details, the tree is given by querying: ParserListener#getAstBody().
the Abstract Syntax Tree body node.
Definition at line 209 of file TextualParser.java.
AbstractSyntaxNode<?> it.emarolab.cagg.core.language.parser.TextualParser.getASPreambleTree ()
This method, returns the root node of a copy of the Abstract Syntax Tree generated during parsing. In particular, it is generated by walking through the Parsing Tree and by applying the listener created on constructor (TextualParser(String, Integer) or TextualParser(String, Boolean, Integer)). More in details, the tree is given by querying: ParserListener#getAstRoot() and then the copy is given by calling: AbstractSyntaxNode#copyTree().
Returns
a copy of the Abstract Syntax Tree root node. This method, returns the preamble node of the Abstract Syntax Tree generated during parsing. In particular, it is generated by walking through the Parsing Tree and by applying the listener created on constructor (TextualParser(String, Integer) or TextualParser(String, Boolean, Integer)). More in details, the tree is given by querying: ParserListener#getAstPreamble().
the Abstract Syntax Tree preamble node.
Definition at line 190 of file TextualParser.java.
AbstractSyntaxNode<?> it.emarolab.cagg.core.language.parser.TextualParser.getASTree ()
This method, returns the root node of the Abstract Syntax Tree generated during parsing. In particular, it is generated by walking through the Parsing Tree and by applying the listener created on constructor (TextualParser(String, Integer) or TextualParser(String, Boolean, Integer)). More in details, the tree is given by querying: ParserListener#getAstRoot().
Returns
the Abstract Syntax Tree root node.
Definition at line 171 of file TextualParser.java.
Integer it.emarolab.cagg.core.language.parser.TextualParser.getId ()
Returns
the
id
assigned to this object on constructors (TextualParser(String, Integer) or TextualParser(String, Boolean, Integer)). This is used mainly for visualisation or debugging purposes.
Definition at line 161 of file TextualParser.java.
References it.emarolab.cagg.core.language.parser.TextualParser.id.
static String it.emarolab.cagg.core.language.parser.TextualParser.getWordBetweenSymbols (String baseStr, String startSymb, String endSymb) static
This method calls: getWordBetweenSymbols(String, String, String, Boolean) with:
baseStr
,
startsSymb
,
endSymb
and
false
; respectively.
Parameters
baseStr the string from where retrieve the set of chars between symbols.
startSymb the starting symbol type that defines the set of chars returned by this method.
endSymb the ending symbol type that defines the set of chars returned by this method.
Returns
the chars of
baseStr
that are within the symbols:
startSymb
and
endSymb
. (The first occurrence).
Definition at line 265 of file TextualParser.java.
Referenced by it.emarolab.cagg.core.language.parser.TextualParser.removeWordBetweenTwoSymbols(), it.emarolab.cagg.core.language.parser.TextualParser.retrieveDeclaration(), and it.emarolab.cagg.core.language.parser.TextualParser.retrieveString().
static String it.emarolab.cagg.core.language.parser.TextualParser.getWordBetweenSymbols (String baseStr, String startSymb, String endSymb, Boolean lastOf) static
This method relies on:
String#indexOf(int)
,
String#lastIndexOf(int)
and
String#substring(int, int)
in order to get the chars of an input string that are between two symbols. By searching for the first or last occurrence.
Parameters
baseStr the string from where retrieve the set of chars between symbols.
startSymb the starting symbol type that defines the set of chars returned by this method.
endSymb the ending symbol type that defines the set of chars returned by this method.
lastOf if it is
true
the method looks for the last occurrence of the
startSymb
and
endSymb
. While, if it is
false
it looks for the first occurrence.
Returns
the set of chars that are between the two given symbols (excluded).
Definition at line 280 of file TextualParser.java.
boolean it.emarolab.cagg.core.language.parser.TextualParser.hasError ()
This method, returns the body node of a copy of the Abstract Syntax Tree generated during parsing. In particular, it is generated by walking through the Parsing Tree and by applying the listener created on constructor (TextualParser(String, Integer) or TextualParser(String, Boolean, Integer)). More in details, the tree is given by querying: ParserListener#getAstBody() and then the copy is given by calling: AbstractSyntaxNode#copyTree().
Returns
a copy of the Abstract Syntax Tree body node.
true
if at lest an error occurred during parsing perfomed on constructor.
Definition at line 224 of file TextualParser.java.
Referenced by it.emarolab.cagg.core.language.parser.TextualParser.initialise().
void it.emarolab.cagg.core.language.parser.TextualParser.initialise (Integer id) private
Definition at line 118 of file TextualParser.java.
References it.emarolab.cagg.core.language.parser.TextualParser.hasError(), and it.emarolab.cagg.core.language.parser.TextualParser.id.
Referenced by it.emarolab.cagg.core.language.parser.TextualParser.TextualParser().
CAGGSyntaxDefinitionLexer it.emarolab.cagg.core.language.parser.TextualParser.instanciateLexer (ANTLRInputStream stream) protected
Definition at line 126 of file TextualParser.java.
CAGGSyntaxDefinitionParser it.emarolab.cagg.core.language.parser.TextualParser.instanciateParse (CAGGSyntaxDefinitionLexer lexer) protected
Definition at line 130 of file TextualParser.java.
static Boolean it.emarolab.cagg.core.language.parser.TextualParser.isStringLiteral (String baseLit) static
This method returns
true
if the calls
baseLit.contains({@value #DEFAULT_STRING_IDENTIFIER})
returns
true
.
false
otherwise.
Parameters
baseLit the string to be checked (if it is a string literal or not).
Returns
true
if
baseLit
is a string literal.
false
otherwise.
Definition at line 236 of file TextualParser.java.
References it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_STRING_IDENTIFIER.
Referenced by it.emarolab.cagg.core.language.syntax.abstractTree.syntaxNodeType.GrammarSyntaxNode.assignData(), and it.emarolab.cagg.core.language.syntax.abstractTree.syntaxNodeType.PronounceSyntaxNode.setName().
static String it.emarolab.cagg.core.language.parser.TextualParser.removeDeclaration (String baseStr) static
This method calls: removeWordBetweenTwoSymbols(String, String, String) with:
baseStr
, { DEFAULT_DECLARATION_OPEN} and { DEFAULT_DECLARATION_CLOSE} input parameters respectively.
Parameters
baseStr the string from where remove the set of chars between symbols.
Returns
a copy of
baseStr
that does not have the first occurrence of the words between two symbols anymore (symbols: { DEFAULT_DECLARATION_OPEN} and { DEFAULT_DECLARATION_CLOSE}). This method also removes the specified starting and ending symbols.
Definition at line 316 of file TextualParser.java.
References it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_DECLARATION_CLOSE, it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_DECLARATION_OPEN, and it.emarolab.cagg.core.language.parser.TextualParser.removeWordBetweenTwoSymbols().
static String it.emarolab.cagg.core.language.parser.TextualParser.removePrefix (String baseStr, String prefix) static
This method remove a prefix from a string by returning:
baseStr.substring(prefix.length(), baseStr.length())
.
Parameters
baseStr the string from which remove the prefix
prefix the prefix to be removed from
baseStr
.
Returns
the a copy of the
baseStr
where a number of char equals to the length of
prefix
is removed (from the beginning of the base string).
See Also
String::substring(int, int)
Definition at line 251 of file TextualParser.java.
static String it.emarolab.cagg.core.language.parser.TextualParser.removeWordBetweenTwoSymbols (String baseStr, String startSymb, String endSymb) static
This method calls: getWordBetweenSymbols(String, String, String) with:
baseStr
,
startSymb
and
endSymb
input parameters respectively. Then, it returns:
baseStr.replace(startSymb + toRemove + endSymb, {@value #DEFAULT_REMOVING_REPLACE})
where
toRemove
is the string returning from the previous call.
Parameters
baseStr the string from where remove the set of chars between symbols.
startSymb the starting symbol type that defines the set of chars removed by this method.
endSymb the ending symbol type that defines the set of chars removed by this method.
Returns
a copy of
baseStr
that does not have the first occurrence of the words between two symbols anymore. This method also removes the specified starting and ending symbols.
Definition at line 304 of file TextualParser.java.
References it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_REMOVING_REPLACE, and it.emarolab.cagg.core.language.parser.TextualParser.getWordBetweenSymbols().
Referenced by it.emarolab.cagg.core.language.parser.TextualParser.removeDeclaration().
static String it.emarolab.cagg.core.language.parser.TextualParser.retrieveDeclaration (String baseStr) static
This method calls: getWordBetweenSymbols(String, String, String) with:
baseStr
, { DEFAULT_DECLARATION_OPEN}, { DEFAULT_DECLARATION_CLOSE}; respectively.
Parameters
baseStr the string from where retrieving the declaration literal.
Returns
the first set of chars of
baseStr
within the symbols: { DEFAULT_DECLARATION_OPEN} and { DEFAULT_DECLARATION_CLOSE}.
Definition at line 342 of file TextualParser.java.
References it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_DECLARATION_CLOSE, it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_DECLARATION_OPEN, and it.emarolab.cagg.core.language.parser.TextualParser.getWordBetweenSymbols().
Referenced by it.emarolab.cagg.core.language.syntax.expressionTree.expressionNodeType.TermExpressionNode.parse().
static String it.emarolab.cagg.core.language.parser.TextualParser.retrieveDirectiveContent (ParserRuleContext ctx, String declaration) static
This method looks into the string ParserRuleContext#getText() of all the children of the input parameter
ctx
and returns it (first occurence) if it not equals to: { DEFAULT_BEGINNING},
declaration
, { DEFAULT_OPEN} and { DEFAULT_CLOSE}. Otherwise it returns an empty string.
Parameters
ctx the parsing tree context from which get child and text to check.
declaration an optional child content text to be discarder.
Returns
the first text of the child of
ctx
that it is not equal to the standard grammar declarative literals.
Definition at line 355 of file TextualParser.java.
References it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_BEGINNING, it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_CLOSE, and it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_OPEN.
static List< String> it.emarolab.cagg.core.language.parser.TextualParser.retrieveDirectiveContents (ParserRuleContext ctx, String declaration) static
This method looks into the string ParserRuleContext#getText() of all the children of the input parameter
ctx
and returns it for all the occurences in which it is not equals to: { DEFAULT_BEGINNING},
declaration
, { DEFAULT_OPEN}, { DEFAULT_SEPARATOR} and { DEFAULT_CLOSE}. Otherwise it returns an empty list.
Parameters
ctx the parsing tree context from which get child and text to check.
declaration an optional child content text to be discarder.
Returns
the all texts of the children of
ctx
that it are not equal to the standard grammar declarative literals.
Definition at line 377 of file TextualParser.java.
References it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_BEGINNING, it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_CLOSE, it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_OPEN, and it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_SEPARATOR.
static String it.emarolab.cagg.core.language.parser.TextualParser.retrieveString (String baseStr) static
This method calls: getWordBetweenSymbols(String, String, String, Boolean) with:
baseStr
, { DEFAULT_STRING_IDENTIFIER}, { DEFAULT_STRING_IDENTIFIER} and
true
; respectively. Finally, it removes all the occurrences of
{@value #DEFAULT_STRING_IDENTIFIER}{@value #DEFAULT_STRING_IDENTIFIER}
with:
{@value #DEFAULT_STRING_IDENTIFIER}
.
Parameters
baseStr the string from where retrieving the string literal.
Returns
the last set of chars of
baseStr
within the symbol { DEFAULT_STRING_IDENTIFIER}; where possible double occurrences of
{@value #DEFAULT_STRING_IDENTIFIER} + {@value #DEFAULT_STRING_IDENTIFIER}
are substituted with:
{@value #DEFAULT_STRING_IDENTIFIER}
.
Definition at line 331 of file TextualParser.java.
References it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_STRING_IDENTIFIER, and it.emarolab.cagg.core.language.parser.TextualParser.getWordBetweenSymbols().
Referenced by it.emarolab.cagg.core.language.syntax.abstractTree.syntaxNodeType.LanguageSyntaxNode.assignData(), it.emarolab.cagg.core.language.syntax.abstractTree.syntaxNodeType.GrammarSyntaxNode.assignData(), it.emarolab.cagg.core.language.syntax.expressionTree.expressionNodeType.LabelExpressionNode.parse(), and it.emarolab.cagg.core.language.syntax.expressionTree.expressionNodeType.TermExpressionNode.parse().
NuanceGrammarContext it.emarolab.cagg.core.language.parser.TextualParser.startParser (CAGGSyntaxDefinitionParser parser) protected
This method specify the main ANTLR rule with respect to which the parser starts. Particularly, it is set to:
parser.nuanceGrammar()
See Also
ParserBase::startParser(Parser)
Definition at line 139 of file TextualParser.java.
String it.emarolab.cagg.core.language.parser.TextualParser.toString ()
This method describes this object with a string for visualisation and debugging purposes. It simply returns:
"grammarId:" + id
, where
id
is the value given on class constructors (TextualParser(String, Integer) or TextualParser(String, Boolean, Integer)).
See Also
it.emarolab.cagg.core.language.parser.ANTLRInterface.ParserBase::toString()
Definition at line 149 of file TextualParser.java.
References it.emarolab.cagg.core.language.parser.TextualParser.id.
Member Data Documentation
final String it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_BEGINNING = "!" static
The default directive beginning symbol of the grammar. By default set to { "!"}.
Definition at line 53 of file TextualParser.java.
Referenced by it.emarolab.cagg.core.language.parser.TextualParser.retrieveDirectiveContent(), and it.emarolab.cagg.core.language.parser.TextualParser.retrieveDirectiveContents().
final String it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_CLOSE = ")" static
The default expression ending symbol of the grammar. By default set to { ")"}.
Definition at line 61 of file TextualParser.java.
Referenced by it.emarolab.cagg.core.language.parser.TextualParser.retrieveDirectiveContent(), and it.emarolab.cagg.core.language.parser.TextualParser.retrieveDirectiveContents().
final String it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_DECLARATION_CLOSE = ">" static
The default declaration ending symbol of the grammar. By default set to { ">"}.
Definition at line 77 of file TextualParser.java.
Referenced by it.emarolab.cagg.core.language.parser.TextualParser.removeDeclaration(), and it.emarolab.cagg.core.language.parser.TextualParser.retrieveDeclaration().
final String it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_DECLARATION_OPEN = "<" static
The default declaration starting symbol of the grammar. By default set to { "<"}.
Definition at line 73 of file TextualParser.java.
Referenced by it.emarolab.cagg.core.language.parser.TextualParser.removeDeclaration(), and it.emarolab.cagg.core.language.parser.TextualParser.retrieveDeclaration().
final String it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_OPEN = "(" static
The default expression opening symbol of the grammar. By default set to { "("}.
Definition at line 57 of file TextualParser.java.
Referenced by it.emarolab.cagg.core.language.parser.TextualParser.retrieveDirectiveContent(), and it.emarolab.cagg.core.language.parser.TextualParser.retrieveDirectiveContents().
final String it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_REMOVING_REPLACE = "" static
The default symbol replaced to the chars to be removed. By default set to { ""}.
Definition at line 69 of file TextualParser.java.
Referenced by it.emarolab.cagg.core.language.parser.TextualParser.removeWordBetweenTwoSymbols().
final String it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_SEPARATOR = "," static
The default data separator symbol of the grammar. By default set to { ","}.
Definition at line 49 of file TextualParser.java.
Referenced by it.emarolab.cagg.core.language.parser.TextualParser.retrieveDirectiveContents().
final String it.emarolab.cagg.core.language.parser.TextualParser.DEFAULT_STRING_IDENTIFIER = "\"" static
The default string identifying symbol of the grammar. By default set to { "\""}.
Definition at line 65 of file TextualParser.java.
Referenced by it.emarolab.cagg.core.language.parser.TextualParser.isStringLiteral(), and it.emarolab.cagg.core.language.parser.TextualParser.retrieveString().
Boolean it.emarolab.cagg.core.language.parser.TextualParser.hasError private
Definition at line 82 of file TextualParser.java.
Integer it.emarolab.cagg.core.language.parser.TextualParser.id = null private
Definition at line 81 of file TextualParser.java.
Referenced by it.emarolab.cagg.core.language.parser.TextualParser.getId(), it.emarolab.cagg.core.language.parser.TextualParser.initialise(), and it.emarolab.cagg.core.language.parser.TextualParser.toString().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/language/parser/TextualParser.java