ConceptActionGrammarGenerator: it.emarolab.cagg.core.language.parser.ParserListener Class Reference
it.emarolab.cagg.core.language.parser.ParserListener Class Reference
Public Member Functions
ParserListener (CAGGSyntaxDefinitionParser parser)
void enterNuanceGrammar (NuanceGrammarContext ctx)
void enterGrammarHearder (GrammarHearderContext ctx)
void enterGrammarDeclaration (GrammarDeclarationContext ctx)
void enterLanguageDeclaration (LanguageDeclarationContext ctx)
void enterExportDeclaration (ExportDeclarationContext ctx)
void enterImportDeclaration (ImportDeclarationContext ctx)
void enterStartDeclaration (StartDeclarationContext ctx)
void enterModifableDeclaration (ModifableDeclarationContext ctx)
void enterActivableDeclaration (ActivableDeclarationContext ctx)
void enterPronounceDeclaration (PronounceDeclarationContext ctx)
void enterPronunceLabel (PronunceLabelContext ctx)
void exitPronounceDeclaration (PronounceDeclarationContext ctx)
void enterOptionalDirective (OptionalDirectiveContext ctx)
void enterLabelDirective (LabelDirectiveContext ctx)
void enterIdDirective (IdDirectiveContext ctx)
void enterActionDirective (ActionDirectiveContext ctx)
void enterPronounceDirective (PronounceDirectiveContext ctx)
void enterRepeatDirective (RepeatDirectiveContext ctx)
void enterBody (BodyContext ctx)
void enterRuleDeclaration (RuleDeclarationContext ctx)
void enterAndOperator (AndOperatorContext ctx)
void enterOrOperator (OrOperatorContext ctx)
void enterRuleTerm (RuleTermContext ctx)
void exitRuleTerm (RuleTermContext ctx)
void enterActionDefinition (ActionDefinitionContext ctx)
void exitBody (BodyContext ctx)
Public Member Functions inherited from it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener
TreeParserListener (CAGGSyntaxDefinitionParser parser)
TreeParserListener (CAGGSyntaxDefinitionParser parser, AbstractSyntaxNode<?> astRoot, AbstractSyntaxNode<?> astPreamble, AbstractSyntaxNode<?> astBody)
void setBaseNodes (AbstractSyntaxNode<?> astRoot, AbstractSyntaxNode<?> astPreamble, AbstractSyntaxNode<?> astBody)
JTree getAbstractSyntaxTree ()
AbstractSyntaxNode<?> getAstRoot ()
AbstractSyntaxNode<?> getAstPreamble ()
AbstractSyntaxNode<?> getAstBody ()
CAGGSyntaxDefinitionParser getParser ()
Public Member Functions inherited from it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener
LogicalParserListener ()
Boolean isInGrammarRoot ()
void enterNuanceGrammar (NuanceGrammarContext ctx)
void exitNuanceGrammar (NuanceGrammarContext ctx)
Boolean isInGrammarPreamble ()
void enterPreamble (PreambleContext ctx)
void exitPreamble (PreambleContext ctx)
void enterGrammarHearder (GrammarHearderContext ctx)
void exitGrammarHearder (GrammarHearderContext ctx)
Boolean isInGrammarBody ()
void enterBody (BodyContext ctx)
void exitBody (BodyContext ctx)
Boolean isInRuleDeclarationPreamble ()
Boolean isInRuleDeclarationBody ()
void enterRuleDeclaration (RuleDeclarationContext ctx)
void exitRuleDeclaration (RuleDeclarationContext ctx)
Boolean isInRuleBody ()
void enterRuleBody (RuleBodyContext ctx)
void exitRuleBody (RuleBodyContext ctx)
Boolean isOrOperation ()
void enterOrOperator (OrOperatorContext ctx)
Boolean isAndOperation ()
void enterAndOperator (AndOperatorContext ctx)
Boolean isRuleTerm ()
void enterRuleTerm (RuleTermContext ctx)
Public Member Functions inherited from it.emarolab.cagg.core.language.parser.ANTLRInterface.ANTLRGenerated.CAGGSyntaxDefinitionBaseListener
void enterExportDeclaration (@NotNull CAGGSyntaxDefinitionParser.ExportDeclarationContext ctx)
void exitExportDeclaration (@NotNull CAGGSyntaxDefinitionParser.ExportDeclarationContext ctx)
void enterActivableDeclaration (@NotNull CAGGSyntaxDefinitionParser.ActivableDeclarationContext ctx)
void exitActivableDeclaration (@NotNull CAGGSyntaxDefinitionParser.ActivableDeclarationContext ctx)
void enterPreamble (@NotNull CAGGSyntaxDefinitionParser.PreambleContext ctx)
void exitPreamble (@NotNull CAGGSyntaxDefinitionParser.PreambleContext ctx)
void enterRuleBody (@NotNull CAGGSyntaxDefinitionParser.RuleBodyContext ctx)
void exitRuleBody (@NotNull CAGGSyntaxDefinitionParser.RuleBodyContext ctx)
void enterRuleTerm (@NotNull CAGGSyntaxDefinitionParser.RuleTermContext ctx)
void exitRuleTerm (@NotNull CAGGSyntaxDefinitionParser.RuleTermContext ctx)
void enterBody (@NotNull CAGGSyntaxDefinitionParser.BodyContext ctx)
void exitBody (@NotNull CAGGSyntaxDefinitionParser.BodyContext ctx)
void enterPronounceDeclaration (@NotNull CAGGSyntaxDefinitionParser.PronounceDeclarationContext ctx)
void exitPronounceDeclaration (@NotNull CAGGSyntaxDefinitionParser.PronounceDeclarationContext ctx)
void enterRepeatDirective (@NotNull CAGGSyntaxDefinitionParser.RepeatDirectiveContext ctx)
void exitRepeatDirective (@NotNull CAGGSyntaxDefinitionParser.RepeatDirectiveContext ctx)
void enterPronunceLabel (@NotNull CAGGSyntaxDefinitionParser.PronunceLabelContext ctx)
void exitPronunceLabel (@NotNull CAGGSyntaxDefinitionParser.PronunceLabelContext ctx)
void enterActionDirective (@NotNull CAGGSyntaxDefinitionParser.ActionDirectiveContext ctx)
void exitActionDirective (@NotNull CAGGSyntaxDefinitionParser.ActionDirectiveContext ctx)
void enterGrammarHearder (@NotNull CAGGSyntaxDefinitionParser.GrammarHearderContext ctx)
void exitGrammarHearder (@NotNull CAGGSyntaxDefinitionParser.GrammarHearderContext ctx)
void enterImportDeclaration (@NotNull CAGGSyntaxDefinitionParser.ImportDeclarationContext ctx)
void exitImportDeclaration (@NotNull CAGGSyntaxDefinitionParser.ImportDeclarationContext ctx)
void enterNuanceGrammar (@NotNull CAGGSyntaxDefinitionParser.NuanceGrammarContext ctx)
void exitNuanceGrammar (@NotNull CAGGSyntaxDefinitionParser.NuanceGrammarContext ctx)
void enterRuleDirective (@NotNull CAGGSyntaxDefinitionParser.RuleDirectiveContext ctx)
void exitRuleDirective (@NotNull CAGGSyntaxDefinitionParser.RuleDirectiveContext ctx)
void enterGrammarDeclaration (@NotNull CAGGSyntaxDefinitionParser.GrammarDeclarationContext ctx)
void exitGrammarDeclaration (@NotNull CAGGSyntaxDefinitionParser.GrammarDeclarationContext ctx)
void enterRuleExpression (@NotNull CAGGSyntaxDefinitionParser.RuleExpressionContext ctx)
void exitRuleExpression (@NotNull CAGGSyntaxDefinitionParser.RuleExpressionContext ctx)
void enterActionDefinition (@NotNull CAGGSyntaxDefinitionParser.ActionDefinitionContext ctx)
void exitActionDefinition (@NotNull CAGGSyntaxDefinitionParser.ActionDefinitionContext ctx)
void enterStartDeclaration (@NotNull CAGGSyntaxDefinitionParser.StartDeclarationContext ctx)
void exitStartDeclaration (@NotNull CAGGSyntaxDefinitionParser.StartDeclarationContext ctx)
void enterAndOperator (@NotNull CAGGSyntaxDefinitionParser.AndOperatorContext ctx)
void exitAndOperator (@NotNull CAGGSyntaxDefinitionParser.AndOperatorContext ctx)
void enterRuleDeclaration (@NotNull CAGGSyntaxDefinitionParser.RuleDeclarationContext ctx)
void exitRuleDeclaration (@NotNull CAGGSyntaxDefinitionParser.RuleDeclarationContext ctx)
void enterOrOperator (@NotNull CAGGSyntaxDefinitionParser.OrOperatorContext ctx)
void exitOrOperator (@NotNull CAGGSyntaxDefinitionParser.OrOperatorContext ctx)
void enterModifableDeclaration (@NotNull CAGGSyntaxDefinitionParser.ModifableDeclarationContext ctx)
void exitModifableDeclaration (@NotNull CAGGSyntaxDefinitionParser.ModifableDeclarationContext ctx)
void enterLanguageDeclaration (@NotNull CAGGSyntaxDefinitionParser.LanguageDeclarationContext ctx)
void exitLanguageDeclaration (@NotNull CAGGSyntaxDefinitionParser.LanguageDeclarationContext ctx)
void enterOptionalDirective (@NotNull CAGGSyntaxDefinitionParser.OptionalDirectiveContext ctx)
void exitOptionalDirective (@NotNull CAGGSyntaxDefinitionParser.OptionalDirectiveContext ctx)
void enterLabelDirective (@NotNull CAGGSyntaxDefinitionParser.LabelDirectiveContext ctx)
void exitLabelDirective (@NotNull CAGGSyntaxDefinitionParser.LabelDirectiveContext ctx)
void enterIdDirective (@NotNull CAGGSyntaxDefinitionParser.IdDirectiveContext ctx)
void exitIdDirective (@NotNull CAGGSyntaxDefinitionParser.IdDirectiveContext ctx)
void enterPronounceDirective (@NotNull CAGGSyntaxDefinitionParser.PronounceDirectiveContext ctx)
void exitPronounceDirective (@NotNull CAGGSyntaxDefinitionParser.PronounceDirectiveContext ctx)
void enterEveryRule (@NotNull ParserRuleContext ctx)
void exitEveryRule (@NotNull ParserRuleContext ctx)
void visitTerminal (@NotNull TerminalNode node)
void visitErrorNode (@NotNull ErrorNode node)
Private Member Functions
void setParentASN (ExpressionNode<?> node)
Private Attributes
PronounceSyntaxNode asnPronounce
RuleSyntaxNode asnRule
ExpressionNode<?> lastTerm = null
List< String > actionPending = null
Additional Inherited Members
Protected Member Functions inherited from it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener
void addNode (AbstractSyntaxNode<?> newChild)
ExpressionTreeGenerator newExpressionGenerator ()
void addExpressionOperation (ExpressionNode<?> e)
void addExpressionTerm (ExpressionNode<?> e)
ExpressionNode<?> getExpressionTree ()
Protected Member Functions inherited from it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener
List< ParseTree > getChildOfTypeOR (ParseTree node)
List< ParseTree > getChildOfTypeAND (ParseTree node)
List< ParseTree > getChildOfTypeTerm (ParseTree node)
List< ParseTree > getChildOfTypeExpression (ParseTree node)
List< ParseTree > getChildOfTypeDirective (ParseTree node)
Boolean hasChildWithXChildren (ParseTree node, int X)
Boolean hasChildWith0Children (ParseTree node)
Boolean hasChildWith1Children (ParseTree node)
Boolean hasChildWith2Children (ParseTree node)
Boolean hasChildWith3Children (ParseTree node)
Boolean hasChildrenWithSymbol (ParseTree orChild, String symbol)
Boolean hasChildrenWithOrSymbol (ParseTree orChild)
Detailed Description
Version
Concept-Action Grammar Generator 1.1
File: src//cagg.core.sourceInterface.parser.ParserListener.java
Author
Buoncompagni Luca
DIBRIS, emaroLab,
University of Genoa.
15/gen/2016
This class is the top level parser listener of the system. It extends the TreeParserListener in order to generate the Abstract Syntax Tree from Parsing Tree traversal.
See Also
TreeParserListener
LogicalParserListener
AbstractSyntaxNode
TextualParser
ExpressionNode
ExpressionTreeGenerator
Definition at line 58 of file ParserListener.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.language.parser.ParserListener.ParserListener (CAGGSyntaxDefinitionParser parser)
This constructor just initialises this object by calling its super-constructor: TreeParserListener#TreeParserListener(CAGGSyntaxDefinitionParser).
Parameters
parser the ANTLR generated class for parsing the source code.
Definition at line 68 of file ParserListener.java.
Member Function Documentation
void it.emarolab.cagg.core.language.parser.ParserListener.enterActionDefinition (ActionDefinitionContext ctx)
This method calls its super-method (TreeParserListener#enterActionDefinition(CAGGSyntaxDefinitionParser.ActionDefinitionContext)) first. Then, it parses the string containing the action tags (if any) and add them to the last term of this expression by calling RuleSyntaxNode#addActions(List, ExpressionNode).
See Also
enterBody(CAGGSyntaxDefinitionParser.BodyContext)
enterRuleDeclaration(CAGGSyntaxDefinitionParser.RuleDeclarationContext)
enterAndOperator(CAGGSyntaxDefinitionParser.AndOperatorContext)
enterOrOperator(CAGGSyntaxDefinitionParser.OrOperatorContext)
enterRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext)
exitRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext)
exitBody(CAGGSyntaxDefinitionParser.BodyContext)
Definition at line 578 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ParserListener.actionPending, and it.emarolab.cagg.core.language.parser.ParserListener.lastTerm.
void it.emarolab.cagg.core.language.parser.ParserListener.enterActionDirective (ActionDirectiveContext ctx)
This method calls its super-method (TreeParserListener#enterActionDirective(CAGGSyntaxDefinitionParser.ActionDirectiveContext)) first. Then, it calls addExpressionOperation(ExpressionNode) with a new ActionExpressionNode as input parameter. This is done in order to add to the actual expression tree state of this object a new Action node.
Definition at line 375 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ParserListener.setParentASN().
void it.emarolab.cagg.core.language.parser.ParserListener.enterActivableDeclaration (ActivableDeclarationContext ctx)
This method calls its super-method (TreeParserListener#enterActivableDeclaration(CAGGSyntaxDefinitionParser.ActivableDeclarationContext)) first. Then, it initialises the grammar node (ActivableSyntaxNode) and add it as a child of the preamble node into the AST.
Definition at line 227 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.getParser().
void it.emarolab.cagg.core.language.parser.ParserListener.enterAndOperator (AndOperatorContext ctx)
This method calls its super-method (TreeParserListener#enterAndOperator(CAGGSyntaxDefinitionParser.AndOperatorContext)) first. Then, if isAndOperation() is
true
, it calls addExpressionOperation(ExpressionNode) with a new AndExpressionNode as input parameter in order to add a new And node to the ET state. Otherwise it does not do nothing.
See Also
enterBody(CAGGSyntaxDefinitionParser.BodyContext)
enterRuleDeclaration(CAGGSyntaxDefinitionParser.RuleDeclarationContext)
enterOrOperator(CAGGSyntaxDefinitionParser.OrOperatorContext)
enterRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext)
exitRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext)
enterActionDefinition(CAGGSyntaxDefinitionParser.ActionDefinitionContext)
exitBody(CAGGSyntaxDefinitionParser.BodyContext)
Definition at line 482 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isAndOperation(), and it.emarolab.cagg.core.language.parser.ParserListener.setParentASN().
void it.emarolab.cagg.core.language.parser.ParserListener.enterBody (BodyContext ctx)
This method calls its super-method (TreeParserListener#enterBody(CAGGSyntaxDefinitionParser.BodyContext)) first. Then, it creates and initialises a new pronounce node (RuleSyntaxNode).
See Also
enterRuleDeclaration(CAGGSyntaxDefinitionParser.RuleDeclarationContext)
enterAndOperator(CAGGSyntaxDefinitionParser.AndOperatorContext)
enterOrOperator(CAGGSyntaxDefinitionParser.OrOperatorContext)
enterRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext)
exitRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext)
enterActionDefinition(CAGGSyntaxDefinitionParser.ActionDefinitionContext)
exitBody(CAGGSyntaxDefinitionParser.BodyContext)
Definition at line 439 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ParserListener.asnRule, and it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.getParser().
void it.emarolab.cagg.core.language.parser.ParserListener.enterExportDeclaration (ExportDeclarationContext ctx)
This method calls its super-method (TreeParserListener#enterExportDeclaration(CAGGSyntaxDefinitionParser.ExportDeclarationContext)) first. Then, it initialises the export node (ExportSyntaxNode) and add it as a child of the preamble node into the AST.
Definition at line 159 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.getParser().
void it.emarolab.cagg.core.language.parser.ParserListener.enterGrammarDeclaration (GrammarDeclarationContext ctx)
This method calls its super-method (TreeParserListener#enterGrammarDeclaration(CAGGSyntaxDefinitionParser.GrammarDeclarationContext)) first. Then, it initialises the grammar node (GrammarSyntaxNode) and add it as a child of the preamble node into the AST.
Definition at line 125 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.getParser().
void it.emarolab.cagg.core.language.parser.ParserListener.enterGrammarHearder (GrammarHearderContext ctx)
This method calls its super-method (TreeParserListener#enterGrammarHearder(CAGGSyntaxDefinitionParser.GrammarHearderContext)) first. Then, it initialises the header node (HeaderSyntaxNode) and add it as a child of the preamble node into the AST.
Definition at line 106 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.getParser().
void it.emarolab.cagg.core.language.parser.ParserListener.enterIdDirective (IdDirectiveContext ctx)
This method calls its super-method (TreeParserListener#enterIdDirective(CAGGSyntaxDefinitionParser.IdDirectiveContext)) first. Then, it calls addExpressionOperation(ExpressionNode) with a new IdExpressionNode as input parameter. This is done in order to add to the actual expression tree state of this object a new Id node.
Definition at line 357 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ParserListener.setParentASN().
void it.emarolab.cagg.core.language.parser.ParserListener.enterImportDeclaration (ImportDeclarationContext ctx)
This method calls its super-method (TreeParserListener#enterImportDeclaration(CAGGSyntaxDefinitionParser.ImportDeclarationContext)) first. Then, it initialises the grammar node (ImportSyntaxNode) and add it as a child of the preamble node into the AST.
Definition at line 176 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.getParser().
void it.emarolab.cagg.core.language.parser.ParserListener.enterLabelDirective (LabelDirectiveContext ctx)
This method calls its super-method (TreeParserListener#enterIgnoreDirective(NuanceGrammarParser.IgnoreDirectiveContext)) first. Then, it calls addExpressionOperation(ExpressionNode) with a new IgnoreExpressionNode as input parameter. This is done in order to add to the actual expression tree state of this object a new Ignore node. This method calls its super-method (TreeParserListener#enterLabelDirective(CAGGSyntaxDefinitionParser.LabelDirectiveContext)) first. Then, it calls addExpressionOperation(ExpressionNode) with a new LabelExpressionNode as input parameter. This is done in order to add to the actual expression tree state of this object a new Label node.
Definition at line 339 of file ParserListener.java.
void it.emarolab.cagg.core.language.parser.ParserListener.enterLanguageDeclaration (LanguageDeclarationContext ctx)
This method calls its super-method (TreeParserListener#enterLanguageDeclaration(CAGGSyntaxDefinitionParser.LanguageDeclarationContext)) first. Then, it initialises the language node (LanguageSyntaxNode) and add it as a child of the preamble node into the AST.
Definition at line 142 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.getParser().
void it.emarolab.cagg.core.language.parser.ParserListener.enterModifableDeclaration (ModifableDeclarationContext ctx)
This method calls its super-method (TreeParserListener#enterModifableDeclaration(CAGGSyntaxDefinitionParser.ModifableDeclarationContext)) first. Then, it initialises the grammar node (ModifiableSyntaxNode) and add it as a child of the preamble node into the AST.
Definition at line 210 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.getParser().
void it.emarolab.cagg.core.language.parser.ParserListener.enterNuanceGrammar (NuanceGrammarContext ctx)
This method calls its super-method (TreeParserListener#enterNuanceGrammar(CAGGSyntaxDefinitionParser.NuanceGrammarContext)) first. Then, it initialises the main AST nodes (root, preamble and body) by instantiate: RootSyntaxNode, PreambleSyntaxNode and BodySyntaxNode (respectively). Finally, it uses them in order to set the AST attached to this class by calling: setBaseNodes(AbstractSyntaxNode, AbstractSyntaxNode, AbstractSyntaxNode).
Definition at line 83 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.astRoot, it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.getAstBody(), it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.getAstPreamble(), it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.getAstRoot(), and it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.getParser().
void it.emarolab.cagg.core.language.parser.ParserListener.enterOptionalDirective (OptionalDirectiveContext ctx)
This method calls its super-method (TreeParserListener#enterOptionalDirective(CAGGSyntaxDefinitionParser.OptionalDirectiveContext)) first. Then, it calls addExpressionOperation(ExpressionNode) with a new OptionalExpressionNode as input parameter. This is done in order to add to the actual expression tree state of this object a new Optional node.
Definition at line 305 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ParserListener.setParentASN().
void it.emarolab.cagg.core.language.parser.ParserListener.enterOrOperator (OrOperatorContext ctx)
This method calls its super-method (TreeParserListener#enterOrOperator(CAGGSyntaxDefinitionParser.OrOperatorContext)) first. Then, if isOrOperation() is
true
, it calls addExpressionOperation(ExpressionNode) with a new OrExpressionNode as input parameter in order to add a new Or node to the ET state. Otherwise it does not do nothing.
See Also
enterBody(CAGGSyntaxDefinitionParser.BodyContext)
enterRuleDeclaration(CAGGSyntaxDefinitionParser.RuleDeclarationContext)
enterAndOperator(CAGGSyntaxDefinitionParser.AndOperatorContext)
enterRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext)
exitRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext)
enterActionDefinition(CAGGSyntaxDefinitionParser.ActionDefinitionContext)
exitBody(CAGGSyntaxDefinitionParser.BodyContext)
Definition at line 506 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isOrOperation(), and it.emarolab.cagg.core.language.parser.ParserListener.setParentASN().
void it.emarolab.cagg.core.language.parser.ParserListener.enterPronounceDeclaration (PronounceDeclarationContext ctx)
This method calls its super-method (TreeParserListener#enterPronounceDeclaration(CAGGSyntaxDefinitionParser.PronounceDeclarationContext)) first. Then, it creates and initialises a new pronounce node (PronounceSyntaxNode).
See Also
enterPronunceLabel(CAGGSyntaxDefinitionParser.PronunceLabelContext)
exitPronounceDeclaration(CAGGSyntaxDefinitionParser.PronounceDeclarationContext)
Definition at line 248 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ParserListener.asnPronounce, and it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.getParser().
void it.emarolab.cagg.core.language.parser.ParserListener.enterPronounceDirective (PronounceDirectiveContext ctx)
This method calls its super-method (TreeParserListener#enterPronounceDirective(CAGGSyntaxDefinitionParser.PronounceDirectiveContext)) first. Then, it calls addExpressionOperation(ExpressionNode) with a new PronounceExpressionNode as input parameter. This is done in order to add to the actual expression tree state of this object a new Pronounce node.
Definition at line 393 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ParserListener.setParentASN().
void it.emarolab.cagg.core.language.parser.ParserListener.enterPronunceLabel (PronunceLabelContext ctx)
This method calls its super-method (TreeParserListener#enterPronunceLabel(CAGGSyntaxDefinitionParser.PronunceLabelContext)) first. Then, it calls the method PronounceSyntaxNode#setName(org.antlr.v4.runtime.ParserRuleContext) by giving
ctx
as input parameter in order to retrieve and store in the pronounce AST node the label attached to this definition. This is done on the instance of the ASN created in enterPronounceDeclaration(CAGGSyntaxDefinitionParser.PronounceDeclarationContext). Finally, it creates a new Expression Tree instance by calling: newExpressionGenerator() that can be manipulated by: enterOptionalDirective(CAGGSyntaxDefinitionParser.OptionalDirectiveContext), enterLabelDirective(CAGGSyntaxDefinitionParser.LabelDirectiveContext), enterIdDirective(CAGGSyntaxDefinitionParser.IdDirectiveContext), enterActionDirective(CAGGSyntaxDefinitionParser.ActionDirectiveContext), enterRepeatDirective(CAGGSyntaxDefinitionParser.RepeatDirectiveContext), enterPronounceDirective(CAGGSyntaxDefinitionParser.PronounceDirectiveContext), enterAndOperator(CAGGSyntaxDefinitionParser.AndOperatorContext), enterOrOperator(CAGGSyntaxDefinitionParser.OrOperatorContext) and enterRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext); in order to generate the logical definition of the pronounce.
See Also
enterPronounceDeclaration(CAGGSyntaxDefinitionParser.PronounceDeclarationContext)
exitPronounceDeclaration(CAGGSyntaxDefinitionParser.PronounceDeclarationContext)
Definition at line 271 of file ParserListener.java.
void it.emarolab.cagg.core.language.parser.ParserListener.enterRepeatDirective (RepeatDirectiveContext ctx)
This method calls its super-method (TreeParserListener#enterRepeatDirective(CAGGSyntaxDefinitionParser.RepeatDirectiveContext)) first. Then, it calls addExpressionOperation(ExpressionNode) with a new RepeatExpressionNode as input parameter. This is done in order to add to the actual expression tree state of this object a new Repeat node.
Definition at line 411 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ParserListener.setParentASN().
void it.emarolab.cagg.core.language.parser.ParserListener.enterRuleDeclaration (RuleDeclarationContext ctx)
This method calls its super-method (TreeParserListener#enterRuleDeclaration(CAGGSyntaxDefinitionParser.RuleDeclarationContext)) first. Then, if isInRuleDeclarationBody() is
true
and isInRuleBody() is
false
, it calls RuleSyntaxNode#setRuleName(org.antlr.v4.runtime.ParserRuleContext) in order to set the name of the rule. Finally, it calls also:
#newExpressionGenerator()
to initialise a new expression tree to describe the rule. Otherwise it does not do nothing.
See Also
enterBody(CAGGSyntaxDefinitionParser.BodyContext)
enterAndOperator(CAGGSyntaxDefinitionParser.AndOperatorContext)
enterOrOperator(CAGGSyntaxDefinitionParser.OrOperatorContext)
enterRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext)
exitRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext)
enterActionDefinition(CAGGSyntaxDefinitionParser.ActionDefinitionContext)
exitBody(CAGGSyntaxDefinitionParser.BodyContext)
Definition at line 459 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isInRuleDeclarationBody().
void it.emarolab.cagg.core.language.parser.ParserListener.enterRuleTerm (RuleTermContext ctx)
This method calls its super-method (TreeParserListener#enterRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext)) first. Then, if isRuleTerm() is
true
, it calls addExpressionTerm(ExpressionNode) with a new TermExpressionNode as input parameter in order to add a new Term node to the ET state. Moreover, if there are pending action tags to be added it calls RuleSyntaxNode#addActions(List, ExpressionNode) in order to relate the AST rule note also with its action tags. Otherwise it does not do nothing.
See Also
enterBody(CAGGSyntaxDefinitionParser.BodyContext)
enterRuleDeclaration(CAGGSyntaxDefinitionParser.RuleDeclarationContext)
enterAndOperator(CAGGSyntaxDefinitionParser.AndOperatorContext)
enterOrOperator(CAGGSyntaxDefinitionParser.OrOperatorContext)
exitRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext)
enterActionDefinition(CAGGSyntaxDefinitionParser.ActionDefinitionContext)
exitBody(CAGGSyntaxDefinitionParser.BodyContext)
Definition at line 532 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ParserListener.actionPending, it.emarolab.cagg.core.language.parser.ANTLRInterface.LogicalParserListener.isRuleTerm(), it.emarolab.cagg.core.language.parser.ParserListener.lastTerm, and it.emarolab.cagg.core.language.parser.ParserListener.setParentASN().
void it.emarolab.cagg.core.language.parser.ParserListener.enterStartDeclaration (StartDeclarationContext ctx)
This method calls its super-method (TreeParserListener#enterStartDeclaration(CAGGSyntaxDefinitionParser.StartDeclarationContext)) first. Then, it initialises the start node (StartSyntaxNode) and add it as a child of the preamble node into the AST.
Definition at line 193 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.getParser().
void it.emarolab.cagg.core.language.parser.ParserListener.exitBody (BodyContext ctx)
This method calls its super-method (TreeParserListener#exitBody(CAGGSyntaxDefinitionParser.BodyContext)) first. Then, it calls getExpressionTree() in order to generate the ET and set it to the actual AST rule node by calling: RuleSyntaxNode#setTree(ExpressionNode). Finally, it adds that rule node to the AST body node.
See Also
enterBody(CAGGSyntaxDefinitionParser.BodyContext)
enterRuleDeclaration(CAGGSyntaxDefinitionParser.RuleDeclarationContext)
enterAndOperator(CAGGSyntaxDefinitionParser.AndOperatorContext)
enterOrOperator(CAGGSyntaxDefinitionParser.OrOperatorContext)
enterRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext)
exitRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext)
enterActionDefinition(CAGGSyntaxDefinitionParser.ActionDefinitionContext)
Definition at line 604 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ANTLRInterface.TreeParserListener.addNode(), and it.emarolab.cagg.core.language.parser.ParserListener.asnRule.
void it.emarolab.cagg.core.language.parser.ParserListener.exitPronounceDeclaration (PronounceDeclarationContext ctx)
This method calls its super-method (TreeParserListener#exitPronounceDeclaration(CAGGSyntaxDefinitionParser.PronounceDeclarationContext)) first. Then, it calls the method PronounceSyntaxNode#setTree(ExpressionNode) by giving getExpressionTree() as input parameter in order to compose and store the ET that logically defines the pronounce relations. This is done on the instance of the ASN created in enterPronounceDeclaration(CAGGSyntaxDefinitionParser.PronounceDeclarationContext). Finally, it adds the pronounce node to the AST preamble node.
See Also
enterPronounceDeclaration(CAGGSyntaxDefinitionParser.PronounceDeclarationContext)
enterPronunceLabel(CAGGSyntaxDefinitionParser.PronunceLabelContext)
Definition at line 287 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ParserListener.asnPronounce.
void it.emarolab.cagg.core.language.parser.ParserListener.exitRuleTerm (RuleTermContext ctx)
This method calls its super-method (TreeParserListener#exitRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext)) first. Then, it resets the object identifying the last term added to the ET.
See Also
enterBody(CAGGSyntaxDefinitionParser.BodyContext)
enterRuleDeclaration(CAGGSyntaxDefinitionParser.RuleDeclarationContext)
enterAndOperator(CAGGSyntaxDefinitionParser.AndOperatorContext)
enterOrOperator(CAGGSyntaxDefinitionParser.OrOperatorContext)
enterRuleTerm(CAGGSyntaxDefinitionParser.RuleTermContext)
enterActionDefinition(CAGGSyntaxDefinitionParser.ActionDefinitionContext)
exitBody(CAGGSyntaxDefinitionParser.BodyContext)
Definition at line 559 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ParserListener.lastTerm.
void it.emarolab.cagg.core.language.parser.ParserListener.setParentASN (ExpressionNode<?> node) private
Definition at line 618 of file ParserListener.java.
References it.emarolab.cagg.core.language.parser.ParserListener.asnPronounce, and it.emarolab.cagg.core.language.parser.ParserListener.asnRule.
Referenced by it.emarolab.cagg.core.language.parser.ParserListener.enterActionDirective(), it.emarolab.cagg.core.language.parser.ParserListener.enterAndOperator(), it.emarolab.cagg.core.language.parser.ParserListener.enterIdDirective(), it.emarolab.cagg.core.language.parser.ParserListener.enterOptionalDirective(), it.emarolab.cagg.core.language.parser.ParserListener.enterOrOperator(), it.emarolab.cagg.core.language.parser.ParserListener.enterPronounceDirective(), it.emarolab.cagg.core.language.parser.ParserListener.enterRepeatDirective(), and it.emarolab.cagg.core.language.parser.ParserListener.enterRuleTerm().
Member Data Documentation
List< String> it.emarolab.cagg.core.language.parser.ParserListener.actionPending = null private
Definition at line 426 of file ParserListener.java.
Referenced by it.emarolab.cagg.core.language.parser.ParserListener.enterActionDefinition(), and it.emarolab.cagg.core.language.parser.ParserListener.enterRuleTerm().
PronounceSyntaxNode it.emarolab.cagg.core.language.parser.ParserListener.asnPronounce private
Definition at line 240 of file ParserListener.java.
Referenced by it.emarolab.cagg.core.language.parser.ParserListener.enterPronounceDeclaration(), it.emarolab.cagg.core.language.parser.ParserListener.exitPronounceDeclaration(), and it.emarolab.cagg.core.language.parser.ParserListener.setParentASN().
RuleSyntaxNode it.emarolab.cagg.core.language.parser.ParserListener.asnRule private
Definition at line 424 of file ParserListener.java.
Referenced by it.emarolab.cagg.core.language.parser.ParserListener.enterBody(), it.emarolab.cagg.core.language.parser.ParserListener.exitBody(), and it.emarolab.cagg.core.language.parser.ParserListener.setParentASN().
ExpressionNode<?> it.emarolab.cagg.core.language.parser.ParserListener.lastTerm = null private
Definition at line 425 of file ParserListener.java.
Referenced by it.emarolab.cagg.core.language.parser.ParserListener.enterActionDefinition(), it.emarolab.cagg.core.language.parser.ParserListener.enterRuleTerm(), and it.emarolab.cagg.core.language.parser.ParserListener.exitRuleTerm().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/language/parser/ParserListener.java