ConceptActionGrammarGenerator: it.emarolab.cagg.example.GrammarTest Class Reference
it.emarolab.cagg.example.GrammarTest Class Reference
Static Public Member Functions
static void main (String[] args)
Static Public Attributes
static final String GRAMMAR_PATH = DebuggingDefaults.PATH_GRAMMA_DESERIALISATION_NOTJAR + "query_scene.ser"
static final List< String > USER_COMMANDS = new ArrayList<>()
static final Float EVALUATION_TIME_OUT = 250.0f
static final Boolean USE_DEFAULT_TESTER = true
static final String TEST_LOGGING_NAME = "PhDReport15_GrammarTest"
Static Private Member Functions
static GrammarTesterBase getDefaultTester ()
static GrammarTesterBase getCustomTester ()
Detailed Description
Definition at line 17 of file GrammarTest.java.
Member Function Documentation
static GrammarTesterBase it.emarolab.cagg.example.GrammarTest.getCustomTester () static private
Definition at line 113 of file GrammarTest.java.
References it.emarolab.cagg.example.GrammarTest.EVALUATION_TIME_OUT, and it.emarolab.cagg.example.GrammarTest.GRAMMAR_PATH.
Referenced by it.emarolab.cagg.example.GrammarTest.main().
static GrammarTesterBase it.emarolab.cagg.example.GrammarTest.getDefaultTester () static private
Definition at line 103 of file GrammarTest.java.
References it.emarolab.cagg.example.GrammarTest.EVALUATION_TIME_OUT, it.emarolab.cagg.example.GrammarTest.GRAMMAR_PATH, and it.emarolab.cagg.example.GrammarTest.TEST_LOGGING_NAME.
Referenced by it.emarolab.cagg.example.GrammarTest.main().
static void it.emarolab.cagg.example.GrammarTest.main (String[] args) static
Definition at line 91 of file GrammarTest.java.
References it.emarolab.cagg.example.GrammarTest.getCustomTester(), it.emarolab.cagg.example.GrammarTest.getDefaultTester(), it.emarolab.cagg.debugging.DebuggingDefaults.PATH_LOG_CONF_BASE, it.emarolab.cagg.example.GrammarTest.USE_DEFAULT_TESTER, and it.emarolab.cagg.example.GrammarTest.USER_COMMANDS.
Member Data Documentation
final Float it.emarolab.cagg.example.GrammarTest.EVALUATION_TIME_OUT = 250.0f static
Definition at line 86 of file GrammarTest.java.
Referenced by it.emarolab.cagg.example.GrammarTest.getCustomTester(), and it.emarolab.cagg.example.GrammarTest.getDefaultTester().
final String it.emarolab.cagg.example.GrammarTest.GRAMMAR_PATH = DebuggingDefaults.PATH_GRAMMA_DESERIALISATION_NOTJAR + "query_scene.ser" static
Definition at line 20 of file GrammarTest.java.
Referenced by it.emarolab.cagg.example.GrammarTest.getCustomTester(), and it.emarolab.cagg.example.GrammarTest.getDefaultTester().
final String it.emarolab.cagg.example.GrammarTest.TEST_LOGGING_NAME = "PhDReport15_GrammarTest" static
Definition at line 88 of file GrammarTest.java.
Referenced by it.emarolab.cagg.example.GrammarTest.getDefaultTester().
final Boolean it.emarolab.cagg.example.GrammarTest.USE_DEFAULT_TESTER = true static
Definition at line 87 of file GrammarTest.java.
Referenced by it.emarolab.cagg.example.GrammarTest.main().
final List< String> it.emarolab.cagg.example.GrammarTest.USER_COMMANDS = new ArrayList<>() static
Definition at line 23 of file GrammarTest.java.
Referenced by it.emarolab.cagg.example.GrammarTest.main().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/example/GrammarTest.java