ConceptActionGrammarGenerator: it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile Class Reference
it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile Class Reference
Public Member Functions
void setUserInputToTest (List< String > userInputToTest)
void setUserInputToTest (String userInputToTest)
void setUserInputToTest (String userInputToTest, int idx)
void resetUserInputToTest ()
MultiGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, String grammarPath)
void setMultiFile (String attribute, String date)
void run ()
Public Member Functions inherited from it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile
CaggGrammarTesterOnFile (String grammarPath)
CaggGrammarTesterOnFile (String grammarPath, Float timeOutSec)
CaggGrammarTesterOnFile (GrammarBase<?extends SemanticExpressionTreeBase > grammar)
CaggGrammarTesterOnFile (GrammarBase<?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
CaggGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, String grammarPath)
CaggGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, String grammarPath, Float timeOutSec)
CaggGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar)
CaggGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
synchronized void willEvaluateCommand (String command, int testIdx)
synchronized void didEvaluateCommand (String command, int testIdx)
EvaluatorTesterOnFile getEvaluator ()
TestPathManager getPathManager ()
void setFile ()
void setFile (String attribute)
void setFile (String basePath, String attribute)
void setFile (String attribute, boolean useDate)
void setFile (boolean useDate, String basePath)
void setFile (String basePath, String attribute, boolean useDate)
void setFile (String basePath, String attribute, boolean useDate, String logsFileName, String testMapFileName, String resultBaseFileName)
void setPathManager (TestPathManager pathManager)
Public Member Functions inherited from it.emarolab.cagg.interfaces.CaggGrammarTester
CaggGrammarTester (GrammarBase<?extends SemanticExpressionTreeBase > grammar)
CaggGrammarTester (GrammarBase<?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
CaggGrammarTester (String grammarPath)
CaggGrammarTester (String grammarPath, Float timeOutSec)
CaggGrammarTester (String evaluatorLoggerName, String formatterLoggerName, String grammarPath)
CaggGrammarTester (String evaluatorLoggerName, String formatterLoggerName, String grammarPath, Float timeOutSec)
CaggGrammarTester (String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar)
CaggGrammarTester (String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
synchronized void willEvaluateCommand (String command, int testIdx)
synchronized void didEvaluateCommand (String command, int testIdx)
Public Member Functions inherited from it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase
GrammarTesterBase (String grammarPath)
GrammarTesterBase (String grammarPath, Float timeOutSec)
GrammarTesterBase (GrammarBase< ?extends SemanticExpressionTreeBase > grammar)
GrammarTesterBase (GrammarBase< ?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
GrammarTesterBase (String evaluatorLoggerName, String formatterLoggerName, String grammarPath)
GrammarTesterBase (String evaluatorLoggerName, String formatterLoggerName, String grammarPath, Float timeOutSec)
GrammarTesterBase (String evaluatorLoggerName, String formatterLoggerName, GrammarBase< ?extends SemanticExpressionTreeBase > grammar)
GrammarTesterBase (String evaluatorLoggerName, String formatterLoggerName, GrammarBase< ?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
GrammarBase< ?extends
SemanticExpressionTreeBase > getGrammar ()
TimeOutedEvaluatorBase getEvaluator ()
ThreadedInputFormatter getFormatter ()
boolean isTestingLastCommand ()
void resetLastCommand ()
Float getTestingTime ()
void setTestingTime ()
synchronized Float getRangeFromTestingStart ()
synchronized String getEvaluatorLoggerName ()
String getFormatterLoggerName ()
synchronized void test (List< String > commands)
synchronized void test (String command)
synchronized void test (String command, int testIdx)
abstract void willEvaluateCommand (String command, int testIdx)
abstract void didEvaluateCommand (String command, int testIdx)
Protected Member Functions
synchronized void updateTestMap (String filePath, String command, int testIdx)
Protected Member Functions inherited from it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile
ThreadedInputFormatter getNewFormatter (String prefixLog, GrammarBase< ?extends SemanticExpressionTreeBase > grammar)
TimeOutedEvaluatorBase getNewEvaluator (String prefixLog, ThreadedInputFormatter formatter, Float timeOutSec)
void createTestMap (int testIdx)
void createSystemLog (String logPath)
void storeResults (CaggXmlManager xmlManager, int testIdx, String command)
void storeResult (String filePath, CaggXmlManager xmlManager)
synchronized void updateTestMap (String filePath, String command, int testIdx)
void addTestMapFooter (String logPath)
Protected Member Functions inherited from it.emarolab.cagg.interfaces.CaggGrammarTester
ThreadedInputFormatter getNewFormatter (String prefixLog, GrammarBase< ?extends SemanticExpressionTreeBase > grammar)
TimeOutedEvaluatorBase getNewEvaluator (String prefixLog, ThreadedInputFormatter formatter, Float timeOutSec)
Protected Member Functions inherited from it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase
abstract ThreadedInputFormatter getNewFormatter (String loggerName, GrammarBase< ?extends SemanticExpressionTreeBase > grammar)
abstract TimeOutedEvaluatorBase getNewEvaluator (String loggerName, ThreadedInputFormatter formatter, Float timeOutSec)
TimeOutedEvaluatorBase getNewEvaluator (TimeOutedEvaluatorBase eval)
void performTest (String command, int testIdx)
Private Member Functions
MultiGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, String grammarPath, Float timeOutSec)
MultiGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar)
MultiGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
MultiGrammarTesterOnFile (String testName, String evaluatorLoggerName, String formatterLoggerName, String grammarPath)
MultiGrammarTesterOnFile (String testName, String evaluatorLoggerName, String formatterLoggerName, String grammarPath, Float timeOutSec)
MultiGrammarTesterOnFile (String testName, String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar)
MultiGrammarTesterOnFile (String testName, String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar, Float timeOutSec)
Private Attributes
String testName
List< String > userInputToTest = null
Integer testingIndex = null
Additional Inherited Members
Static Public Member Functions inherited from it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile
static String pathDir (String directive)
Static Public Attributes inherited from it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile
static final String DEFAULT_BASE_PATH = pathDir(DebuggingDefaults.SYS_PATH_WORKING) + pathDir("file") + pathDir("tests")
static final String DEFAULT_ATTRIBUTE = null
static final Boolean DEFAULT_USE_DATE = true
static final String ATTRIBUTE_SEPARATOR = "_"
static final String EMPTY_DIRECTORY_NAME = "xxx" + ATTRIBUTE_SEPARATOR
static final String NO_TEST_SUBFOLDER_ATTRIBUTE = ".."
Detailed Description
Definition at line 45 of file CaggMultiGrammarTesterOnFile.java.
Constructor & Destructor Documentation
it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.MultiGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, String grammarPath)
Definition at line 71 of file CaggMultiGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.DEFAULT_TEST_NAME.
it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.MultiGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, String grammarPath, Float timeOutSec) private
Definition at line 76 of file CaggMultiGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.DEFAULT_TEST_NAME.
it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.MultiGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar) private
Definition at line 81 of file CaggMultiGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.DEFAULT_TEST_NAME.
it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.MultiGrammarTesterOnFile (String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar, Float timeOutSec) private
Definition at line 86 of file CaggMultiGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.DEFAULT_TEST_NAME.
it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.MultiGrammarTesterOnFile (String testName, String evaluatorLoggerName, String formatterLoggerName, String grammarPath) private
Definition at line 91 of file CaggMultiGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.testName.
it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.MultiGrammarTesterOnFile (String testName, String evaluatorLoggerName, String formatterLoggerName, String grammarPath, Float timeOutSec) private
Definition at line 96 of file CaggMultiGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.testName.
it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.MultiGrammarTesterOnFile (String testName, String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar) private
Definition at line 101 of file CaggMultiGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.testName.
it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.MultiGrammarTesterOnFile (String testName, String evaluatorLoggerName, String formatterLoggerName, GrammarBase<?extends SemanticExpressionTreeBase > grammar, Float timeOutSec) private
Definition at line 106 of file CaggMultiGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.testName.
Member Function Documentation
void it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.resetUserInputToTest ()
Definition at line 63 of file CaggMultiGrammarTesterOnFile.java.
void it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.run ()
Definition at line 124 of file CaggMultiGrammarTesterOnFile.java.
References it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.test(), it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.testingIndex, and it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.userInputToTest.
void it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.setMultiFile (String attribute, String date)
Definition at line 115 of file CaggMultiGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.ATTRIBUTE_SEPARATOR, it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.DEFAULT_BASE_PATH, it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.NO_TEST_SUBFOLDER_ATTRIBUTE, it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.pathDir(), it.emarolab.cagg.debugging.DebuggingDefaults.SYS_PATH_DELIM, and it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.testName.
void it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.setUserInputToTest (List< String > userInputToTest)
Definition at line 52 of file CaggMultiGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.userInputToTest.
Referenced by it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.setUserInputToTest().
void it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.setUserInputToTest (String userInputToTest)
Definition at line 55 of file CaggMultiGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.setUserInputToTest().
void it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.setUserInputToTest (String userInputToTest, int idx)
Definition at line 58 of file CaggMultiGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.userInputToTest.
synchronized void it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.updateTestMap (String filePath, String command, int testIdx) protected
Definition at line 135 of file CaggMultiGrammarTesterOnFile.java.
References it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.addTestMapFooter(), it.emarolab.cagg.interfaces.CaggGrammarTesterOnFile.getPathManager(), it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.getRangeFromTestingStart(), and it.emarolab.cagg.core.evaluation.interfacing.GrammarTesterBase.isTestingLastCommand().
Member Data Documentation
Integer it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.testingIndex = null private
Definition at line 51 of file CaggMultiGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.run().
String it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.testName private
Definition at line 49 of file CaggMultiGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.MultiGrammarTesterOnFile(), and it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.setMultiFile().
List< String> it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.userInputToTest = null private
Definition at line 50 of file CaggMultiGrammarTesterOnFile.java.
Referenced by it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.run(), and it.emarolab.cagg.interfaces.CaggMultiGrammarTesterOnFile.MultiGrammarTesterOnFile.setUserInputToTest().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/interfaces/CaggMultiGrammarTesterOnFile.java