ConceptActionGrammarGenerator: it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector Class Reference
it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector Class Reference
Public Member Functions
ConsoleLogRidirector ()
ConsoleLogRidirector (String filePath)
ConsoleLogRidirector (Boolean attachOut, Boolean attachErr, Boolean printOnConsole, String filePath)
synchronized String printOutLog ()
synchronized String printErrLog ()
synchronized void setPrintOnConsole (Boolean printOnConsole)
synchronized Boolean getPrintOnConsole ()
synchronized Boolean isErrorAttached ()
synchronized Boolean isOutAtached ()
synchronized void attachOutLog ()
synchronized void detachOutLog ()
synchronized void attachErrLog ()
synchronized void detachErrLog ()
synchronized String getFilePath ()
synchronized void setFilePath (String filePath)
Protected Member Functions
synchronized void finalize () throws Throwable
Private Member Functions
void initialise (Boolean attachOut, Boolean attachErr, Boolean print, String filePath)
synchronized void printOnFile (ByteArrayOutputStream toPrint)
Private Attributes
ByteArrayOutputStream logOut
PrintStream psOut
PrintStream oldOut
Boolean outAttached = false
Boolean printOnConsole
String filePath
Detailed Description
Version
Concept-Action Grammar Generator 1.1
File: src//cagg.debugging.DebuggingText.java
Author
Buoncompagni Luca
DIBRIS, emaroLab,
University of Genoa.
15/gen/2016
This class is used along all the system to have a basing logging object. Particularly, it listen for the standard streams:
System.out
and
System.err
and redirect their messages into the StandaloneDebuggingText.Logger object.
Moreover, the messages can be also printed in the standard java console before to redirect it.
It is important to note that if some exceptions occur in to the system this class may not print the results as long as its buffer is processed. To obviate to this problem and see the longs in the GUI interact in order to process other logs (e.g. open a new grammar dialog and cancel it). While, from API it is possible to call: Logger#flushOut(), Logger#flushErr() or Logger#flushOutErr() to print out all the messages.
See Also
StandaloneDebuggingText
Logger
Definition at line 178 of file StandaloneDebuggingText.java.
Constructor & Destructor Documentation
it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.ConsoleLogRidirector ()
Initialise the redirector with all
true
flags which are:
attachOut
(listen for
System.out
stream),
attachErr
(listen for
System.err
stream) and
printOnConsole
(if the message should be printed on console rather than only redirect them). This constructor does not allow to print the logs on file
Definition at line 195 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.initialise().
it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.ConsoleLogRidirector (String filePath)
Initialise the redirector with all
true
flags which are:
attachOut
(listen for
System.out
stream),
attachErr
(listen for
System.err
stream) and
printOnConsole
(if the message should be printed on console rather than only redirect them). This constructor allows to print the logs on file by specifying the file path.
Parameters
filePath the directory to the path in which write all the logs.
Definition at line 204 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.initialise().
it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.ConsoleLogRidirector (Boolean attachOut, Boolean attachErr, Boolean printOnConsole, String filePath)
Initialise the redirector with custom flags as input parameters. Also, this constructor allows to print the logs on file by specifying the file path.
Parameters
attachOut@code true if the logger should listener
System.out
stream.
attachErr@code true if the logger should listener
System.err
stream.
printOnConsole@code true if the logger should print in the Java Console before to be redirected.
filePath the directory to the path in which write the activated logs. Set it to null or empty to do not write.
Definition at line 215 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.initialise().
Member Function Documentation
synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.attachErrLog ()
Set this redirector to listen the
System.err
stream. It has effects only if isErrorAttached() is false.
Definition at line 369 of file StandaloneDebuggingText.java.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.initialise(), and it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printErrLog().
synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.attachOutLog ()
Set this redirector to listen the
System.out
stream. It has effects only if isOutAtached() is false.
Definition at line 346 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.logOut, it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.oldOut, it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.outAttached, and it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.psOut.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.initialise(), and it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printOutLog().
synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.detachErrLog ()
Set this redirector to do not listen the
System.err
stream. It has always effects.
Definition at line 381 of file StandaloneDebuggingText.java.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printErrLog().
synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.detachOutLog ()
Set this redirector to do not listen the
System.out
stream. It has always effects.
Definition at line 358 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.oldOut, and it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.outAttached.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printOutLog().
synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.finalize () throws Throwable protected
Definition at line 402 of file StandaloneDebuggingText.java.
synchronized String it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.getFilePath ()
Returns
the directory path to the logging file. It is
empty()
if the system is not saving the logs.
Definition at line 391 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.filePath.
synchronized Boolean it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.getPrintOnConsole ()
get the print on console flag value
Returns
true
if this redirector prints the message to console.
false
otherwise.
Definition at line 323 of file StandaloneDebuggingText.java.
void it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.initialise (Boolean attachOut, Boolean attachErr, Boolean print, String filePath) private
Definition at line 218 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.attachErrLog(), it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.attachOutLog(), it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.filePath, and it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printOnConsole.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.ConsoleLogRidirector().
synchronized Boolean it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.isErrorAttached ()
get the
attachErr
flag. To modify this value use attachErrLog() or detachErrLog().
Returns
true
if this redirector is attached to
Syste.err
stream.
false
otherwise.
Definition at line 330 of file StandaloneDebuggingText.java.
synchronized Boolean it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.isOutAtached ()
get the
attachOut
flag. To modify this value use attachOutLog() or detachOutLog().
Returns
true
if this redirector is attached to
Syste.out
stream.
false
otherwise.
Definition at line 337 of file StandaloneDebuggingText.java.
synchronized String it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printErrLog ()
Return all the messages streamed in
System.err
and, if the flag (
printOnConsole
) allows it, print them into the Java console.
It returns and empty string (and logs an error) if this redirector is not attached to the out stream (specified by the flag
attachErr
).
Returns
all the new messages in the
System.err
.
Definition at line 264 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.attachErrLog(), it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.detachErrLog(), it.emarolab.cagg.debugging.StandaloneDebuggingText.NOT_ATTACHED_ERROR_RATE, it.emarolab.cagg.debugging.StandaloneDebuggingText.numberOfNotAttachedError, it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printOnConsole, and it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printOnFile().
synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printOnFile (ByteArrayOutputStream toPrint) private
Definition at line 284 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.filePath.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printErrLog(), and it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printOutLog().
synchronized String it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printOutLog ()
Return all the messages streamed in
System.out
and, if the flag (
printOnConsole
) allows it, print them into the Java console.
It returns and empty string (and logs an error) if this redirector is not attached to the out stream (specified by the flag
attachOut
).
Returns
all the new messages in the
System.out
.
Definition at line 237 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.attachOutLog(), it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.detachOutLog(), it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.logOut, it.emarolab.cagg.debugging.StandaloneDebuggingText.NOT_ATTACHED_ERROR_RATE, it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.outAttached, it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printOnConsole, and it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printOnFile().
synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.setFilePath (String filePath)
Parameters
filePath the directory path in which save all the logs. Set to
empty()
for do not saving any logs.
Definition at line 397 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.filePath.
synchronized void it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.setPrintOnConsole (Boolean printOnConsole)
Set the if this redirector should print the messages on console or not when printErrLog() and printOutLog() is called.
Parameters
printOnConsole the flag to be set.
true
to print or
false
to do not print.
Definition at line 316 of file StandaloneDebuggingText.java.
References it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printOnConsole.
Member Data Documentation
String it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.filePath private
Definition at line 184 of file StandaloneDebuggingText.java.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.getFilePath(), it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.initialise(), it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printOnFile(), and it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.setFilePath().
ByteArrayOutputStream it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.logOut private
Definition at line 179 of file StandaloneDebuggingText.java.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.attachOutLog(), and it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printOutLog().
PrintStream it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.oldOut private
Definition at line 181 of file StandaloneDebuggingText.java.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.attachOutLog(), and it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.detachOutLog().
Boolean it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.outAttached = false private
Definition at line 182 of file StandaloneDebuggingText.java.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.attachOutLog(), it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.detachOutLog(), and it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printOutLog().
Boolean it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printOnConsole private
Definition at line 183 of file StandaloneDebuggingText.java.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.initialise(), it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printErrLog(), it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.printOutLog(), and it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.setPrintOnConsole().
PrintStream it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.psOut private
Definition at line 180 of file StandaloneDebuggingText.java.
Referenced by it.emarolab.cagg.debugging.StandaloneDebuggingText.ConsoleLogRidirector.attachOutLog().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/debugging/StandaloneDebuggingText.java