ConceptActionGrammarGenerator: it.emarolab.cagg.core.language.syntax.GrammarPrimitive Class Reference
it.emarolab.cagg.core.language.syntax.GrammarPrimitive Class Reference
Public Member Functions
GrammarPrimitive (TextualParser parser)
AbstractSyntaxNode<?> getPreambleTree ()
Map< Long, AbstractSyntaxNode<?> > getPreambleMap ()
AbstractSyntaxNode<?> getBodyTree ()
Map< Long, RuleSyntaxNode > getBodyMap ()
Map< Long, ExpressionNode<?> > getExpressionsNodesMap ()
RuleSyntaxNode getMainRule ()
RuleSyntaxNode getNamedRule (String ruleName)
ExpressionNode<?> getMainRuleExpressionTree ()
ExpressionNode<?> getNamedRuleExpressionTree (String ruleName)
String searchMainRuleName ()
Boolean isMainGrammar ()
String getMainRuleName ()
String toString ()
Private Member Functions
Map< Long, AbstractSyntaxNode<?> > setPreambleMap (AbstractSyntaxNode<?> tree)
Map< Long, RuleSyntaxNode > setRuleMap (AbstractSyntaxNode<?> tree)
Map< Long, ExpressionNode<?> > setExpressionsNodesMap (Map< Long, RuleSyntaxNode > ruleMap)
Private Attributes
AbstractSyntaxNode<?> preambleTree
Map< Long, AbstractSyntaxNode<?> > preambleMap
Map< Long, RuleSyntaxNode > ruleMap
Map< Long, ExpressionNode<?> > expMap
String parserToString
String mainRuleName = ""
Detailed Description
Version
Concept-Action Grammar Generator 1.1
File: src//cagg.core.sourceInterface.grammar.GrammarPrimitive.java
Author
Buoncompagni Luca
DIBRIS, emaroLab,
University of Genoa.
15/gen/2016
This class is used to fully describe the grammar obtained by parsing a source code. Particularly, instances of this class are created during constructors of GrammarCreator.
More in details, this grammar contains the preamble and body ASTs for a given source code, as well as those nodes collected in an java.util.HashMap with node ID has identifier (this is done by using: it.emarolab.cagg.core.language.SyntaxNode#toMap()).
To note that the methods implemented from this class may be inefficient (also because their are designed to be used with the GUI). So, for a real usage of this sistem it is suggest to serialise those results and use them directly without compute them all the times that a result should be evaluated. In order to do so, use: GrammarCreator#serialise(String)
See Also
it.emarolab.cagg.core.language.parser.TextualParser
it.emarolab.cagg.core.language.SyntaxNode
GrammarCreator
it.emarolab.cagg.core.language.syntax.abstractTree.AbstractSyntaxNode
it.emarolab.cagg.core.language.syntax.expressionTree.ExpressionNode
Definition at line 44 of file GrammarPrimitive.java.
Constructor & Destructor Documentation
it.emarolab.cagg.core.language.syntax.GrammarPrimitive.GrammarPrimitive (TextualParser parser)
This method construct the preamble and body trees and maps from the input parameter. More in details, the preamble and body trees are given by calling: it.emarolab.cagg.core.language.parser.TextualParser#getASPreambleTreeCopy() and it.emarolab.cagg.core.language.parser.TextualParser#getASBodyTreeCopy(). Where a copy is done in order to do not modify all the visualisations of those trees in the GUI during evaluation and manipulation (even if this is not efficient). Finally, this constructors class it.emarolab.cagg.core.language.SyntaxNode#toMap() on those tree in order to fully initialise this class.
Parameters
parser the source code parser from which this Grammar should be created.
Definition at line 69 of file GrammarPrimitive.java.
References it.emarolab.cagg.core.language.syntax.GrammarPrimitive.expMap, it.emarolab.cagg.core.language.syntax.GrammarPrimitive.parserToString, it.emarolab.cagg.core.language.syntax.GrammarPrimitive.preambleMap, it.emarolab.cagg.core.language.syntax.GrammarPrimitive.preambleTree, it.emarolab.cagg.core.language.syntax.GrammarPrimitive.ruleMap, it.emarolab.cagg.core.language.syntax.GrammarPrimitive.setExpressionsNodesMap(), it.emarolab.cagg.core.language.syntax.GrammarPrimitive.setPreambleMap(), and it.emarolab.cagg.core.language.syntax.GrammarPrimitive.setRuleMap().
Member Function Documentation
Map<Long, RuleSyntaxNode> it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getBodyMap ()
Returns
the body map created on constructors GrammarCreator#GrammarCreator(List)}.
Definition at line 139 of file GrammarPrimitive.java.
References it.emarolab.cagg.core.language.syntax.GrammarPrimitive.ruleMap.
AbstractSyntaxNode<?> it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getBodyTree ()
Returns
the body tree parsed from source and copied on constructors GrammarCreator#GrammarCreator(List)}.
Definition at line 133 of file GrammarPrimitive.java.
Map<Long, ExpressionNode<?> > it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getExpressionsNodesMap ()
Returns
the map containing every node of all the Expression Trees in this primitive w.r.t. to base node identifier.
Definition at line 146 of file GrammarPrimitive.java.
RuleSyntaxNode it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getMainRule ()
This methods return the ASN for the main rule in case in which this is a main grammar. It returns
null
otherwise or if searchMainRuleName() has not been called. To note that this method has a not efficient implementation.
Returns
the value of getNamedRule(String) with input parameter set to: getMainRuleName().
Definition at line 157 of file GrammarPrimitive.java.
References it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getNamedRule(), and it.emarolab.cagg.core.language.syntax.GrammarPrimitive.mainRuleName.
ExpressionNode<?> it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getMainRuleExpressionTree ()
This method calls: getNamedRuleExpressionTree(String, Boolean) where the input parameter
ruleName
is the result of getMainRuleName()
Parameters
copy if
true
the returning ET is a copy extrapolated from the ASN. If it is
false
the returning tree is the same object that is contained in the ASN.
Returns
The ET described from the main rule. It returns
null
if the grammar does not contain this rule definition or if getMainRuleName() returns
empty
.
Definition at line 188 of file GrammarPrimitive.java.
References it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getNamedRuleExpressionTree(), and it.emarolab.cagg.core.language.syntax.GrammarPrimitive.mainRuleName.
String it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getMainRuleName ()
This method returns the name of the main rule in cases in which this source file identify a main grammar. To note that it returns an empty string in case in which this is not a main grammar or searchMainRuleName() has not be called.
Returns
the name of the main rule found by the method searchMainRuleName() (not automatically called). Or it returns an empty string in case in which the name has not been evaluated or this is not a main grammar.
Definition at line 294 of file GrammarPrimitive.java.
References it.emarolab.cagg.core.language.syntax.GrammarPrimitive.mainRuleName.
RuleSyntaxNode it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getNamedRule (String ruleName)
This method search for the ASN of a rule given its declarative name. It break the searching loop as soon as the first occurrence is found.
Parameters
ruleName the declarative name of a rule to be found in this grammar.
Returns
the Abstract Syntax Node describing the rule if it exists.
null
if it has not such a rule or if the getBodyMap() is empty.
Definition at line 167 of file GrammarPrimitive.java.
References it.emarolab.cagg.core.language.syntax.GrammarPrimitive.ruleMap.
Referenced by it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getMainRule(), and it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getNamedRuleExpressionTree().
ExpressionNode<?> it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getNamedRuleExpressionTree (String ruleName)
This method calls: getNamedRuleExpressionTree(String, Boolean, Boolean) where the input parameter
ruleName
is the result of getMainRuleName()
Parameters
copy if
true
the returning ET is a copy extrapolated from the ASN. If it is
false
the returning tree is the same object that is contained in the ASN.
createNewId this data is considered only when
copy
is
true
. Particularly, if
createNewId
is
true
the copied tree would have the same ID but different copyID. If it is
false
the copied tree will have the same ID and copyId. This is done by calling cagg.core.sourceInterface.grammar.abstractSyntaxTree.syntaxNodeType.RuleSyntaxNode#getExpressionTreeCopy(Boolean) with
createNewId
as input parameter.
Returns
The ET described from the main rule. It returns
null
if the grammar does not contain this rule definition or if getMainRuleName() returns
empty
. This method calls getNamedRuleExpressionTree(String, Boolean, Boolean) with input parameter respectively set to:
ruleName
,
copy
and
false
.
Parameters
ruleName the declarative name of the rule to be searched in the body map.
copy if
true
the returning ET is a copy extrapolated from the ASN. If it is
false
the returning tree is the same object that is contained in the ASN.
Returns
the ET contained in the body Abstract Syntax Node that have name as
ruleName
copied with respect to the given parameter. If this grammar does not contains a rule with the given name it returns
null
. This method use getNamedRule(String) in order to get the ASN of the rule from its name. Than, it returns the ET that represents such a rule. Moreover, it managge the copying of tree and id both for the visualisation in the GUI of more than one tree as well as for evaluation (see it.emarolab.cagg.core.evaluatorOLD.InputFormatter).
Parameters
ruleName the declarative name of the rule to be searched in the body map.
copy if
true
the returning ET is a copy extrapolated from the ASN. If it is
false
the returning tree is the same object that is contained in the ASN.
createNewId this data is considered only when
copy
is
true
. Particularly, if
createNewId
is
true
the copied tree would have the same ID but different copyID. If it is
false
the copied tree will have the same ID and copyId. This is done by calling it.emarolab.cagg.core.language.syntax.abstractTree.syntaxNodeType.RuleSyntaxNode#getExpressionTreeCopy(Boolean) with
createNewId
as input parameter.
Returns
the ET contained in the body Abstract Syntax Node that have name as
ruleName
copied with respect to the given parameter. If this grammar does not contains a rule with the given name it returns
null
.
Definition at line 239 of file GrammarPrimitive.java.
References it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getNamedRule().
Referenced by it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getMainRuleExpressionTree().
Map<Long, AbstractSyntaxNode<?> > it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getPreambleMap ()
Returns
the preamble map created on constructors GrammarCreator#GrammarCreator(List)}.
Definition at line 126 of file GrammarPrimitive.java.
References it.emarolab.cagg.core.language.syntax.GrammarPrimitive.preambleMap.
AbstractSyntaxNode<?> it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getPreambleTree ()
Returns
the preamble tree parsed from source and copied on constructors GrammarCreator#GrammarCreator(List)}.
Definition at line 120 of file GrammarPrimitive.java.
References it.emarolab.cagg.core.language.syntax.GrammarPrimitive.preambleTree.
Boolean it.emarolab.cagg.core.language.syntax.GrammarPrimitive.isMainGrammar ()
This method describe if the source file parsed in this object is a main grammar or not. To note that it returns always
false
if searchMainRuleName() is not called first.
Returns
true
if this source file identify a main grammar (so, has a main rule).
false
otherwise.
Definition at line 282 of file GrammarPrimitive.java.
References it.emarolab.cagg.core.language.syntax.GrammarPrimitive.mainRuleName.
String it.emarolab.cagg.core.language.syntax.GrammarPrimitive.searchMainRuleName ()
This method (not called on constructor) returns the node data attached to the ASN that defines the main source file and its main rule. To note that it breaks the searching loop when the first occurrence is found. It is important to know that this implementation is not efficient and so it is raccomanded to call it as few times as possible, see also isMainGrammar() and getMainRuleName().
Returns
an empty String if the preamble map does not contains a it.emarolab.cagg.core.language.syntax.abstractTree.syntaxNodeType.StartSyntaxNode node. Otherwise it returns the node data attached to it (e.g. the name of the main rule).
Definition at line 266 of file GrammarPrimitive.java.
References it.emarolab.cagg.core.language.syntax.GrammarPrimitive.mainRuleName, and it.emarolab.cagg.core.language.syntax.GrammarPrimitive.preambleMap.
Map<Long, ExpressionNode<?> > it.emarolab.cagg.core.language.syntax.GrammarPrimitive.setExpressionsNodesMap (Map< Long, RuleSyntaxNode > ruleMap) private
Definition at line 102 of file GrammarPrimitive.java.
Referenced by it.emarolab.cagg.core.language.syntax.GrammarPrimitive.GrammarPrimitive().
Map< Long, AbstractSyntaxNode<?> > it.emarolab.cagg.core.language.syntax.GrammarPrimitive.setPreambleMap (AbstractSyntaxNode<?> tree) private
Definition at line 78 of file GrammarPrimitive.java.
Referenced by it.emarolab.cagg.core.language.syntax.GrammarPrimitive.GrammarPrimitive().
Map< Long, RuleSyntaxNode> it.emarolab.cagg.core.language.syntax.GrammarPrimitive.setRuleMap (AbstractSyntaxNode<?> tree) private
Definition at line 90 of file GrammarPrimitive.java.
Referenced by it.emarolab.cagg.core.language.syntax.GrammarPrimitive.GrammarPrimitive().
String it.emarolab.cagg.core.language.syntax.GrammarPrimitive.toString ()
Returns the description given on constructor GrammarCreator.GrammarPrimitive#GrammarCreator.Grammar(TextualParser) as
parser.toString()
See Also
java.lang.Object::toString()
Definition at line 304 of file GrammarPrimitive.java.
References it.emarolab.cagg.core.language.syntax.GrammarPrimitive.parserToString.
Member Data Documentation
Map< Long, ExpressionNode<?> > it.emarolab.cagg.core.language.syntax.GrammarPrimitive.expMap private
Definition at line 51 of file GrammarPrimitive.java.
Referenced by it.emarolab.cagg.core.language.syntax.GrammarPrimitive.GrammarPrimitive().
String it.emarolab.cagg.core.language.syntax.GrammarPrimitive.mainRuleName = "" private
Definition at line 55 of file GrammarPrimitive.java.
Referenced by it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getMainRule(), it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getMainRuleExpressionTree(), it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getMainRuleName(), it.emarolab.cagg.core.language.syntax.GrammarPrimitive.isMainGrammar(), and it.emarolab.cagg.core.language.syntax.GrammarPrimitive.searchMainRuleName().
String it.emarolab.cagg.core.language.syntax.GrammarPrimitive.parserToString private
Definition at line 53 of file GrammarPrimitive.java.
Referenced by it.emarolab.cagg.core.language.syntax.GrammarPrimitive.GrammarPrimitive(), and it.emarolab.cagg.core.language.syntax.GrammarPrimitive.toString().
Map< Long, AbstractSyntaxNode<?> > it.emarolab.cagg.core.language.syntax.GrammarPrimitive.preambleMap private
Definition at line 49 of file GrammarPrimitive.java.
Referenced by it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getPreambleMap(), it.emarolab.cagg.core.language.syntax.GrammarPrimitive.GrammarPrimitive(), and it.emarolab.cagg.core.language.syntax.GrammarPrimitive.searchMainRuleName().
AbstractSyntaxNode<?> it.emarolab.cagg.core.language.syntax.GrammarPrimitive.preambleTree private
Definition at line 47 of file GrammarPrimitive.java.
Referenced by it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getPreambleTree(), and it.emarolab.cagg.core.language.syntax.GrammarPrimitive.GrammarPrimitive().
Map< Long, RuleSyntaxNode> it.emarolab.cagg.core.language.syntax.GrammarPrimitive.ruleMap private
Definition at line 50 of file GrammarPrimitive.java.
Referenced by it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getBodyMap(), it.emarolab.cagg.core.language.syntax.GrammarPrimitive.getNamedRule(), and it.emarolab.cagg.core.language.syntax.GrammarPrimitive.GrammarPrimitive().
The documentation for this class was generated from the following file:
/home/luca-phd/Documents/school luca/dottorato/research/verbal interface/speech_workspace/concept_action_grammar_generator/src/it/emarolab/cagg/core/language/syntax/GrammarPrimitive.java